### ISSUE TITLE
App Menu Integration 

### ISSUE THREAD

**Issue by Newt-OS** [rilian-la-te/vala-panel-appmenu#10]
Not sure if this is the place to write this, if not, then just ask me to remove it.

Anyway, I was trying out this menu in Xubuntu (15.10 if that's relevant).  I have found that your menu works better than the XFCE topmenu plugin, especially when used with Vala Panel.  However, for a lot of apps like terminals, text editors, and other core-type apps, the menu only displayed the application's name with the option to choose between open windows.  

I have seen posts of the appmenu plugin and Vala Panel with a full global menu for specific apps (Thunar, Mousepad) that would not display a full menu for me.  Is this an issue with my system (ubuntu, xfce session) or am I missing a package?  

Thanks,
~Newt

**Comment by rilian-la-te** [comment]
Newt, do you install appmenu* packages and unity-gtk-module?

**Comment by Newt-OS** [comment]
I will try that and let you know how it goes.  Thanks for the help.

~Newt

**Comment by JuHwon** [comment]
What package did you install on xubuntu?
i got xubuntu 16.04 and i got the following packages:
```
unity-gtk-module-common - Common files for GtkMenuShell D-Bus exporter
unity-gtk2-module - GtkMenuShell D-Bus exporter
unity-gtk3-module - GtkMenuShell D-Bus exporter
unity-gtk-module-autopilot - GtkMenuShell D-Bus Autopilot tests
```

I currently have installed the `unity-gtk-module-common` and the `unity-gtk3-module`

Still the app menu plugin in the xfce panel is not working for e.g. xfce-terminal or thunar.
Chrome is working fine.

What am i mssing here?

**Comment by rilian-la-te** [comment]
Unity-gtk2-module

**Comment by JuHwon** [comment]
already installed and still the same issue. is there any specific configuration required?

**Comment by rilian-la-te** [comment]
Start unity-gtk-module, please:-))

**Comment by rilian-la-te** [comment]
Use .gtkrc to start unity-gtk-module on login

**Comment by JuHwon** [comment]
big thx! :) awesome!

**Comment by NicolasThierion** [comment]
Thank you for your work.
I have the same problem: Appmenu works fine for some application (ie: chrome), but I can't get it to work with mousepad or terminal for example (it displays only the application name).

I run xubuntu 16.10.
I installed these dependencies:
` unity-gtk2-module, unity-gtk3-module, unity-gtk-common, appmenu-qt.`
I created these files : 
`
 - ~/.gtkrc
 - ~/.gtkrc-2.0
 - ~/.config/gtk-2.0/settings.ini
 - ~/.config/gtk-3.0/settings.ini
`
tried GTK_MODULES=unity-gtk-module within .gtkrc with no success.

I will appreciate if you have any clue

**Comment by rilian-la-te** [comment]
Weird ubuntu issues:(

**Comment by funkholio** [comment]
hi, i tried but not succeded. i do all the steps but vala panel dont show on xfce panel
(sorry for my english)

**Comment by rilian-la-te** [comment]
Screen, please.

**Comment by marreto** [comment]
Hi. I have a problem with some applications that doesn`t integrate correctly to the panel too. My specific problem is with the software ~Krita~ 
I knew it was qt4 based, and now, the version Im using has been ported to qt5. So I thought It should work fine, but it doesnt. Gimp, btw, works very nice with the panel.
![screenshot_2017-04-09_22-15-03](https://cloud.githubusercontent.com/assets/27174016/24842742/11840a92-1d72-11e7-89b1-d27af8514e95.png)

**Comment by rilian-la-te** [comment]
I will investigate this.

**Comment by rilian-la-te** [comment]
If possible, can you test Krita in Unity?

**Comment by rilian-la-te** [comment]
Worksforme, 
![screenshot at 2017-04-10 10-00-14](https://cloud.githubusercontent.com/assets/1329638/24847839/5678109e-1dcc-11e7-8039-dab041979928.png)

**Comment by marreto** [comment]
I tested other software and every program runs fine except for KDE applications. I installed kwave, Korganizer, Kmail and none of them work with the appmenu. Could it be something I did wrong installing the appmenu?
![screenshot_2017-04-10_14-56-42](https://cloud.githubusercontent.com/assets/27174016/24875718/64820c7a-1dff-11e7-90dd-52fc52659026.png)

**Comment by rilian-la-te** [comment]
KDE4 Apps? If so, you must install appmenu-qt

**Comment by rilian-la-te** [comment]
And what qt5 version are you using?

**Comment by marreto** [comment]
I already have appmenu-qt4 installed. but I think those app use qt5.
I`m using qt5 from arch repo, v5.8.0-7

**Comment by rilian-la-te** [comment]
Ok, what about pure Qt applications? It uses AppMenu? If yes, you may try to enable appmenu in KDE settings.

**Comment by marreto** [comment]
Yesterday I installed things and messed with kde setthings with no success ( I didn`t really know what I was doing). And when I booted up this morning, IT WORKED! Unfortunately I don`t know what happened, but it works now. Thanks man!
![screenshot_2017-04-11_07-27-59](https://cloud.githubusercontent.com/assets/27174016/24904909/711c296e-1e88-11e7-8771-2df613e06f0f.png)
