### ISSUE TITLE
Nothing change in solus budgie

### ISSUE THREAD

**Issue by earlcherry** [rilian-la-te/vala-panel-appmenu#101]
Hello. After successful installation i cant find new applet. What im doing wrong?
I use flags: cmake -DENABLE_BUDGIE=ON -DENABLE_UNITY_GTK_MODULE=ON ..

**Comment by rilian-la-te** [comment]
CMAKE_INSTALL_PREFIX - ?

**Comment by rilian-la-te** [comment]
It is fixed, AFAIK. If bug reappears, feel free to reopen.
