### ISSUE TITLE
qt5ct works intermittently

### ISSUE THREAD

**Issue by darthoctopus** [rilian-la-te/vala-panel-appmenu#104]
When I use qt5ct, I can use the dbus global menu once in a while, but most of the time I get the following error message:

```
Failed to register window menu, reason: org.freedesktop.DBus.Error.NoReply ("Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.")
```

This doesn't happen when I'm using appmenu-qt5

**Comment by darthoctopus** [comment]
May be related to #40?

**Comment by darthoctopus** [comment]
I've managed to capture the output of dbus-monitor when it's working and not working.

[logs.zip](https://github.com/rilian-la-te/vala-panel-appmenu/files/1099365/logs.zip)

**Comment by darthoctopus** [comment]
Relevant: when it doesn't work, it hangs around line 837 of the not working log:

```
method call time=1498266455.143512 sender=:1.34 -> destination=:1.138 serial=5010 path=/MenuBar/2; interface=org.freedesktop.DBus.Properties; member=GetAll
```

yielding

```
error time=1498266479.982908 sender=:1.138 -> destination=:1.34 error_name=org.freedesktop.DBus.Error.UnknownObject reply_serial=5010
   string "No such object path '/MenuBar/2'"
```

**Comment by rilian-la-te** [comment]
This is bug of qt5ct, if it works without it.

**Comment by darthoctopus** [comment]
Noted, I have filed a bug report on the qt5ct tracker.
