### ISSUE TITLE
vala-panel-appmenu in xfce4 under Gentoo linux - Failed to load module "libappmenu-gtk-module"

### ISSUE THREAD

**Issue by nkichukov** [rilian-la-te/vala-panel-appmenu#105]
ebuild sourced from the lxde-gtk3 overlay with some slight mods as per the below:

		$(cmake-utils_use_enable xfce)
		$(cmake-utils_use_enable vala-panel VALAPANEL)
		$(cmake-utils_use_enable wnck)
		-DGSETTINGS_COMPILE=OFF
		-DVALA_EXECUTABLE:NAMES=valac-0.34
		-DENABLE_UNITY_GTK_MODULE=ON
		-DMAKE_BOLD_APPNAME=ON

with xfce and wnck flags enabled, which ends up into:

cmake --no-warn-unused-cli -C /var/tmp/portage/x11-misc/vala-panel-appmenu-9999/work/vala-panel-appmenu-9999_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_xfce=ON -DENABLE_XFCE=ON -DENABLE_Xfce=ON -DENABLE_VALAPANEL=OFF -DENABLE_wnck=ON -DENABLE_WNCK=ON -DENABLE_Wnck=ON -DGSETTINGS_COMPILE=OFF -DVALA_EXECUTABLE:NAMES=valac-0.34 -DENABLE_UNITY_GTK_MODULE=ON -DMAKE_BOLD_APPNAME=ON -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/x11-misc/vala-panel-appmenu-9999/work/vala-panel-appmenu-9999_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/x11-misc/vala-panel-appmenu-9999/work/vala-panel-appmenu-9999_build/gentoo_toolchain.cmake  /var/tmp/portage/x11-misc/vala-panel-appmenu-9999/work/vala-panel-appmenu-9999

The package compiles and installs alright:
   usr/lib64/libappmenu-gtk2-parser.so.0.5.2
   usr/lib64/libappmenu-gtk3-parser.so.0.5.2
   usr/lib64/gtk-3.0/modules/libappmenu-gtk-module.so
   usr/lib64/gtk-2.0/modules/libappmenu-gtk-module.so
   usr/lib64/xfce4/panel/plugins/libappmenu-xfce.so

The applet can be added in the xfce4-panel, and works fine with google-chrome for example.
However, for gtk2 applications the below error is printed in .xsession-error log:
$ hexchat 
Gtk-Message: Failed to load module "libappmenu-gtk-module"
**
ERROR:/var/tmp/portage/x11-misc/vala-panel-appmenu-9999/work/vala-panel-appmenu-9999/unity-gtk-module/src/platform.c:134:gtk_widget_set_property_string: code should not be reached
Aborted

The schema is installed and compiled:
$ gsettings list-schemas | grep vala
org.valapanel.appmenu-gtk-module

the shell environment is setup as instructed:
$ env | grep GTK
GTK_MODULES=canberra-gtk-module:appmenu-gtk-module
$ env | grep UBUNTU
UBUNTU_MENUPROXY=1

What am I missing here to get the menu show in the panel? 

Thank you,
-Nikolay

**Comment by rilian-la-te** [comment]
Will look for it.
