### ISSUE TITLE
debian xfce make issues with "unity-gtk-module"

### ISSUE THREAD

**Issue by tiledman** [rilian-la-te/vala-panel-appmenu#106]
I'm trying to install this on Debian Testing and all has worked until I had to make the file. I get an error when trying to use -DENABLE_UNITY_GTK_MODUEL=ON

Is there something simple I'm missing?

> [ 77%] Built target appmenu-gtk3-parser
Scanning dependencies of target appmenu-gtk3-module
[ 77%] Building C object unity-gtk-module/src/CMakeFiles/appmenu-gtk3-module.dir/platform.c.o
/home/tiles/Documents/Clone-Folder/vala-panel-appmenu/unity-gtk-module/src/platform.c:7:28: fatal error: gdk/gdkwayland.h: No such file or directory
 #include <gdk/gdkwayland.h>
                            ^
compilation terminated.
unity-gtk-module/src/CMakeFiles/appmenu-gtk3-module.dir/build.make:86: recipe for target 'unity-gtk-module/src/CMakeFiles/appmenu-gtk3-module.dir/platform.c.o' failed
make[2]: *** [unity-gtk-module/src/CMakeFiles/appmenu-gtk3-module.dir/platform.c.o] Error 1
CMakeFiles/Makefile2:281: recipe for target 'unity-gtk-module/src/CMakeFiles/appmenu-gtk3-module.dir/all' failed
make[1]: *** [unity-gtk-module/src/CMakeFiles/appmenu-gtk3-module.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rilian-la-te** [comment]
Do you have libgtk3-dev?
This file is here: [libgtk3-dev filelist](https://packages.debian.org/testing/i386/libgtk-3-dev/filelist)

**Comment by tiledman** [comment]
I didn't have it installed so I installed it but I got the same error

**Comment by rilian-la-te** [comment]
you need all devel packages. do you see file in place?

**Comment by tiledman** [comment]
I'm not sure quite what that means

**Comment by rilian-la-te** [comment]
If you use such distro, you must install all corresponding devel packages.

**Comment by tiledman** [comment]
Is there a way I can know which ones I don't have the dev version of?

**Comment by rilian-la-te** [comment]
I does not know for debian, sorry, I am arch user. You need devels for gtk2, gtk3, glib, and selected panels.

**Comment by rilian-la-te** [comment]
Exact names I do not know:(

**Comment by rilian-la-te** [comment]
Closed as INVALID. (Misconfiguration)
