### ISSUE TITLE
menu getting unresponsive after a few hours of use

### ISSUE THREAD

**Issue by nkichukov** [rilian-la-te/vala-panel-appmenu#107]
Hello,

I have been running the menu for a few hours then I figured that clicking on it does not do anything.

Not sure if that can tell anything, but the errors in the xsession-error log are as follows:

(wrapper-2.0:11136): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_is_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_is_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_is_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_is_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_is_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_is_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_is_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
(wrapper-2.0:11136): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed

Above is printed when I move the mouse over the menu or click on it and nothing reacts, the process id is:
/usr/lib64/xfce4/panel/wrapper-2.0 /usr/lib64/xfce4/panel/plugins/libappmenu-xfce.so 7 20971563 appmenu AppMenu Plugin Display AppMenu (Global Menu)

Running xfce4-panel -r (restarting the whole panel) fixes the problem until it reappears later. 

Menu compiled with the options from issue #105 . Anyone else saw this?

Cheers,
-Nik

**Comment by rilian-la-te** [comment]
What applications are you using when bug appears?

**Comment by nkichukov** [comment]
I am not aware this is caused by a specific application. It is after some time I realize it has stopped working. Have you seen this with some specific applications? Are those in the blacklist of the schema?

I will try to pick up on what application caused it, even though I am reusing the apps(same apps) and it works with them in the beginning and then later on it stops working for the same apps it used to work. The menu is is drawn and changes by switching the applications, but cannot be actioned, so clicking does nothing.

Cheers,
-N

**Comment by nkichukov** [comment]
I've updated to the latest code today and will see if I can reproduce this issue.

**Comment by rilian-la-te** [comment]
Let's see. I think this is https://github.com/rilian-la-te/vala-panel-appmenu/issues/156, but just unnoticed.

**Comment by rilian-la-te** [comment]
Please test latest release.

**Comment by nkichukov** [comment]
This has not happened for me for quite some time now. I will close this now.
Thank you!
