### ISSUE TITLE
[Debian 9 XFCE] How to add the applet to panel?

### ISSUE THREAD

**Issue by ajcerejeira** [rilian-la-te/vala-panel-appmenu#109]
I followed all the instructions to compile and install, and everything worked fine, then followed the post-install guide for non ubuntu and non arch distros, and finally i typed `xfconf-query -c xsettings -p /Gtk/ShellShowsMenubar -n -t bool -s true xfconf-query -c xsettings -p /Gtk/ShellShowsAppmenu -n -t bool -s true` and restarted the computer. However i cannot add the vala appmenu to the panel, since it does not appear on the "add new items to panel" menu on xfce.

**Comment by rilian-la-te** [comment]
CMAKE_INSTALL_PREFIX - ?

**Comment by ajcerejeira** [comment]
I didn't change that variable was it necessary?

**Comment by rilian-la-te** [comment]
yes, you need to install everything in /usr

**Comment by ajcerejeira** [comment]
I just ran (in `vala-appmenu/build' dir):

`cmake -DENABLE_XFCE=ON -DENABLE_JAYATANA=ON -DENABLE_UNITY_GTK_MODULE=ON -DMAKE_BOLD_APPNAME=ON -DCMAKE_INSTALL_PREFIX=/usr/local ..`

then `make && sudo make install`, restarted and yet nothing

**Comment by rilian-la-te** [comment]
```-DCMAKE_INSTALL_PREFIX=/usr```

Should be.

**Comment by ajcerejeira** [comment]
Ok I changed that, tried everything again and it still does not show in XFCE applets list.

Here are the outputs of the commands that i have run:

[cmake_output.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1131700/cmake_output.txt)
[make_output.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1131701/make_output.txt)
[make_install_output.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1131704/make_install_output.txt)

**Comment by rilian-la-te** [comment]
Install devel packages first

**Comment by rilian-la-te** [comment]
It build without any panel

**Comment by ajcerejeira** [comment]
Thanks, which devel packages? I installed `xfce4-panel-dev` and `xfce4-dev-tools` and tried again and still nothing...

[cmake_output.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1131723/cmake_output.txt)
[make_output.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1131724/make_output.txt)
[make_install_output.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1131725/make_install_output.txt)

**Comment by rilian-la-te** [comment]
I am an arch user, so, I do not know:( Ask Ubuntu guys:) for example, @flexiondotorg

**Comment by ajcerejeira** [comment]
It's working! I installed the following packages: `libxfce4util-dev libxfcegui4-dev  libxfce4ui-2-dev libxfce4panel-2.0-dev`
