### ISSUE TITLE
Segfaults after WARNING **: Failed to fetch path: Timeout was reached

### ISSUE THREAD

**Issue by zezic** [rilian-la-te/vala-panel-appmenu#11]
Sometimes when switching from one window to another i get
`** (vala-panel:10661): WARNING **: Failed to fetch path: Timeout was reached`
and after some time (about 1 minute) panel segfaults:
`Segmentation fault`
Not sure if it related to appmenu or vala-panel, but seems like appmenu side problem.
Ubuntu 15.10 (amd64), vala-panel + vala-panel-appmenu.

How can i debug vala-panel with vala-panel-appmenu?
I'm trying to figure out which app cause this behaviour atm.

**Comment by rilian-la-te** [comment]
You can debug vala-panel-appmenu with XFCE panel. I think you does not have bamfdaemon.

**Comment by zezic** [comment]
Strange. I added `stdout.printf("Hello, world\n");` in `on_window_added` function and plugin in vala-panel doesn't crashes anymore, but crashes in xfce4-panel after following actions:

1. Open gnome-terminal (3.16.2)
2. Navigate to Help > About
3. Focus on appeared "About" window
4. Close "About" window and focus back to terminal window

appmenu freezes with "Terminal" and doesn't respond to clicks and window switches, window resizing produces this output continuosly:
```
** (wrapper-2.0:1176): WARNING **: Failed to fetch path: Timeout was reached
** (wrapper-2.0:1176): WARNING **: Failed to get application for xid 10273386: Timeout was reached
** (wrapper-2.0:1176): WARNING **: Failed to fetch property `_GTK_UNIQUE_BUS_NAME': Timeout was reached
** (wrapper-2.0:1176): WARNING **: Failed to fetch path: Timeout was reached
** (wrapper-2.0:1176): WARNING **: Failed to get application for xid 10273386: Timeout was reached
```
and after some time i see following:
```
xfce4-panel(external): appmenu-1: child is unembedded
xfce4-panel(external): appmenu-1: child exited with status 0
```
and appmenu disappeared.

**Comment by rilian-la-te** [comment]
I will try to fix it in free time, but see README. This is BAMF failure, I
think:-))

**Comment by rilian-la-te** [comment]
I close it as invalid for now. If you have relevant info - feel free to reopen.
