### ISSUE TITLE
Support for Java apps is broken ?

### ISSUE THREAD

**Issue by arifcatalyst** [rilian-la-te/vala-panel-appmenu#115]
I build with `-DENABLE_JAYATANA=ON` but still, it doesn't work for any Java Apps.

[log_file.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1153408/log_file.txt)
[install_log_file.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1153410/install_log_file.txt)

**Comment by rilian-la-te** [comment]
Do instructions work? Do you found jayatana instructions in the Internet at all?

**Comment by arifcatalyst** [comment]
These instructions worked in Unity-desktop. I am on Manjaro-XFCE Desktop.

You just have to edit `gedit ~/.IntelliJIdea2016.1/idea64.vmoptions` 
and add `-javaagent:/usr/share/java/jayatanaag.jar` this line in the end

**Comment by rilian-la-te** [comment]
Can you post a log with Idea and my jayatana?

**Comment by arifcatalyst** [comment]
You mean the Build and install logs ?

**Comment by rilian-la-te** [comment]
You need Java log files for Idea. I need to look for agent loading.

**Comment by arifcatalyst** [comment]
Please tell me how to get Java log files. It's not in my home directory as instructed in Oracle documentation.

**Comment by rilian-la-te** [comment]
You must consult Idea's documentation?

**Comment by arifcatalyst** [comment]
@rilian-la-te I posted above.

**Comment by rilian-la-te** [comment]
Agent is not loading. I need futher look. Will look for it tomorrow. Can you post Idea log with Ubuntu agent?

**Comment by arifcatalyst** [comment]
I don't have an Ubuntu installation right now, but will run in Virtual and will get you the log.

**Comment by rilian-la-te** [comment]
Thanks. If agent is not loading, I need to look closer. You can try get jayatanaag,jar from Ubuntu and copy it (they should be identical).

**Comment by arifcatalyst** [comment]
Here is the Log file for Idea in Ubuntu 16.04 LTS working perfectly by editing .vmoptions.
[idea (copy).txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1154962/idea.copy.txt)

![screenshot from 2017-07-18 07-19-07](https://user-images.githubusercontent.com/26674272/28305045-b726af08-6b89-11e7-9e42-0dde5b327a56.png)

**Comment by rilian-la-te** [comment]
Agent does not loaded. Try jayatanag from ubuntu (copy jar to arch). If it will work. I will fix my JAR generating.

**Comment by arifcatalyst** [comment]
@rilian-la-te Tried jayatanag from Ubuntu.It doesn't work.

**Comment by rilian-la-te** [comment]
So, you need to fix your config first. And then try also jayatana.jar from Ubuntu.

**Comment by arifcatalyst** [comment]
Config from Idea ? I can't understand, if the same config worked in Ubuntu

**Comment by rilian-la-te** [comment]
then try jayatana.jar from Ubuntu.

**Comment by arifcatalyst** [comment]
I tried jayatana.jar from Ubuntu. It doesn't work

**Comment by rilian-la-te** [comment]
Ok, will look for it.

**Comment by rilian-la-te** [comment]
what about environment variables?

**Comment by arifcatalyst** [comment]
`java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
`

**Comment by rilian-la-te** [comment]
you need to try variables XDG_CURRENT_DESKTOP, JAYTANA and JAYATANA_FORCE.

**Comment by arifcatalyst** [comment]
I have to append this line in the launch command ?

**Comment by rilian-la-te** [comment]
Please, read about environment variables. It is a big concept.

**Comment by arifcatalyst** [comment]
Oh, My It worked now. 
![screenshot_2017-07-18_13-26-16](https://user-images.githubusercontent.com/26674272/28306394-c064e052-6bbc-11e7-9b2b-ca67dcf3a832.png)

**Comment by rilian-la-te** [comment]
How?

**Comment by arifcatalyst** [comment]
By just appending the variable before the launch command.

**Comment by arifcatalyst** [comment]
Menus doesn't respond with environment variables.

**Comment by rilian-la-te** [comment]
Symptoms?

**Comment by arifcatalyst** [comment]
Yes, Menus show the drop-down but on clicking, it doesn't perform any action.

**Comment by rilian-la-te** [comment]
Need to try to use menus from raw DBus. Ubuntu JARs help?

**Comment by arifcatalyst** [comment]
I cannot follow you.

**Comment by rilian-la-te** [comment]
What?

**Comment by arifcatalyst** [comment]
> Need to try to use menus from raw DBus. Ubuntu JARs help?

I don't understand what do you mean by above line

**Comment by rilian-la-te** [comment]
1. Someone need to try to use menu actions from raw DBus, not from clicking by applet.
2. Copying Ubuntu JARs help against issue?

**Comment by arifcatalyst** [comment]
>Copying Ubuntu JARs help against issue? 
No, it doesn't help. 

I don't get your 1 point.

**Comment by arifcatalyst** [comment]
@rilian-la-te Global Menu doesn't work on Vlc too

**Comment by rilian-la-te** [comment]
It works on VLC. For me, at least. What symptoms are you have?

**Comment by arifcatalyst** [comment]
![screenshot_2017-07-20_16-38-13](https://user-images.githubusercontent.com/26674272/28414569-e8e7f876-6d69-11e7-8397-60869c4946a6.png)

**Comment by rilian-la-te** [comment]
Do you use qt5ct?

**Comment by arifcatalyst** [comment]
No

**Comment by rilian-la-te** [comment]
show me QT_QPA_PLATFORMTHEME

**Comment by arifcatalyst** [comment]
<QT_QPA_PLATFORMTHEME: command not found/>

**Comment by rilian-la-te** [comment]
use ```echo $QT_QPA_PLATFORMTHEME```

**Comment by arifcatalyst** [comment]
Yes `qt5ct`
I thought you were talking about qt version of Vlc

**Comment by rilian-la-te** [comment]
you need to turn it off, it conflicts with dbusmenu.

**Comment by arifcatalyst** [comment]
Can you guide me, how do I ?

**Comment by rilian-la-te** [comment]
remove it with pacman:)

**Comment by arifcatalyst** [comment]
yeah lol, you said `turn it off`

**Comment by rilian-la-te** [comment]
it is more difflicult. You need to replace all instances of environment variable QT_QPA_PLATFORMTHEME from qt5ct to gtk.

**Comment by arifcatalyst** [comment]
Cannot remove it, One package `manjaro-xfce-settings` needs qt5ct.

**Comment by rilian-la-te** [comment]
Search similar closed issues in bugtracker, please. And try qt5ct from git.

**Comment by arifcatalyst** [comment]
I have installed `qt5ct-svn` as per the bugtracker here [https://sourceforge.net/p/qt5ct/tickets/34/](url)

**Comment by rilian-la-te** [comment]
It works?

**Comment by arifcatalyst** [comment]
No

**Comment by rilian-la-te** [comment]
Try rebooting after qt5ct-svn installed.

**Comment by arifcatalyst** [comment]
Maybe, it will work for Java apps now.

**Comment by rilian-la-te** [comment]
Strange. Try to run ```QT_QPA_PLATFORMTHEME=gtk vlc``` Appmenu exists?

**Comment by rilian-la-te** [comment]
Do you have appmenu for Qt5 apps? (SMPlayer for example)?

**Comment by snippins** [comment]
@rilian-la-te Today I try to build with jayatana enabled. But the build failed with:

`core/swing/SwingGTKFixed.java:29: error: package com.sun.java.swing.plaf.gtk does not exist`

Any idea what might be the reason?

**Comment by arifcatalyst** [comment]
> 

Strange. Try to run QT_QPA_PLATFORMTHEME=gtk vlc Appmenu exists?
--


appmenu link is broken in AUR repository

**Comment by rilian-la-te** [comment]
Not package, but menu itself.

**Comment by arifcatalyst** [comment]
Yes

**Comment by snippins** [comment]
@arifcatalyst He means to launch vlc with the command "QT_QPA_PLATFORMTHEME=gtk vlc" in terminal to and check if the menu plugin work with that command.

@rilian-la-te, @arifcatalyst  To avoid further misunderstandings, I think you guys should use more formal English with longer sentences to communicate. (I mean no offense or disrespect, I am not an English speaker myself).

**Comment by arifcatalyst** [comment]
> 

Strange. Try to run QT_QPA_PLATFORMTHEME=gtk vlc Appmenu exists?
--

I have the menu but it's not global

**Comment by rilian-la-te** [comment]
Wxwidgets version? Or qt4 version? Or gtk version?

**Comment by arifcatalyst** [comment]
Qt4 version-`qt4 4.8.7-22`

**Comment by rilian-la-te** [comment]
ok. Do you have appmenu-qt4 installed? What toolkit VLC using?

**Comment by arifcatalyst** [comment]
Yes, after installing `appmenu-qt4`, global menu works in Vlc, but Java apps like IntelliJ and Pycharm refuses to work even with environmental variable.
The menu is visible in Pychram by appending env var `XDG_CURRENT_DESKTOP-Unity` but it is not actionable, clicking on it doesn't work.

**Comment by rilian-la-te** [comment]
confirmed.

**Comment by rilian-la-te** [comment]
JAyatana works, except for JetBrains. Will look for solution for JetBrains.
