### ISSUE TITLE
budgie-desktop completely freezes with the appmenu

### ISSUE THREAD

**Issue by fossfreedom** [rilian-la-te/vala-panel-appmenu#116]
Martin has now packaged and uploaded v0.5.2 to Ubuntu Artful (17.10)

https://launchpad.net/ubuntu/+source/vala-panel-appmenu

I installed the binary package budgie-appmenu-applet, logged out, logged in, added the appmenu applet to the panel.

I then opened libreoffice calc.  Checked that the appmenu correctly displayed by clicking on one of the displayed menus.  Then I clicked on the budgie menu icon (top left).  At that point the whole desktop completely froze.

**Comment by rilian-la-te** [comment]
Add budgie-panel into unity-gtk-module's blacklist. Ubuntu does not use appmenu-gtk-module and my fixes for this bug.

If such adding works, close the bug, please.

**Comment by fossfreedom** [comment]
hmm - I now remembered I brought this up before - https://github.com/rilian-la-te/vala-panel-appmenu/commit/ee82d6cbb938f1f5519d29c9dee5c58b4ec42443

thanks
