### ISSUE TITLE
Text looks weird after clicked

### ISSUE THREAD

**Issue by re23071998** [rilian-la-te/vala-panel-appmenu#117]
unclicked : http://www.4gp.me/ba3s/1500698931868.jpg
clicked : http://www.4gp.me/ba3s/1500699164222.jpg

i use xfce4-panel

**Comment by rilian-la-te** [comment]
Look into your theme, please

**Comment by re23071998** [comment]
theme is arc

**Comment by rilian-la-te** [comment]
May your panel size is too small and margins cuts text. Try to increase panel size.
