### ISSUE TITLE
Menu visual glitch when the panel is at bottom of the screen. (xfce4-panel)

### ISSUE THREAD

**Issue by snippins** [rilian-la-te/vala-panel-appmenu#119]
Not sure if this a gtk problem or the plugin. When the panel is at the bottom, the menu does not extend to fully use the screen height and most entries are hidden. This happens with Firefox and electron apps, which builds the menu dynamically.

![image](https://user-images.githubusercontent.com/6032077/28491208-870984be-6f1f-11e7-9f1d-39c2fb3617ed.png)

**Comment by snippins** [comment]
@rilian-la-te It is indeed gtk fault. They unable to calculate the view box in time after we called AboutToShow() or send "opened" event.

I have a workaround for this (dbus-gtk.vala)
```

        private void open_cb()
        {
            get_root_item().handle_event("opened",null,0);
            get_root_item().request_about_to_show();
            root_menu.queue_resize();
            foreach(unowned Item i in get_root_item().get_children()) 
            {
                i.request_about_to_show();
                i.handle_event("opened",null,0);
            }

        }
```

**Comment by rilian-la-te** [comment]
Can you make a PR for vala-dbusmenu?
