### ISSUE TITLE
thunar menubar not hiding 

### ISSUE THREAD

**Issue by JuHwon** [rilian-la-te/vala-panel-appmenu#12]
I am using xubuntu 16.04

Somehow my thunar menu bar at the window is not hiding automatically.
When i hide the menubar by myself then it is working for the current session though on logout/login the appmenu is also not showing it. :/

The same issue goes for xfce4-terminal.

I added `unity-gtk-module` in .profile to my env `GTK_MODULES`.
Do i need specific configurations?

**Comment by rilian-la-te** [comment]
Do you have gtk-shell-shows-menubar and gtk-shell-shows-appmenu in .gtkrc?

**Comment by JuHwon** [comment]
nope :/ - how should that .gtkrc file look like? i dont have such a file at all. sry for being such a newb.

**Comment by Malezha** [comment]
Analogous issue, thunar, terminal and sublime 3 duplicate menu.
The decision of [this topic](https://www.linux.org.ru/forum/desktop/11473563) does not help.

**Comment by Malezha** [comment]
Ok, copypaste style failed, .gtkrc should not begin with a `[Settings]`.

**Comment by Malezha** [comment]
@JuHwon create (or edit) .gtkrc, .gtkrc-2.0 and insert 
```
gtk-shell-shows-app-menu=1
gtk-shell-shows-menubar=1
```

**Comment by JuHwon** [comment]
thanks! awesome. its working now! 

do i need the settings.ini and the .gtkrc files? because first i tried to only use settings.ini files (had to create all files) and it did not work.

**Comment by Malezha** [comment]
Without `.gtkrc` menu will be duplicated.

**Comment by JuHwon** [comment]
kk thanks

**Comment by ASAPHAANING** [comment]
I followed these instructions and now I have a working appmenu- sort of.

Firefox/Thunderbird used to work and other apps didnt, now it's reversed. Also I lose appmenu functionality after launching sublime text.
