### ISSUE TITLE
Enhancement: Option to display window control buttons within the Global Menu (useful when the "undecorate maximized windows" option is selected)

### ISSUE THREAD

**Issue by GizmoChicken** [rilian-la-te/vala-panel-appmenu#120]
I'm loving the improved Global Menu in Ubuntu MATE. Thanks so much!

REQUEST: I'm not sure whether it would be difficult to implement, but would you please consider offering options to display window control buttons (close, min, and max/unmax buttons) within the Global Menu applet (preferably on its left side) whenever the associated window is maximized?

USE CASE:  If such an option were available, I would use the option in conjunction with the "undecorate maximized windows" option. Acting together, the two options would allow for closely approximating how Unity handles maximized windows.  (I'd likely use it with either the Cupertino or Mutiny layout.  But I wouldn't want to be restricted to using it with those two layouts.)

Of course, there will be many who won't want to display the window control buttons in the Global Menu applet at any time.  Also, I can imagine that, given an alternate set of window control buttons, some (but probably not many) may want to "undecorate" all windows, and then use only the window control buttons newly available in the Global Menu.

With the above in mind, I hope that the Global Menu could offer the following options:

      Display Window Control Buttons in Global Menu Applet:
      [ ]  Never (default)
      [x]  Only when associated window is maximized
      [ ]  Always

**Comment by rilian-la-te** [comment]
Wontfix, because of X dependency. I may suggest vala-panel and window controls plugin. I can port it to Mate. But no X in app menu.

**Comment by GizmoChicken** [comment]
Displaying control buttons (close, min, and max/unmax buttons) within a separate panel applet (rather than directly within the global menu applet) would certainly work.  And indeed, using such an approach, the window controls could be independently positioned on the panel, which may have some advantages.

But the downside is that the menu and window control functions, which should work together, wouldn't be as tightly integrated.  And from a cosmetic standpoint, I imagine that, unless the control buttons are integrated directly into the menu applet, they will probably look out-of-place.

You mention a "window controls plugin" in your reply.  I'm not familiar with any such plugin.  Do you have one in mind?

Also, just curious, but what's your objection to adding an X dependency?  You want to keep the menu simple, or is there something else that would block this approach?

If you don't want to mess with buttons, how about adding an optional menu pull-down that would allow the user to "close", "min", and "max/unmax" the focused window?

Yes, I suppose that the above described pull-down approach would still require an X dependency to get "min" and "max/unmax" functionality, but at least you couldn't skip theming, etc, that would be required for buttons.

I'll just add that, although the menus for most programs include "close" functionality, not many (almost none?) include "min" and "max/unmax" functionality.  So, once maximized with the "undecorate maximized windows" option on, it's not inititve how to "min" or "unmax" such a window.  That's why I'm pushing for this.

**Comment by rilian-la-te** [comment]
Against X. One word - Wayland. For now, menu almost unaware about X, it requires just bamf dbus calls. Menu must not know about window system, it is just a widget. 
Close can be done without using X, so it is implemented. 
About vala-panel - look to another repo in my page.

**Comment by GizmoChicken** [comment]
Thanks much for the reply!

I just learned about a discussion on the Ubuntu Mate forum regarding "[Developing a Window Buttons Applet for Mate](https://ubuntu-mate.community/t/developing-a-window-buttons-applet-for-mate/8637)."  It seems that the project is being developed [here](https://github.com/IKRadulov/mate-window-applets).

I hope that the buttons project will work well with your menu project.

**Comment by rilian-la-te** [comment]
I do not know. I have [vala-panel](https://github.com/rilian-la-te/vala-panel) and [window buttons applet for it.](https://github.com/rilian-la-te/vala-panel/blob/master/applets/wnck/buttons/buttons.vala)

**Comment by nikita-moor** [comment]
XFCE already has a "window button" panel: https://github.com/cedl38/xfce4-windowck-plugin
It works well.
