### ISSUE TITLE
No appmenu for GTK apps

### ISSUE THREAD

**Issue by wengarm** [rilian-la-te/vala-panel-appmenu#121]
I am an Arch user so at first I tried installing the vala-panel-appmenu-xfce-git AUR package. I thought GTK apps have the highest chance of working so I was testing it on them. The only thing that appeared was the app name so I thought it is not working. Then I decided to build it manually. I built the main thing then installed the appmenu-gtk, appmenu-qt and the files for chrome/chromium. I use firefox so I even though I was googling for help the appmenu was still showing just a name. Then I opened some qt app and noticed it works. I downloaded chromium to test it out and that works too. So the only thing not working for me are GTK apps. If I understood correctly as an Arch user I shouldn't be doing any edits to gtkrc and settings.ini right ?
I would love to provide more info but sadly I don't know what else to add. I would appreciate any help with my issue.

**Comment by wengarm** [comment]
I am using XFCE. With BSPWM as a WM if that can make any problems. I downloaded the "appmenu-gtk-module-git 0.4.4-2" from AUR as suggested in you readme. I did apply the two commands for xfce which are in the readme as well. What I did not do is add the two lines to .gtkrc and the export part to my .bashrc as it was part of "Enable unity-gtk-module on Ubuntu".

**Comment by rilian-la-te** [comment]
it can, if it carries xsettings. Show me a screen, please. And logs from terminal run, and GTK_MODULES.

**Comment by wengarm** [comment]
So I did a fresh install just to be sure. Currently I have a freshly installed XFCE and I am using it's WM as well. Here are two screenshots. One is showing chromium where the appmenu works and the other is showing thunar where it doesn't work.
![screenshot_2017-08-04_17-16-05](https://user-images.githubusercontent.com/25515867/28975077-ff2eefd8-7938-11e7-9167-7d53717aada1.png)
![screenshot_2017-08-04_17-17-05](https://user-images.githubusercontent.com/25515867/28975079-045b8ba6-7939-11e7-9dbb-f16722778506.png)
And "echo $GTK_MODULES" shows only canberra-gtk-module so I guess that is the reason why I am having issues ? The appmenu-gtk-module from AUR installed successfully.

**Comment by rilian-la-te** [comment]
Yes. You need to enable appmenu-gtk-module

**Comment by wengarm** [comment]
Ok so I added 
`if [ -n "$GTK_MODULES" ]; then
    GTK_MODULES="${GTK_MODULES}:unity-gtk-module"
else
    GTK_MODULES="unity-gtk-module"
fi

if [ -z "$UBUNTU_MENUPROXY" ]; then
    UBUNTU_MENUPROXY=1
fi

export GTK_MODULES
export UBUNTU_MENUPROXY`
this piece of code inside my bash_profile and now "echo $GTK_MODULES" shows unity-gtk-module:canberra-gtk-module. But the appmenu still doesn't work for me.

**Comment by rilian-la-te** [comment]
Module is called appmenu-gtk-module, not unity-gtk-module

**Comment by wengarm** [comment]
Everything is working as expected now. Thank you for your help, I would never figure it out on my own.
