### ISSUE TITLE
jayatana

### ISSUE THREAD

**Issue by PHPJosh** [rilian-la-te/vala-panel-appmenu#122]
Just wondering if jayatana is included in the Arch AUR package appmenu-gtk-module-git and if not do you plan on adding jayatana to the AUR package or plan to add one for jayatana? just wondering

**Comment by rilian-la-te** [comment]
Jayatana is expeimental now, you can use it in your own risk, so, no package.

**Comment by PHPJosh** [comment]
alright

**Comment by rilian-la-te** [comment]
Closed as duplicate of https://github.com/rilian-la-te/vala-panel-appmenu/issues/115
