### ISSUE TITLE
Separate the appmenu Dbus registrar into a service

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#123]
I have a working [Heads-Up Display (HUD)](https://github.com/ubuntu-mate/mate-hud)  that inter-operates with vala-panel-appmenu so long as the MATE applet is running.

Please can you separate the vala-panel-appmenu Dbus registrar to a service so that other consumers of 
the registrar can work regardless of having the vala-panel-appmenu applet in a panel.

**Comment by rilian-la-te** [comment]
Separation is not good decision, because it will strip menus from Qt applications. I can try do activatable registrar, which only work while HUD is opened.

**Comment by rilian-la-te** [comment]
Your HUD changes NET_ACTIVE_WINDOW or similar properties in BAMF?

**Comment by flexiondotorg** [comment]
@rilian-la-te No, `mate-hud` only has methods to get NET_ACTIVE_WINDOW, it doesn't change it.

**Comment by snippins** [comment]
@rilian-la-te Apart from the disadvantage above, it also has an advantage.

There are some QT/KDE apps like Krusader, Konsole only export the menus once. Thus if anyone add the plugin to some panels for the first time they might get confused by not seeing the menu showed up. 

In addition the menu also not appears if someone restart their panel for whatever reasons. They will need to restart these apps to see the menu again.

**Comment by rilian-la-te** [comment]
1. If this will be activatable registrar, this apps will export a menu again))))
2. Also can be solved with out-of-process registrar.

**Comment by sunweaver** [comment]
I'd love to see this feature, too.

**Comment by rilian-la-te** [comment]
We have outer registrar now)

**Comment by flexiondotorg** [comment]
Brilliant! Is there anything we need to know with regard to enabling it?

**Comment by rilian-la-te** [comment]
For now, I need testing))) It is dbus-activatable)

**Comment by rilian-la-te** [comment]
I now doing a new, release, so, closing it, this will be included.

**Comment by flexiondotorg** [comment]
Thank you for working on this. I'll test it over the next few days.
