### ISSUE TITLE
mate-applet-appmenu "swallows" all indicators in mate-indicator-applet

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#124]
Indicators are no longer displayed via [MATE Indicator Applet](https://github.com/mate-desktop/mate-indicator-applet) under the following conditions:

  * `GTK_MODULES="unity-gtk-module"` is correctly exported via `/etc/profile.d/appmenu.sh`.
  * `org.mate.interface/gtk-shell-shows-menubar` to `True`.
  * `mate-applet-appmenu`, from `vala-panel-appmenu` 0.5.3 or 0.5.2, is present in a panel.
  * `mate-indicator-applet-complete` is present in a panel.

The contents of `/etc/profile.d/appmenu.sh` is as follows:

```
if [ -z "$GTK_MODULES" ]; then
    GTK_MODULES="unity-gtk-module"
else
    GTK_MODULES="$GTK_MODULES:unity-gtk-module"
fi
export GTK_MODULES
export UBUNTU_MENUPROXY=1
```

`ps` shows that all the Indicators are running and in the case of Redshift it can be clearly seen it is running as the screen is colour shifted accordingly.

I have tried adding `['mate-panel', 'Mate-panel']` to `blacklist` in `com.canonical.unity-gtk-module` but no change. I also tried blacklist `'indicator-applet'`, also no change. It looks like the global menu is absorbing the Indicators.

This was tested on [Ubuntu MATE 17.10 daily](http://cdimage.ubuntu.com/ubuntu-mate/daily-live/current/). To reproduce the issue install Ubuntu MATE 17.10 daily in a VM, add `/etc/profile.d/appmenu.sh` as shown above, reboot and then use `mate-tweak` to change the panel layout to Cupertino, Contemporary or Mutiny.

**Comment by rilian-la-te** [comment]
1. how indicator binary is called?
2. do you tried appmenu-gtk-module instead of unity-gtk-module?

**Comment by rilian-la-te** [comment]
1. mate-panel is already blacklisted in appmenu-gtk-module
2. try to blacklist mate-indicator-applet, mate-indicator-applet-complete and mate-indicator-applet-appmenu

**Comment by flexiondotorg** [comment]
The source for mate-indicator-applet is here:

  * https://github.com/mate-desktop/mate-indicator-applet

The binaries it produces are:

  * `/usr/lib/mate-indicator-applet/mate-indicator-applet`
  * `/usr/lib/mate-indicator-applet/mate-indicator-applet-appmenu`
  * `/usr/lib/mate-indicator-applet/mate-indicator-applet-complete`

They are panel applet so added to a panel by right right clicking, I only use `mate-indicator-applet-complete`

**Comment by rilian-la-te** [comment]
blacklist them all:)

**Comment by flexiondotorg** [comment]
Thanks for the advice. Blacklisting the all appear to have solved it :-) I'll do some more testing to be sure. But looking good.

**Comment by flexiondotorg** [comment]
This is issue is resolved. Another was found. I'll raise a new issue.
