### ISSUE TITLE
The application's menu has disappeared but the xfce panel does not show the menu

### ISSUE THREAD

**Issue by hosxy** [rilian-la-te/vala-panel-appmenu#126]
Here is screenshot：
![deepinscreenshot_select-area_20170818230533](https://user-images.githubusercontent.com/17108640/29465546-40ac08ae-846c-11e7-92a5-326d0dae46fe.png)
OS : debian testing

**Comment by rilian-la-te** [comment]
Do you have application name on panel?

**Comment by whonchen** [comment]
There is no  application name on panel. And it is nothing about the globalmenu on panel.

**Comment by rilian-la-te** [comment]
look to install paths, please

**Comment by whonchen** [comment]
could you please describe in  detail,? Because I find no package named paths, and there are many packages that include this keyword "paths".

**Comment by rilian-la-te** [comment]
Where binary of this applet and other applets are located?

**Comment by whonchen** [comment]
All of them are in /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/
I have used this flags  -DCMAKE_INSTALL_PREFIX=/usr

**Comment by rilian-la-te** [comment]
And where desktop file points? (Which is installed with appmenu)?

**Comment by whonchen** [comment]
sorry,I couldn't understand your meaning. 
what do you mean which window focus on?

**Comment by rilian-la-te** [comment]
no. I want to know a link inside a desktop file installed by plugin.

**Comment by rilian-la-te** [comment]
Install bamfdaemon and add it to autostart. Closing this, because it is misconfiguration.
