### ISSUE TITLE
Source package fix

### ISSUE THREAD

**Issue by PHPJosh** [rilian-la-te/vala-panel-appmenu#127]
I would like to recommend to include the cmake @ d868e10 Source LInk and dbusmenu @ 7e68328 into the final release source package as without them RPMs fail to build on fedora.

**Comment by rilian-la-te** [comment]
can you provide a link to commits?

**Comment by rilian-la-te** [comment]
Try latest release, please:))))) Post here. If works, I will close the bug.

**Comment by rilian-la-te** [comment]
Closing it, as submodules is updated
