### ISSUE TITLE
Menus not showing in Debian 9.1

### ISSUE THREAD

**Issue by alvarezprado** [rilian-la-te/vala-panel-appmenu#128]
I followed the instructions to compile and configure vala-panel-appmenu for XFCE in Debian 9.1 and for some unknown reason, the only app that works correctly is LibreOffice. I've tried GTK2 apps (Thunar, GIMP, Inkscape, Audacious...) and GTK3 (atril) and the only thing I get is the application name, not the menus:

![libreoffice](https://user-images.githubusercontent.com/31181378/29494579-91004bfc-85ad-11e7-957f-e4badc23aa93.png)

![thunar](https://user-images.githubusercontent.com/31181378/29494580-9102ea42-85ad-11e7-87c6-07ddc32168e4.png)

This is how I executed _cmake_:
`cmake -DENABLE_XFCE=ON -DENABLE_JAYATANA=ON -DENABLE_UNITY_GTK=ON -DMAKE_BOLD_APPNAME=ON -DCMAKE_INSTALL_PREFIX=/usr ..`

Then ran _make_ and _make install_ (as root), without any apparent issues. You can see the output for the three commands here:
[cmake_appmenu.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1237044/cmake_appmenu.txt)
[make_appmenu.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1237043/make_appmenu.txt)
[make_install_appmenu.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1237045/make_install_appmenu.txt)

Any idea of what might be happening?

Thanks a lot!

**Comment by alvarezprado** [comment]
Update: QT apps also work. Tested keepassx and VLC. Is it possible that I'm missing some configuration for GTK apps?

**Comment by rilian-la-te** [comment]
-DENABLE_UNITY_GTK_MODULE=ON

You does not built appmenu-gtk-module

**Comment by alvarezprado** [comment]
Do you mean that this flag does not build appmenu-gtk-module and I need to build it? I understood ON built the module and that was required for non-Arch, non-Ubuntu distros.

Thanks for your quick reply!

**Comment by rilian-la-te** [comment]
this flag is build. but you was not build it, because you misspelled a flag AFAIK

**Comment by alvarezprado** [comment]
Ups, sorry for the lapse! I'll rebuild it when I get back home and close the thread if it works.

Many thanks ;)

**Comment by alvarezprado** [comment]
I recompiled with the appropriate flags and still facing the same issue...

`cmake -DENABLE_XFCE=ON -DENABLE_JAYATANA=ON -DENABLE_UNITY_GTK_MODULE=ON -DMAKE_BOLD_APPNAME=ON -DCMAKE_INSTALL_PREFIX=/usr ..`

[cmake_appmenu.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1237380/cmake_appmenu.txt)
[make_appmenu.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1237381/make_appmenu.txt)
[make_install_appmenu.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1237382/make_install_appmenu.txt)

**Comment by rilian-la-te** [comment]
```
if [ -n "$GTK_MODULES" ]; then
    GTK_MODULES="${GTK_MODULES}:appmenu-gtk-module"
else
    GTK_MODULES="appmenu-gtk-module"
fi

if [ -z "$UBUNTU_MENUPROXY" ]; then
    UBUNTU_MENUPROXY=1
fi

export GTK_MODULES
export UBUNTU_MENUPROXY
```

add this to /etc/profile.d

**Comment by alvarezprado** [comment]
I had already added that to _,bashrc_ and _.profile_ following the instructions in the README. I also added it to _/etc/profile.d/appmenu.sh_ (which shouldn't make a difference to having it added in .profile) and the problem persists.

**Comment by rilian-la-te** [comment]
show me GTK_MODULES var and console log from running GTK app, please.

**Comment by alvarezprado** [comment]
`echo $GTK_MODULES 
appmenu-gtk-module`

`G_MESSAGES_DEBUG=all xfce4-panel`

> ** (wrapper-1.0:2212): WARNING **: No outputs have backlight property
> ** (wrapper-1.0:2212): DEBUG: executed /usr/sbin/xfpm-power-backlight-helper --get-max-brightness; retval: 0
> ** (wrapper-1.0:2212): DEBUG: xfpm_brightness_setup_helper: get-max-brightness returned 937
> ** (wrapper-1.0:2212): DEBUG: xrandr not available, brightness controlled by sysfs helper; min_level=0 max_level=937
> (xfce4-panel:2204): GdkPixbuf-DEBUG: gdk_pixbuf_from_pixdata() called on:
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Encoding raw
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Dimensions: 16 x 16
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Rowstride: 64, Length: 1048
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Copy pixels == false
> (xfce4-panel:2204): GdkPixbuf-DEBUG: gdk_pixbuf_from_pixdata() called on:
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Encoding raw
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Dimensions: 16 x 16
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Rowstride: 64, Length: 1048
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Copy pixels == false
> (wrapper-2.0:2218): pulseaudio-plugin-DEBUG: [pulseaudio-plugin.c:133 pulseaudio_plugin_init]: Pulseaudio Panel Plugin initialized
> (wrapper-2.0:2218): pulseaudio-plugin-DEBUG: [pulseaudio-plugin.c:270 pulseaudio_plugin_bind_keys]: Grabbing volume control keys
> (xfce4-panel:2204): GdkPixbuf-DEBUG: gdk_pixbuf_from_pixdata() called on:
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Encoding raw
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Dimensions: 16 x 16
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Rowstride: 64, Length: 1048
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Copy pixels == false
> (xfce4-panel:2204): GdkPixbuf-DEBUG: gdk_pixbuf_from_pixdata() called on:
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Encoding raw
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Dimensions: 16 x 16
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Rowstride: 64, Length: 1048
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Copy pixels == false
> (wrapper-2.0:2218): pulseaudio-plugin-DEBUG: [pulseaudio-volume.c:266 pulseaudio_volume_context_state_cb]: Connecting to PulseAudio server
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 56625099
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> 
> (wrapper-2.0:2211): Gtk-WARNING **: Theme parsing error: <data>:1:49: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (wrapper-2.0:2211): Gtk-WARNING **: Theme parsing error: <data>:1:80: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (wrapper-2.0:2211): Gtk-WARNING **: Theme parsing error: <data>:1:109: The style property GtkButton:default-border is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (wrapper-2.0:2211): Gtk-WARNING **: Theme parsing error: <data>:1:136: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (wrapper-2.0:2211): Gtk-WARNING **: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkToggleButton)
> 
> (wrapper-2.0:2218): Gtk-WARNING **: Theme parsing error: <data>:1:47: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (wrapper-2.0:2218): Gtk-WARNING **: Theme parsing error: <data>:1:79: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (wrapper-2.0:2218): Gtk-WARNING **: Theme parsing error: <data>:1:109: The style property GtkButton:default-border is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (wrapper-2.0:2218): Gtk-WARNING **: Theme parsing error: <data>:1:137: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version
> (wrapper-2.0:2218): pulseaudio-plugin-DEBUG: [pulseaudio-volume.c:274 pulseaudio_volume_context_state_cb]: Authorizing
> 
> (wrapper-2.0:2218): Gtk-WARNING **: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner PulseaudioButton)
> (wrapper-2.0:2218): pulseaudio-plugin-DEBUG: [pulseaudio-volume.c:270 pulseaudio_volume_context_state_cb]: Setting application name
> (wrapper-2.0:2218): pulseaudio-plugin-DEBUG: [pulseaudio-volume.c:245 pulseaudio_volume_context_state_cb]: PulseAudio connection established
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 56625099
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> (wrapper-2.0:2218): pulseaudio-plugin-DEBUG: [pulseaudio-volume.c:182 pulseaudio_volume_server_info_cb]: server: angel@pulseaudio, v.10.0
> (wrapper-2.0:2218): pulseaudio-plugin-DEBUG: [pulseaudio-volume.c:151 pulseaudio_volume_sink_info_cb]: sink info: alsa_output.pci-0000_00_1f.3.analog-stereo, Audio Interno Estéreo Analógico
> (wrapper-2.0:2218): pulseaudio-plugin-DEBUG: [pulseaudio-volume.c:165 pulseaudio_volume_sink_info_cb]: Updated Volume: 0,000 -> 0,520
> (wrapper-2.0:2218): pulseaudio-plugin-DEBUG: [pulseaudio-volume.c:169 pulseaudio_volume_sink_info_cb]: volume: 0,519974, muted: 0
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 23068675
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 23068675
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 12583967
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 12583967
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 12583967
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 12583967
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 56625099
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 56625099
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 23068675
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 23068675
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 20971702
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 20971702
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 20971702
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 20971702
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> (xfce4-panel:2204): GdkPixbuf-DEBUG: gdk_pixbuf_from_pixdata() called on:
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Encoding raw
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Dimensions: 16 x 16
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Rowstride: 64, Length: 1048
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Copy pixels == false
> (xfce4-panel:2204): GdkPixbuf-DEBUG: gdk_pixbuf_from_pixdata() called on:
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Encoding raw
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Dimensions: 16 x 16
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Rowstride: 64, Length: 1048
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Copy pixels == false
> 
> (wrapper-2.0:2228): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer
> 
> (wrapper-2.0:2228): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (wrapper-2.0:2208): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer
> 
> (wrapper-2.0:2208): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 23068675
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 23068675
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> (xfce4-panel:2204): GdkPixbuf-DEBUG: gdk_pixbuf_from_pixdata() called on:
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Encoding raw
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Dimensions: 16 x 16
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Rowstride: 64, Length: 1048
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Copy pixels == false
> (xfce4-panel:2204): GdkPixbuf-DEBUG: gdk_pixbuf_from_pixdata() called on:
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Encoding raw
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Dimensions: 16 x 16
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Rowstride: 64, Length: 1048
> (xfce4-panel:2204): GdkPixbuf-DEBUG: 	Copy pixels == false
> GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
> GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 23068675
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 23068675
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 12583967
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 12583967
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 12583967
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 12583967
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 56623107
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 56623107
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 56625099
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2208): DEBUG: menubar.vala:177: Looking for parent window on XID 56625099
> ** (wrapper-2.0:2208): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 56625099
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»
> 
> ** (wrapper-2.0:2228): DEBUG: menubar.vala:177: Looking for parent window on XID 56625099
> ** (wrapper-2.0:2228): DEBUG: appmenu-bamf.vala:71: El archivo de claves no tiene la clave «X-Ayatana-Desktop-Shortcuts» en el grupo «Desktop Entry»

**Comment by rilian-la-te** [comment]
Please, use GTK application with a menu for log.

**Comment by alvarezprado** [comment]
I have tried:
`G_MESSAGES_DEBUG=all thunar`
`G_MESSAGES_DEBUG=all xfce4-terminal`

And they do not generate a log, but still don't show the menus in the bar...

However, I've noticed that if I run:
`G_MESSAGES_DEBUG=all mousepad`
`G_MESSAGES_DEBUG=all geany`

They show the menus, but they don't appear if I use _xfce4-appfinder_ to launch them (?)

**Comment by rilian-la-te** [comment]
Do you tried to relogin after modifications?

**Comment by alvarezprado** [comment]
Yes.

**Comment by rilian-la-te** [comment]
look to your environment variables, please. And reboot.

**Comment by alvarezprado** [comment]
Rebooted.
`printenv`

(I removed sensitive info)

> 
> XDG_MENU_PREFIX=xfce-
> LANG=es_ES.utf8
> DISPLAY=:0.0
> COLORTERM=truecolor
> XDG_VTNR=7
> GLADE_CATALOG_PATH=:
> XDG_SESSION_ID=2
> XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/angel
> USER=angel
> GLADE_MODULE_PATH=:
> DESKTOP_SESSION=lightdm-xsession
> QT_ACCESSIBILITY=1
> XDG_SESSION_TYPE=x11
> XDG_DATA_DIRS=/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share
> XDG_SESSION_DESKTOP=lightdm-xsession
> GLADE_PIXMAP_PATH=:
> GTK_MODULES=appmenu-gtk-module
> UBUNTU_MENUPROXY=1
> TERM=xterm-256color
> SHELL=/bin/bash
> VTE_VERSION=4601
> XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
> XDG_CURRENT_DESKTOP=XFCE
> QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
> SHLVL=1
> XDG_SEAT=seat0
> WINDOWID=60817411
> GDMSESSION=lightdm-xsession
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> XDG_RUNTIME_DIR=/run/user/1000
> XAUTHORITY=/home/angel/.Xauthority
> XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
> XDG_CONFIG_DIRS=/etc/xdg
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
> SESSION_MANAGER=local/gram:@/tmp/.ICE-unix/1023,unix/gram:/tmp/.ICE-unix/1023
> _=/usr/bin/printenv

**Comment by rilian-la-te** [comment]
same as before?

**Comment by alvarezprado** [comment]
Yes, exactly the same.

**Comment by alvarezprado** [comment]
Yes, except for thunar and xfce4-terminal that don't work neither from launcher nor from terminal.

**Comment by rilian-la-te** [comment]
look to /etc/environment. Try to set variables there

**Comment by alvarezprado** [comment]
Did it, rebooted, issue remains.
