### ISSUE TITLE
A way to disable "Desktop" and "Files" when no window is selected?

### ISSUE THREAD

**Issue by AryToNeX** [rilian-la-te/vala-panel-appmenu#129]
The title is self-explanatory. Using Xfce4 I can't use shortcuts in "Desktop" menu and I think "Files" menu is redundant in my desktop setup. Any quick way to disable or hide them?

**Comment by rilian-la-te** [comment]
Why Desktop is not working? And why do ypu want to disable this menu? It is purely cosmetic:)

**Comment by AryToNeX** [comment]
Desktop Settings and System Settings do nothing and then apport appears on the screen.. btw I want to disable them exactly because they are purely cosmetic. I want only useful things.

**Comment by mrnhmath** [comment]
+1

**Comment by rilian-la-te** [comment]
Can you run plugin in console to debug crashes?

**Comment by AryToNeX** [comment]
Nope I can't. I just wanted to know how can I disable them. I don't want to use them even if they work correctly.

**Comment by rilian-la-te** [comment]
Can you suggest another variant of desktop menu?

**Comment by AryToNeX** [comment]
Hmm, "Places" menu like in Gnome2? I also suggest you a cmake flag to disable desktop menu.

**Comment by rilian-la-te** [comment]
Maybe, instead or with current menu. Why do you want a empty panel instead?

**Comment by AryToNeX** [comment]
I want it empty because I think it looks better, especially in my minimal desktop configuration.

**Comment by rilian-la-te** [comment]
It will not be empty, because we need to mimic MacOS somehow.

**Comment by AryToNeX** [comment]
I didn't ask you to make it empty, I asked you a method to make it empty just for me tbh

**Comment by rilian-la-te** [comment]
For dirty hack remove lines 45-71 from lib/appmenu-dektop.vala

**Comment by Gambulec** [comment]
Maybe this? <3
<img src=http://linoob.com/wp-content/flagallery/gnome2-global-menu/06-global-menu-in-gnome.png>

**Comment by rilian-la-te** [comment]
Good variant, but Nautilus and Caja does not contain a menu in desktop windows.

**Comment by Gambulec** [comment]
You mean this? :/
https://www.youtube.com/watch?v=kpjT0rqShhs
Is there any way to change the menu language?

**Comment by rilian-la-te** [comment]
vala-panel-appmenu works not only on XFCE))
On Budgie Nautilus is native.

Commit translation to the repo, and language will be change. Not magic, just gettext. Russian is already there.

**Comment by Gambulec** [comment]
Done :+1:

**Comment by rilian-la-te** [comment]
Make a PR then:)

**Comment by mrnhmath** [comment]
It could be a customizable label, like default Unity says "Ubuntu Desktop"

**Comment by rilian-la-te** [comment]
Now I make it Places like) If you do not like this solution, write here. Bug is closing now.
