### ISSUE TITLE
Desktop menu does not use name of the link

### ISSUE THREAD

**Issue by Malezha** [rilian-la-te/vala-panel-appmenu#13]
![files](https://cloud.githubusercontent.com/assets/3649525/15632182/9023e95e-2592-11e6-9938-69349a772f4e.png)
On desktop links named `Steam` and `PhpStorm`.

**Comment by rilian-la-te** [comment]
It is by design now (takes filename, not drives inside desktop entry). И на
русском: развитие проекта ожидайте, когда я вернусь со срочки. (На
контракте проще будет).

**Comment by rilian-la-te** [comment]
Closing this because now Desktop menu does not show Desktop files.
