### ISSUE TITLE
vala-panel-appmenu can't be packaged for Debian

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#130]
The embedded fork of `unity-gtk-module` isn't permitted according to Debian Policy 4.13.

  * https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles

In order to package `vala-panel-appmenu` for Debian the `appmenu-gtk-module` fork will need decoupling from the `vala-panel-appmenu` source. `appmenu-gtk-module` will then need packaging independently and `vala-panel-appmenu` would need to includ something like `Depends: unity-gtk-module | appmenu-gtk-module`.

**Comment by rilian-la-te** [comment]
Answerring:
1. Unforked unity-gtk-module will not work in Debian at all (requires patched GTK)
2. If package is included in build system, it is a part of distro or not?
3. If I made appmenu-gtk-module buildable without core system, can it be downloaded separately from Github (I will not use versioning for it)?

**Comment by rilian-la-te** [comment]
1. I have added a standalone build and generation mode for unity-gtk-module. You can generate source yourself by using ```make dist```
2. You can cherry-pick all commits from appmenu-gtk-module and add it to unity-gtk-module package as patch

**Comment by rilian-la-te** [comment]
What do you think about my variants?

Or you explicitly want to split repositories (or debian policy absolutely requires splitting, not 2 releases from one repo)?

**Comment by flexiondotorg** [comment]
Leave things as they are for now. I spoke with some Debian Developers about this and there might be a way forward. I'll be in touch when we've had the chance to package everything.

**Comment by sunweaver** [comment]
Hi! A DD speaking...

I'd personally love to see the following happen about appmenu-gtk-module.

  - provide a separate repo (or tarball) with only the appmenu-gtk-module
  - make sure it can be co-installed on Ubuntu even with unity-gtk-module installed, too
  - consider the usefulness of UBUNTU_MENUPROXY as a variable name (e.g. introduce APPMENU_PROXY or such and handle UBUNTU_MENUPROXY gracefully for a long time, too)

Once we have the appmenu-gtk-module as a separate source project, I can start bringing your vala-panel stack to Debian. Thanks!!!

**Comment by rilian-la-te** [comment]
1. I can generate a separate tarball, but not a separate repo (I made one build system and some code sharing for 2 projects)
2. It can be co-installed, but cannot co-function.
3. UBUNTU_MENUPROXY is libdbusmenu variable, I have nothing to do with it AFAIK.

With next release I will provide a separate tarball for appmenu-gtk-module.

**Comment by rilian-la-te** [comment]
You can now take appmenu-gtk-module tarball from Releases page (along with full tarball).
I will provide it starting from now.

**Comment by sunweaver** [comment]
Hi Konstantin,

On Friday, December 1, 2017, Konstantin wrote:
> You can now take appmenu-gtk-module tarball from Releases page (along with full tarball).
> I will provide it starting from now. 

Thanks a lot. What is the URL of the release page?

Greets,
Mike

-- 
Sent from my Fairphone 2 (running Sailfish OS)

**Comment by rilian-la-te** [comment]
[For 0.5.5](https://github.com/rilian-la-te/vala-panel-appmenu/releases/tag/0.5.5)

If you do not like a tarball, write here.

**Comment by sunweaver** [comment]
Packaging of this has started. I think this issue has been settled now. Please close this bug. Thanks.
