### ISSUE TITLE
Build failure?

### ISSUE THREAD

**Issue by SolarAquarion** [rilian-la-te/vala-panel-appmenu#131]
[ 35%] Generating dbusmenu.c;dbusmenu-proxy.c;dbusmenu-gtk.c;vala-dbusmenu.vapi;vala-dbusmenu.h
/home/solaraquarion/build/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/dbusmenu/dbusmenu.vala:193.13-193.58: error: 1 extra arguments for `void GLib.VariantDict.insert (string key, string fornat_string)'
            props.insert("children-display","s","submenu");
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)

**Comment by rilian-la-te** [comment]
GLib VAPI is too old AFAIK

**Comment by SolarAquarion** [comment]
I closed that because I had the old vala on my system
