### ISSUE TITLE
vala appmenu doesn't get installed to xfce4 panel plugins

### ISSUE THREAD

**Issue by Simbaclaws** [rilian-la-te/vala-panel-appmenu#132]
Dear rilian-la-te,

I've installed the vala-panel-appmenu by using cmake, make and make install using these flags from within the build directory (I had to set cflags to point to libwnck-3-0 because else it would fail in the make process):

env CFLAGS="-I/usr/include/libwnck-3.0/" cmake ../ -DENABLE_XFCE=ON -DENABLE_UNITY_GTK_MODULE=ON

When I build and make this plugin it doesn't show up in: /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/
I do seem to have it installed in: /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/
and in: /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/
It's almost as if it skipped the XFCE installation...
nor does the desktop file get created in /usr/share/applications/

Any idea what could be going on?
I can't find the plugin in my xfce4 panel aswell...

I'm on a debian based distro btw.

EDIT:
the cmakelists.txt shows ENABLE_XFCE instead of DENABLE_XFCE, is it true that this is wrong inside the documentation? Or is the above cmake command correct? My CMakeCache.txt did show ENABLE_XFCE:INTERNAL=ON in the file so it does seem like it ran correctly...

**Comment by Simbaclaws** [comment]
Found my issue it really has to do with libwnck...
I have version 3.24.0 installed and needed version is 3.4.0 at least but for some reason it still executes even though the version is lower. I'm missing a lot of xfce4 modules in libwnck... I'm gonna try and find a way to upgrade it.

**Comment by rilian-la-te** [comment]
Please, get package build and close bug:)

**Comment by emielmolenaar** [comment]
I think I am suffering the same issue. But I can not figure out what the problem is. @Simbaclaws , did you?

**Comment by rilian-la-te** [comment]
Symptoms, distro, and cmake log, please.

**Comment by Simbaclaws** [comment]
@emielmolenaar 
I just checked the cmake logs in order to find packages that weren't installed, I searched for them using sudo apt-cache search and then installed them with sudo apt-get install, after installing the corresponding packages I also made sure I changed the prefix installation folder to /usr so that it could be recognized by my xfce installation. Now it works perfectly fine :+1:

**Comment by emielmolenaar** [comment]
> I also made sure I changed the prefix installation folder to /usr so that it could be recognized by my xfce installation.

This should be it :smiley: Thanks!

**Comment by rilian-la-te** [comment]
Then I will Close
close it:-)
