### ISSUE TITLE
Menu seems slow and or unreponsive with multiple instances.

### ISSUE THREAD

**Issue by snippins** [rilian-la-te/vala-panel-appmenu#134]
I am using a 2 monitor setup, thus I need two panel and two plugin instances.

~~For electron and qt apps, the menu seem slow to response and hang sometimes.~~

~~This could be some race condition between the Registrar instances.~~

~~Potentially related to https://github.com/rilian-la-te/vala-panel-appmenu/issues/89.~~

Edit:
Turn out only Meshlab is affected. I should not have test with all the apps opened. My bad :(.

Everything is working until I use the menu of Meshlab.

**Comment by rilian-la-te** [comment]
Menu should open only one registrar. I will look for it:)

**Comment by rilian-la-te** [comment]
Can you post a logs from both applets? And can you describe a lags detally? Only one applet lags, or both?

**Comment by snippins** [comment]
Both, I will post the logs next weekend :)

**Comment by snippins** [comment]
I will close this since I now use a different Meshlab build and can not reproduce the problem ...
