### ISSUE TITLE
Global Applications Menu won't work on MATE 1.18.0@Fedora 25

### ISSUE THREAD

**Issue by prppedro** [rilian-la-te/vala-panel-appmenu#140]
Hi, 

Well, I followed the word of the Readme down to the letter. Installed required libs, updated config files and, well. It kinda works, except it doesn't. The module was compiled with success (the prefix being /usr). MATE, then reads it's folders and says: "Cool! New applet!": 
![applet1](https://user-images.githubusercontent.com/9347060/31387322-64120e30-ada0-11e7-83f1-ea6c60fd3cd4.png)
Okay, no problem, let's drag it into a panel: 
![applet2](https://user-images.githubusercontent.com/9347060/31387358-8687f25e-ada0-11e7-94ab-2b8acc12c00a.png)
"Oh, no, it's empty... Let's load an MATE application to see if it lives"
Then I see there's no internal menu anymore... Okay, so far, so good. 
![applet3](https://user-images.githubusercontent.com/9347060/31387436-d0d5200c-ada0-11e7-8663-16cddf509035.png)
But, then, the applet stays dead: 
![applet2](https://user-images.githubusercontent.com/9347060/31387482-fc336a88-ada0-11e7-8d80-9177161a9387.png)

Also, it killed the "Custom menu" applet, which shows "Apps, Places, Settings etc."... 

I don't know much on how to debug it. MATE API is a complete mistery to me.

**Comment by rilian-la-te** [comment]
bamfdaemon is installed?

**Comment by rilian-la-te** [comment]
See https://github.com/rilian-la-te/vala-panel-appmenu/commit/c5bed3e06e14df635df57bcf48c0b038688d247f (new README)

**Comment by rilian-la-te** [comment]
About custom menu - add this binary and mate-panel binary to unity-gtk-module ignore list (or appmenu-gtk-module ignore list)

**Comment by prppedro** [comment]
Hey, quick answer. Thanks! 

Well, it wasn't. Now it is. And seems like it works, now.

**Comment by rilian-la-te** [comment]
So, close the bug then))))

**Comment by prppedro** [comment]
Well, I'm testing it... There's a small caveat, it seems. The "Window Selector" applet seems not to work. And I was planning on using it. ;(

**Comment by rilian-la-te** [comment]
Add it to blacklist in gtk module))). Please, post blacklist list here, I will add to defaults:))))

**Comment by prppedro** [comment]
Wait... What should I add to the blacklist? The Global Menu or the Window Selector?

**Comment by rilian-la-te** [comment]
Window selector:))) Blacklisted windows will not give menu to applet.

**Comment by prppedro** [comment]
Well, turns out that it wasn't even needed. Menu Bar and Window List are back to the work. It was a MATE bug, most likely.
