### ISSUE TITLE
Show menus from windows applet not working for Evolution

### ISSUE THREAD

**Issue by sliddjur** [rilian-la-te/vala-panel-appmenu#144]
Originally created an issue at Budgie desktop github, but they redirected me here.

```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"

budgie-desktop --version
budgie-desktop 10.4

evolution --version
evolution 3.26.1-1 

Widget theme: Flat-Plat-compact
Built-in theme: unchecked
```

**The issue encountered**

The global menu "show menus from windows" applet doesnt work for evolution. It did work before a reboot, now the top panel global menus are gone. (see screenshot below). I also disabled the menus through the app in the view menu. 

However, if I open the "compose message" window, the menus appear _both_ in the app, and also in the top panel global menu.

**Steps to reproduce the issue**

Install show menus from windows applet and open Evolution.

_Main window in evolution. Neither in app menu or top menu menus appears._
![evolution](https://user-images.githubusercontent.com/10002057/32163918-2edfd42c-bd5e-11e7-9bee-e7a9d2ce537c.png)

_Compose Message in Evolution. Top panel global menu works partitially. It still shows in app menu._
![screenshot from 2017-10-30 10-37-20](https://user-images.githubusercontent.com/10002057/32163966-57d4f06a-bd5e-11e7-8452-c3ac34b0866c.png)

**Comment by rilian-la-te** [comment]
1. Enable menus in app view.
2. Show me a screen.
Do you have gtk_shell_shows_menubar set anywhere?

**Comment by rilian-la-te** [comment]
If not, you should set it by methods relevant for Budgie.

**Comment by rilian-la-te** [comment]
For me all is working, but I am on MATE with vala-panel.

**Comment by fossfreedom** [comment]
@rilian-la-te budgie uses "budgie-daemon" - it is part of budgie-desktop and is unmodified.

What do you mean by "appmenu relevant properties"?  We cannot add specific coding to budgie-daemon without pushing a PR upstream (budgie-desktop)

**Comment by rilian-la-te** [comment]
can budgie-daemon set custom xsettings?

**Comment by rilian-la-te** [comment]
What dconf path it uses?

**Comment by rilian-la-te** [comment]
budgie-daemon is modified, AFAIK, because earlier budgie was using gnome-settings-daemon.

**Comment by rilian-la-te** [comment]
appmenu relevant properties is specific GTK settings
```
gtk-shell-shows-appmenu
gtk-shell-shows-menubar
```
it can be set via xsettings or via settings.ini. Xsettings is preferred, but I do not know which method is relevant for budgie.

**Comment by fossfreedom** [comment]
for budgie xsettings is set in dconf as

{'Gtk/ShellShowsAppMenu': <0>, 'Gtk/DecorationLayout': <'menu:minimize,maximize,close'>}

**Comment by rilian-la-te** [comment]
for appmenu this should be:
Gtk/ShellShowsAppMenu': <1>,
Gtk/ShellShowsMenubar': <1>,

**Comment by rilian-la-te** [comment]
So, you block appmenu and cause this issue.

**Comment by fossfreedom** [comment]
hmm - so somehow if the user enables the appmenu applet those values need to be set for the session.

Likewise, if the applet is not added to the panel then those values need to be removed.

Any ideas how this can be done from within the applet?

**Comment by rilian-la-te** [comment]
From applet - I do not like this idea, because it is DE-specific (applet is DE-agnostic).
You can set it for applet's DEB package as override.

But, better, you can write it in my README here, because I do not know than you break appmenu.

**Comment by rilian-la-te** [comment]
Like instructions for XFCE.

**Comment by fossfreedom** [comment]
hmm - ok thanks. 

the budgie-appmenu applet is obviously for budgie.  So if we can somehow add code for that then all distro's that use the applet can benefit.  

DEB package override is specific to Debian/Ubuntu (and derivatives) so will not really benefit the wider linux community.

Sure README is useful - but you know like me - people rarely seek out README's let alone actually read them ;)

**Comment by rilian-la-te** [comment]
Yes, you can, I will approve (and I may add it myself, if I will do settings).
For budgie I have only one Vala file in whole applet code.
And users of any DE should seek Readme and run post-build instructions. Period.

**Comment by sliddjur** [comment]
I did change to {'Gtk/ShellShowsAppMenu': <1>, 'Gtk/ShellShowsMenuBar': <1>, 'Gtk/DecorationLayout': <'menu:minimize,maximize,close'>} in dconf editor. Logged out and in again. No help

**Comment by rilian-la-te** [comment]
You enable appmenu in evolution itself?

**Comment by sliddjur** [comment]
@rilian-la-te if I enable appmenu in evolution, they will always appear.

However, I found a workaround. If I press and hold ALT for a second while in the Evolution app, both panelappmenu and app menu will appear. If I release ALT the panelappmenu will keep showing, while the app menu is gone. I dont know if this is a budgie or vala-panel "feature" @fossfreedom ?

If I open a compose new email window in Evolution, the menu will appear at both places, as shown in screenshot above. There is no option to hide menu within the evolution app on the compose message thing, afaik.

**Comment by rilian-la-te** [comment]
Even after enabling options? Strange.

Evolution is working for me, so, applet is correct.

**Comment by rilian-la-te** [comment]
In Budgie it also working
