### ISSUE TITLE
Appmenu crash on  "empty body " error

### ISSUE THREAD

**Issue by PsykeDady** [rilian-la-te/vala-panel-appmenu#145]
i use appmenu applet on dde on arch, i've tried both on vala-panel and mate-panel, but when  i click on my desktop, the applet crash with this error:

```

(vala-panel:2611): GLib-GObject-WARNING **: ../glib/gobject/gsignal.c:2641: instance '0x564c715b6aa0' has no handler with id '19207'
GDBus.Error:org.freedesktop.DBus.Error.Failed: Errore di ritorno con corpo vuoto: 
Errore di segmentazione (core dump creato)

```

"_Errore di ritorno con corpo vuoto_" means "_**Return error with empty body**_"
![screen](https://user-images.githubusercontent.com/27916449/32698197-65b36674-c7a1-11e7-97c8-a66ee635c995.png)

**Comment by rilian-la-te** [comment]
Cannot reproduce it. How could you?

**Comment by PsykeDady** [comment]
install archlinux
install dde
install vala-panel (or mate-menu)
install vala appmenu 
i also installed qmenu_hud, it's important? 
start vala-panel, add appmenu applet on panel
write a vala-panel.desktop into $HOME/.config/autostart dir
reboot
click on desktop: crash

**Comment by rilian-la-te** [comment]
Will look for it. Do you have some desktop drawing tool ? What is DDE?

**Comment by PsykeDady** [comment]
desktop drawing tool? gimp? 
DDE is a Deepin Desktop Environment: https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment

**Comment by rilian-la-te** [comment]
No, something like Nautilus or PcManFm.

**Comment by PsykeDady** [comment]
aaah yes, dde-file-manager has the control of desktop drawing

**Comment by rilian-la-te** [comment]
If you click on file manager window, applet crashes?

**Comment by PsykeDady** [comment]
yes
now I understand the reason, if i start at startup system both vala global menu applet and qmenu_hud, global menu crash on deepin software. if i start first vala global menu and after i start qmenu_hud, it's ok... qmenu_hud is incompatible with vala global menu applet?

**Comment by rilian-la-te** [comment]
Do not know, sorry, it is untested. But you can start hud after vala-panel-appmenu and does not encounter the bug.

**Comment by PsykeDady** [comment]
yes sure! i will do! 

Thanks for help :)
