### ISSUE TITLE
Missing LICENSE in appmenu-gtk-module tarball

### ISSUE THREAD

**Issue by alunux** [rilian-la-te/vala-panel-appmenu#147]
Due to the new release v0.5.5, I can't find LICENSE file in appmenu-gtk-module tarball.

**Comment by rilian-la-te** [comment]
You does not need a appmenu-gtk-module tarball, if use full vala-panel-appmenu to build.
If it will be wanted by Debian community, I will add such file. For now, waiting for it.

**Comment by alunux** [comment]
Aha, I think it was be splited. So, appmenu-gtk-modul is included in vala-panel-appmenu tarball, right?

**Comment by rilian-la-te** [comment]
Yes)))

**Comment by alunux** [comment]
Thank you! I will close this issue.
