### ISSUE TITLE
appmenu-gtk-module: Include file naming scheme

### ISSUE THREAD

**Issue by sunweaver** [rilian-la-te/vala-panel-appmenu#150]
Two particularities came up when packaging appmenu-gtk-module:

  1. unity-gtk-module uses /usr/include/unity-gtk-parser/ as folder name, you have /usr/include/appmenu-gkt-module (parser vs. module). You may want to adapt that?
  2. the include files (and many of the source files in general) are named unity-*.h (or unity-*.c). Do you plan to rename those?
  3. Also in the CMakeLists.txt file, you have several occurrences of "unity" where you might want to have "appmenu".

Please check and give feedback esp. about the include file names and paths. I will hold back the Debian upload until I have feedback on this.

**Comment by rilian-la-te** [comment]
1. Fixed.
2. I may rename include files, but I want to have API compatibility with unity-gtk-module. I want it is a drop-in replacement. If renaming includes is required, I will do it.
3. It is ok, I do not want to do a full rename, because this is functional fork, not ideological.
But I renamed cmake option, thanks.

**Comment by rilian-la-te** [comment]
Corrected release will be after we agrees about includes and mentioning of me in sources)))

**Comment by sunweaver** [comment]
1. THANKS
  2. API compat is good. As you have renamed the include dir already, people have to adapt include statements already anyway, so renaming the include files themselves might make sense to have the code really forked. People get confused when they see old stuff in new stuff... Renaming files is not required, but cleaner IMHO.
3. Ok.

**Comment by rilian-la-te** [comment]
Headers now renames itself when installed. So,closing this.

**Comment by sunweaver** [comment]
> Headers now renames itself when installed. So,closing this.

Wait. Simply renaming won't work. The headers include one another (with unity-foo.h as name.

**Comment by rilian-la-te** [comment]
Will look for it now)

**Comment by rilian-la-te** [comment]
Only for parser, will rename it.

**Comment by sunweaver** [comment]
@rilian-la-te: I haven't done a test build, yet, but just from looking at the code, renaming only the one public header is insufficient.

unity-gtk-group-actions.h includes unity-gtk-menu-shell.h and vice versa (depends on what of the headers gets included first).

Whereas your change might work at build time, the result after installation is wrong. In unity-gtk-group-actions.h and unity-gtk-menu-shell.h you try to include the respectively other file. But none of these exist after installation (because they got renamed to appmenu-gtk-<foo>.h).

I'd strongly suggest renaming all three public headers files in the source tree itself.

**Comment by sunweaver** [comment]
@rilian-la-te: and once we have that, I'd suggest another tarball release and we get the thing uploaded to Debian. As long as you maintain it, I prefer having your version (which has a far more responsive upstream maintainer) in Debian. Also it will ease getting vala-panel-appmenu into Debian, too.

**Comment by rilian-la-te** [comment]
AFAIK, another headers include only gtk.h. If it include other unity- part, I will forced to rename it:-(

**Comment by sunweaver** [comment]
Hi,

On Saturday, December 9, 2017, Konstantin wrote:
> AFAIK, another headers include only gtk.h. If it include other unity- part, I will forced to rename it:-( 

Please look further down in the files, about half way through. There are the includes I have been referring to.

Thanks,
Mike

-- 
Sent from my Fairphone 2 (running Sailfish OS)

**Comment by rilian-la-te** [comment]
Look to 0.5.6, please. And if you package appmenu, please package another 3 projects : vala-panel itself, xfce4-sntray-plugin and vala-panel-extras.

**Comment by sunweaver** [comment]
Hi,

On  Sa 09 Dez 2017 18:27:42 CET, Konstantin wrote:

> Look to 0.5.6, please. And if you package appmenu, please package  
> another 3 projects : vala-panel itself, xfce4-sntray-plugin and  
> vala-panel-extras.

appmenu-gtk-module has been uploaded.

I will look at vala-panel next.

For vala-panel-appmenu, I'd like to see  
https://github.com/rilian-la-te/vala-panel-appmenu/issues/123  
implemented first.

The vala-panel-extras I have now added to my list.

The xfce4-sntray-plugin will probably be handled by a guy I work with  
on Ayatana Indicators who is doing packaging of XFCE4 in Debian and  
Ubuntu.

Thanks!!!
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by rilian-la-te** [comment]
123 is a big work, I will implement it eventually, but I think package can work without it now. And appmenu-gtk-module without widget is useless.
