### ISSUE TITLE
appmenu-gtk-module: Add your own copyright attributions

### ISSUE THREAD

**Issue by sunweaver** [rilian-la-te/vala-panel-appmenu#151]
You may want to consider attributing your changes on the files of appmenu-gtk-module with your own copyright holdership. If so, please add yourself as copyright holder to files that you modified.

Thanks for making appmenu-gtk-module work without patched GTK+ 3, btw.

Greets,
Mike

**Comment by rilian-la-te** [comment]
Without patched GTK2, to be correct, Patching GTK3 is not necessary for original.
No, It is not my files:)) I wrote only small patches to fix some issues and reliability on GTK patches)

**Comment by sunweaver** [comment]
Ok, so you leave things as they are. Fine by me.
