### ISSUE TITLE
Rename folder: unity-gtk-module -> appmenu-gtk-module

### ISSUE THREAD

**Issue by sunweaver** [rilian-la-te/vala-panel-appmenu#152]
Another code cleanup suggestion: ```mv unity-gtk-module appmenu-gtk-module``` (and obviously some patching in CMakeLists.txt files)...

**Comment by sunweaver** [comment]
Reasoning: this is the upstream URL appearing in the Debian package:
https://github.com/rilian-la-te/vala-panel-appmenu/tree/master/unity-gtk-module

It would be far nicer, if it had appmenu-gtk-module as last folder name in the path.

**Comment by rilian-la-te** [comment]
I do not like this moving, because this will breaks internal meanings of my code. But I will think about it. Why are you use folder as upstream URL? Not repo's path?

**Comment by sunweaver** [comment]
Hi Konstantin,

On  Mo 04 Dez 2017 14:17:07 CET, Konstantin wrote:

> I do not like this moving, because this will breaks internal  
> meanings of my code. But I will think about it. Why are you use  
> folder as upstream URL? Not repo's path?

because I package the appmenu-gtk-module separately. I could also  
reference the vala-panel-appmenu repo, directly.

Please think about it and let me know your decision.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by rilian-la-te** [comment]
Referencing repo is better, I think) Because if unity-gtk-module will adopt my patch, I will drop a fork)))

**Comment by sunweaver** [comment]
> Referencing repo is better, I think) Because if unity-gtk-module will adopt my patch, I will drop a fork)))

I have thought about this last sentence for the complete day and just now discussed some aspects with Jeremy Bicha. The question is, what approach is best and most progressive:

(a) get your patches into unity-gtk-module
(b) really fork the project completely and honestly

So my question: Have you started filing patches on Launchpad against unity-gtk-module? If so, please send me links. And then I can find out, if we can get them in.

Please note: sending patches to LP for unity-gtk-module will only work, if you have signed the Ubuntu CLA (contributors' license agreement). If that is not possible for you, then your patches won't get accepted for unity-gtk-module as of now.

Please provide some more feedback on the above. Thanks.

**Comment by rilian-la-te** [comment]
I have not been submitted my patches to unity-gtk-module, because this patches is unnecessary on Ubuntu (and harmful on it).

After then I decide to fork it.
If unity-gtk-module will abandon Ubuntu as default and its gtk patches as requirement, I will think about merging. For now, I will stays as fork.

**Comment by rilian-la-te** [comment]
Renamed.

**Comment by flexiondotorg** [comment]
Thanks for working on this @rilian-la-te :smile: 
I'm updating the Debian packaging now and will work on landing this in Debian.
