### ISSUE TITLE
Menu not working with Thunar

### ISSUE THREAD

**Issue by nkkollaw** [rilian-la-te/vala-panel-appmenu#153]
For some reason, I get no menu in Thunar. Only the app name.

Is there any way to show it? Otherwise everything else is awesome.

**Comment by rilian-la-te** [comment]
Distro, panel, do you have menu inside thunar, how are you installed a plugin? Other GTK2 apps?

**Comment by Chromace** [comment]
Hm...I've had this problem occur once or twice. Though it's intermittent. Does it end up working if you kill the "Thunar --daemon" process?

**Comment by rilian-la-te** [comment]
Close this as worksforme. Feel free to reopen it.

**Comment by nkkollaw** [comment]
@Chromace : yup, same thing. It's just not there :-/

**Comment by nkkollaw** [comment]
@rilian-la-te You're my hero. This app is amazing.
