### ISSUE TITLE
Update README for Arch Linux

### ISSUE THREAD

**Issue by andreymal** [rilian-la-te/vala-panel-appmenu#154]
Arch Linux uses `appmenu-gtk-module` instead of `unity-gtk-module`, but README don't contain instructions on how to enable it (it just offers to install it). Please add `GTK_MODULES="${GTK_MODULES}:appmenu-gtk-module"` somewhere (as for `unity-gtk-module`)

**Comment by andreymal** [comment]
Hm, I found ` /usr/lib/systemd/user/appmenu-gtk-module.service`, but:

```
andreymal@home ~ $ sudo systemctl status appmenu-gtk-module.service
Unit appmenu-gtk-module.service could not be found.
andreymal@home ~ $ systemctl status appmenu-gtk-module.service
Unit appmenu-gtk-module.service could not be found.
```

**Comment by rilian-la-te** [comment]
Try determine if this service enabled or not?

**Comment by andreymal** [comment]
andreymal@home ~ $ sudo systemctl enable appmenu-gtk-module.service
    Failed to enable unit: Unit file appmenu-gtk-module.service does not exist.
    andreymal@home ~ $ ls -l /usr/lib/systemd/user/appmenu-gtk-module.service
    -rw-r--r-- 1 root root 691 дек 13 12:54 /usr/lib/systemd/user/appmenu-gtk-module.service

Am I doing something wrong?

**Comment by andreymal** [comment]
Okay, I forgot about `--user` option, sorry

    andreymal@home ~ $ systemctl --user enable appmenu-gtk-module
    Created symlink /home/andreymal/.config/systemd/user/gnome-session.target.wants/appmenu-gtk-module.service → /usr/lib/systemd/user/appmenu-gtk-module.service.
    Created symlink /home/andreymal/.config/systemd/user/mate-session.target.wants/appmenu-gtk-module.service → /usr/lib/systemd/user/appmenu-gtk-module.service.
    andreymal@home ~ $ systemctl --user start appmenu-gtk-module
    andreymal@home ~ $ 

Anyway, @rilian-la-te can you add a note about `appmenu-gtk-module.service` in README somewhere? An hour ago I did not know that `appmenu-gtk-module.service` exists  :)

**Comment by rilian-la-te** [comment]
AFAIK, it should be enabled automatically

**Comment by andreymal** [comment]
This was not enabled automatically for me, dunno why

Anyway, even if it will be enabled automatically, I think that README should contain something like "`appmenu-gtk-module.service` will be installed and enabled automatically" :)

**Comment by rilian-la-te** [comment]
fixed for README AFAIK.
