### ISSUE TITLE
Psi+ menu items are autoclicked without real click

### ISSUE THREAD

**Issue by andreymal** [rilian-la-te/vala-panel-appmenu#155]
Steps to reproduce:

1) Install and configure vala appmenu MATE applet (obviously)
2) Install Psi or Psi+ and add two or more accounts
3) Move mouse cursor to global menu item "General" → "Add a Contact"
4) This will be auto clicked!

Video: https://www.youtube.com/watch?v=CTp5PwVdqKU (recorded with topmenu applet, but vala has same behavior)

Tested on Arch Linux and Ubuntu MATE, with Psi+ Qt4 and Psi+ Qt5.

Without global menu Psi+ menu items are not autoclicked, so it looks like global menu problem, not Psi+ problem (but not sure if this is vala problem or not)

**Comment by rilian-la-te** [comment]
What about Unity?

**Comment by andreymal** [comment]
Ubuntu 16.04, Unity 7, Psi+ Qt4 from official repo — works good

`appmenu-qt5` cannot be installed due to some dependency conflicts (dunno why), so I can't test Psi+ Qt5 right now, I'll try to test it in virtualbox later

**Comment by andreymal** [comment]
Ubuntu Unity 17.04, latest Psi+Qt5 from https://launchpad.net/~psi-plus/+archive/ubuntu/ppa —

Works good https://www.youtube.com/watch?v=K-A41cc7lzQ

**Comment by andreymal** [comment]
Ubuntu MATE 17.10, latest Psi+Qt5 from https://launchpad.net/~psi-plus/+archive/ubuntu/ppa —

Works bad https://www.youtube.com/watch?v=d73AObkPcKM (autoclick has lag here, but this is autoclick, not manual click)

Also, unlike topmenu applet, vala applet hangs after autoclick

**Comment by rilian-la-te** [comment]
I will try to build psi+ in Archlinux. And if I confirm the bug, I will try to fix it.

**Comment by rilian-la-te** [comment]
Does not happen for me in mate with vala-panel.

Screen: 

![screenshot at 2017-12-19 09-12-28](https://user-images.githubusercontent.com/1329638/34143252-d6698336-e49c-11e7-8b0a-d17618d19a66.png)

**Comment by andreymal** [comment]
You should add two or more accounts to reproduce this

**Comment by rilian-la-te** [comment]
It is strange thing of psi plus? is this a psi plus bug or my?

**Comment by andreymal** [comment]
Dunno, I'm not an C++ expert and I can't completely debug it, sorry

But without global menu everything works good:

![](https://i.imgur.com/kRi0JtS.gif)

Also Unity 7 global menu works good. So I think this is not Psi+ bug. But if you are absolutely sure that this is not a vala bug, I can create an issue in another place, if you tell me exactly where

**Comment by rilian-la-te** [comment]
Why it is not reproducible without accounts?

**Comment by andreymal** [comment]
Dunno, I'm not an C++/Qt/GTK/mate-panel/appmenu/vala expert, I'm just a user with this problem ¯\_(ツ)_/¯

**Comment by rilian-la-te** [comment]
Please, write all about this bug. Especially a conditions and reproducibilty in ArchLinux with ValaPanel.

**Comment by andreymal** [comment]
What I should write more? You can see steps to reproduce in first comment. You can see two videos with this problem. This can be reproduced on Arch Linux and Ubuntu MATE.

If you still can't reproduce it, I can record a video with EVERY smallest step to reproduce, beggining from Arch Linux installation -_-

**Comment by rilian-la-te** [comment]
I want some side cases, for example, as having 2 accounts or similar))

**Comment by andreymal** [comment]
I don't understand you. With one account it works good. With two or more accounts it works bad, as you can see in my videos. There's no other side cases

**Comment by andreymal** [comment]
Ой, я ж уже ныл по этому поводу на ЛОРе: https://www.linux.org.ru/news/opensource/13339717?cid=13341482

Правда, тогда я забыл упомянуть, что воспроизведение бага требует двух аккаунтов или больше. Теперь вот упоминаю.) (Но падать апплет с тех пор перестал, теперь юзабельно, за исключением Psi+)

**Comment by rilian-la-te** [comment]
В баню его, особенно такой специфический случай. Если сможешь его отладить (отловить, где vala-dbusmenu не то отсылает) - тогда поправлю. А у меня просто юзкейза нету, чтоб воспроизвести баг.

**Comment by snippins** [comment]
@rilian-la-te I also have auto-clicks occuring with Krusader (Qt5) and xfce4-panel. The auto-click menu entry is Tools -> MountMan. And after the auto-click happens, the menu is also not click-able.

**Comment by rilian-la-te** [comment]
Will test Krusader.

**Comment by rilian-la-te** [comment]
Confirmed for krusader, fill a bug to vala-dbusmenu.

**Comment by andreymal** [comment]
I confirm the problem with Krusader. It looks like exactly like Psi+ problem.

(Не такой уж специфический случай оказался :)

>fill a bug to vala-dbusmenu

https://github.com/rilian-la-te/vala-dbusmenu/issues/11 ?

**Comment by rilian-la-te** [comment]
yes. Will look for it.

**Comment by rilian-la-te** [comment]
Now no autoclicks in Krusader (but you cannot click item with submenu).

**Comment by andreymal** [comment]
Works good with Psi+, thanks!
