### ISSUE TITLE
Application name is hidden for musescore windows

### ISSUE THREAD

**Issue by nick87720z** [rilian-la-te/vala-panel-appmenu#162]
When i switch to musescore, it gives repeating several times:
```
(vala-panel:24850): GLib-CRITICAL **: g_variant_new_string: assertion 'g_utf8_validate (string, -1, NULL)' failed

(vala-panel:24850): Gtk-CRITICAL **: gtk_label_set_text_with_mnemonic: assertion 'str != NULL' failed
```
supposing it could be per each menu items. It is qt5 based, but i have no problems with keepassxc and soundkonverter.

**Comment by rilian-la-te** [comment]
Show me a menu. Where it violate utf8?

**Comment by nick87720z** [comment]
It depends on locale. I tried with LANG=C and sv, they are ok
![vala-panel-appmenu-musescore-ru](https://user-images.githubusercontent.com/3896190/34415148-def8b430-ec0e-11e7-93d2-70b1a1b70c79.png)
https://github.com/musescore/MuseScore.git

**Comment by rilian-la-te** [comment]
Try to fix broken application, if it does not conform utf-8

**Comment by nick87720z** [comment]
When i click on empty place, i get its menu)

**Comment by rilian-la-te** [comment]
Without qt5ct?

**Comment by nick87720z** [comment]
qt5ct itself is ok, though it has cyrillic window name too
QT_QPA_PLATFORMTHEME=fusion musescore
- same result. Btw, musescore intentionally forces internal oxygen fork, without ability to change that (they argue this by branding + crossplatform look)).

**Comment by rilian-la-te** [comment]
What about another cyrrilic window name with DBusMenu protocol, not musecore?

If it will happens, fill bug against vala-dbusmenu.

**Comment by nick87720z** [comment]
No, only MuseScore.
I tried with backintime (qt5). I got error dialog about missing backup location. It was localized. However, it was only window - main window with menu appeared only after closing this dialog (in this case it has probablity to trigger #163 ).

**Comment by rilian-la-te** [comment]
Do it works correctly now?

**Comment by nick87720z** [comment]
Hello. I think, i can try it on this week.

**Comment by rilian-la-te** [comment]
Worksforme in latest release.
