### ISSUE TITLE
Doesn't show menu for some windows, if plugin starts after those windows

### ISSUE THREAD

**Issue by nick87720z** [rilian-la-te/vala-panel-appmenu#167]
It happens for some windows if by some reason they appeared before plugin is started (e.g. plugin crashed and restarted, or just panel restart for some reaspn). For now i found it for all qt5 apps (tested on keepassxc, musescore, qtractor) and at least one java app (jsampler, might be more).

It will happen even if first appeared window is not main, as in case of backintime - i.e., error dialog about missing backup storage appears, then plugin starts, and then you press ok and main window appears (probably, it was just hidden, i'm unsure in that).

**Comment by rilian-la-te** [comment]
I know it. This is because we restart dbusmenu Registrar. Windows does not reregister itself if applet is restarted, so, we need to implement #123

**Comment by rilian-la-te** [comment]
for now it almost fixed. We have an outer registrar, which works for entire session.

**Comment by rilian-la-te** [comment]
Fixed by outer registrar, closed
