### ISSUE TITLE
work not together with windowck since todays update

### ISSUE THREAD

**Issue by rkunschke** [rilian-la-te/vala-panel-appmenu#169]
the vala appmenu and windowck title applet overlaps in xfce panel.... the problem is the size of appmenu is not as big as it should be.
anyone knows what i mean?

**Comment by rilian-la-te** [comment]
Screen, please.

**Comment by nick87720z** [comment]
I failed to reproduce it with applet version from upstream. May be versions make sence:
xfce4-panel-4.13.2
gtk+-3.22.19
and due to new xfce4-panel requirements:
libxfce4ui-4.13.4
libxfce4util-4.13.1 (this could be not related to gui)
and xfce4-windowck-plugin - tried both 0.2.4 and 0.4.4

**Comment by rkunschke** [comment]
![1](https://user-images.githubusercontent.com/29981387/34525441-402194fe-f09f-11e7-8000-a83bc7ee8498.png)
![2](https://user-images.githubusercontent.com/29981387/34525446-4352a9c4-f09f-11e7-908a-79a18089a1ac.png)
on the second picture you can see how the window title on windowck is overlapping the appmenu. the problem is since todays vala menu update

**Comment by rkunschke** [comment]
problem may be both applets are set to expand in width in panel.

**Comment by nick87720z** [comment]
Sorry, i missed word "tittle". However, i don't have issue with it too. As for me, when it is set to expand, it pushes out of panel everythin on right side - clock, systray, etc. But it doesn't happen, when set to fixed width. So, i would think, it is rather issue in that applet.
You may better try buttons-only applet. I have this config, and it is perfect :)

**Comment by rkunschke** [comment]
I have windowck 4.4.4-1
I use it without the windowtitle now since the update
its not realy a big deal but it worked with windowck title to before the update ;)

**Comment by nick87720z** [comment]
then what is panel version? I don't know, does it depend on panel really, but for me it pushes out everything on right from it, not just appmenu applet. And if appmenu is on the left, it agressively shrinks it up to pure appname. Also, in expanded mode window name in windowck is not visible :S.
Did you mean 0.4.4? Btw, this version is from 2015, git version has some recent updates... have to try it myself.

**Comment by nick87720z** [comment]
Tried experiment, placing xfce taskbar before windowck titlebar. When titlebar is set to expanded. Taskbar compresses fully, keeping for you only arrow for submenu, where are all taskbar items.

**Comment by rkunschke** [comment]
yes its thats what i meant.
I get windowck and vala menu from aur. I tried to build a newer version from git but i didn't get it to work. I have to learn something about theese things when i get time month....
XFCE Panel is 4.12.2-1.
when i set on at most setting it puch out everything on the right side. when i set it to expand it overlaps the appmenu like in my screeshots. if i fix the size the appmenu pushes the title to the right side so its not centered anymore.
before last change it takes the spaces it needet and windowck takes the rest. now it takes only the space it needs for the window menu button. the rest of appmenu is hidden by windowck when i set it to expand.
i experimented too in this way but the result was everytime the same

**Comment by nick87720z** [comment]
I have live ebuild, building latest from there.
https://github.com/cedl38/xfce4-windowck-plugin

I managed to update, but it doesn't help. If you want to build latest, you will need to copy some header from xfce4panel-1.0 to xfce4panel-2.0 (you will know it from compilation error). And build must go in source dir, or it will not fint some files in the end.

Anyway, it is windowck trouble. I remember, when i tried it last time before, it was not ok. Its correct behavior in expand mode would be to occupy only available space. If there are multiple expanded applets, like taskbar or this appmenu, equally divide their common space, but never push everything out. And windowck would set its minimum space to either some value, or even automatic (just enough to keep visible window caption, not more).
What is interesting - when i set windowck title alignment to left, it is visible. But if set event to center, it is out. May be applet sets to infinite width in expand mode, i don't know. If you think it is appmenu fail, try without it, e.g. with taskbar (window buttons). And report issue to them. Url, i gave here, may be not initial upstream, but it actually has latest changes.

As for me, i already have window name with appmenu, as well as not using compiz (i remember, windowck can activate expo when clicked). As for icon, there is vertical window list, which i have placed on the left from appmenu - another lightweight alternative for window selection.

**Comment by rkunschke** [comment]
its not a problem with windowck. its an problem with appmenu. it behaves the same with window buttons:
![jhjlhjkhlj](https://user-images.githubusercontent.com/29981387/34591908-f7239dd8-f1c0-11e7-8a8e-496cf609a32b.png)

**Comment by rilian-la-te** [comment]
I do not see any problem in Last screen.

**Comment by rkunschke** [comment]
the window buttons overlapping the rest of the appmenu
![jjjj](https://user-images.githubusercontent.com/29981387/34592237-e310eb6e-f1c2-11e7-9e5f-f20fd1e373de.png)

**Comment by rkunschke** [comment]
![besr](https://user-images.githubusercontent.com/29981387/34592383-d1b1516e-f1c3-11e7-9ac5-6d30f41b1424.png)
thats an better example to show it

**Comment by nick87720z** [comment]
On last screen: windowck buttons are only buttons, no overlaps with appmenu. Is it?
What is see, is that you have standard taskbar after appmenu. This taskbar could shorten its buttons up to showing only icons, but not before appmenu right part will be totally hidden. Since appmenu is considered mandatory-visible element (applet's head), it can't be hidden. Other part can be.
Usually, with such design (with global menu, but on some DE even without it) taskbar is moved to another panel.
Or use something more compact - button-only taskbar  (also make it grouping)
https://github.com/rilian-la-te/vala-panel-appmenu/pull/158
and again, wck buttons are all ok for me on your screen.

Yet, did you try to scroll right applet part? Or just open it and try keyboard navigation. This is new feature, added to make it ok with too long menus.

**Comment by nick87720z** [comment]
@rkunschke It may be like this:
![xfce4-panel-layout-appmenu_2018-01-05_14-04-43](https://user-images.githubusercontent.com/3896190/34602554-057a92fe-f222-11e7-89cd-119eb8c16ca9.png)

**Comment by rkunschke** [comment]
yes the window buttons overlaping the appmenu on my last screen. 
it wasn't like this before update of the appmenu. I think it is because the menu is seperated in two parts.
it wasnt like this before.
Its not a big deal i don't realy need any stuff after appmenu which can overlap it.... but i liked it how it behaeved before with windowck. 
it would be good if appmenu for xfce will get an option to deaktivate the features with seperated parts.

**Comment by rkunschke** [comment]
an yes scrolling is working.
but it would be nice to habe an option to deactivate the seperation of the appmenu.
When this is possible it would work better for me. I can image lots of unity users switcht to xfce and use it like me with appmenu on the left and winowck title on the right of it and have this issue

**Comment by rilian-la-te** [comment]
1. This is XFCE-only issue.
2. Try vala-panel :-)
3. Try icontasks layout)

**Comment by nick87720z** [comment]
Oh. Prfect, i just got windowck ok after width is set to "at most" policy. In this state it tries to use not more, than it needs?
Are not you about appname moving or at least disable, to use with wck title?

**Comment by rilian-la-te** [comment]
And overlapping is not an issue, it is feature of 0.6.x.

**Comment by rkunschke** [comment]
i understand joure point that its not an real issue.
and its an good tip with the at most option. I do not found it out myself because it worked just after a restart of the xfce panel. Thanks for the tipp.
vala panel do not work in xfce? on my system it does not but its ok how it is now.
I still would like to have an option to deactivate the feature with the seperation of the appmenu an still think this would be more user friendly for some people. 
You can decide to do it or not.
And thanks for the tipp with the at most option again. This realy helped me.

**Comment by nick87720z** [comment]
I'm using vala-panel, when need to get crash backtrace from plugin, as for now only it has appmenu as internal plugin. But when it runs, it is ok. What is good in it, i don't have so much plugins on VP,  so it is faster to restart when it is necessary.

**Comment by nick87720z** [comment]
@rkunschke Do you mean splitting menubar to window name with gtk3 menu and menubar?
btw, try to navigate menu with keyboard - you wil notice, it will go through all applet, not just selected menu half.

**Comment by rkunschke** [comment]
now the vala panel works, But i like xfce panel a bit better.
yes that what i meant. That causes my problem and thats wy its not that good in my case.
yes its the taskbar this time. I wanted to proof that its an problem in general for me and not only with windowck title plugin.

**Comment by rilian-la-te** [comment]
fixed. But vala-panel is better than xfce4-panel)))) A lot)))

**Comment by snippins** [comment]
@rilian-la-te I would love to take a look at vala-panel again since . 
The most important thing for me is that I would like to script it to follow/display on my current active monitor (not duplicating it for all monitor). A command for moving the existing panel to different monitor is sufficient for me. 

Is it possible with vala-panel?

**Comment by rilian-la-te** [comment]
It can be on primary monitor or on specific monitor. And you can change it in config. It cannot follow active monitor.

**Comment by rilian-la-te** [comment]
For moving dynamically, you can just change monitor in config file by script. Panel monitors it dynamically.

**Comment by snippins** [comment]
That should be good. Thanks!
