### ISSUE TITLE
Spacer after app name

### ISSUE THREAD

**Issue by Morvs** [rilian-la-te/vala-panel-appmenu#171]
I'm using Budgie on Arch Linux on my desktop and there's a spacer after the app name in case there are menu items, e.g. the Terminal shown in the picture below. There's no spacer if there are no items, e.g. in case of my browser  Opera.

It is the same for the MATE desktop but it's on my notebook. The spacer in this case is actually movable, on Budgie it's not.

Before I set up MATE on my notebook today I thought I might have messed up something but as it's present on two devices with separate installations I don't think so anymore.

![appmenu_spacer](https://user-images.githubusercontent.com/6150983/34545972-0a829af8-f0f1-11e7-8a3f-810f282e2740.png)

**Comment by rilian-la-te** [comment]
Already fixed in latest commit
