### ISSUE TITLE
budgie plugin broken after last update

### ISSUE THREAD

**Issue by darthoctopus** [rilian-la-te/vala-panel-appmenu#175]
The menu appears in the centre of the "left" section of the panel, without having its contents populated, bringing the menu button with it. When no window is selected, the menu button goes back to its correct position on the left.

![out](https://user-images.githubusercontent.com/5761408/34641261-4893ce90-f2cf-11e7-908f-ac0bf4f9e2a7.jpg)

**Comment by rilian-la-te** [comment]
You should set it expandable.

**Comment by darthoctopus** [comment]
That doesn't fix anything, the menu entries still aren't being populated
![screenshot from 2018-01-06 11-20-59](https://user-images.githubusercontent.com/5761408/34641531-bab441b8-f2d3-11e7-9282-e15eb1dff6d0.png)

**Comment by darthoctopus** [comment]
I bisected to find that the last working commit for me is bb089f7 (i.e. just before the scrollable-menubar patch)

**Comment by rilian-la-te** [comment]
On vala-panel it is easy. Just set it as expanded in config.

**Comment by darthoctopus** [comment]
So far, I've found that

0. Budgie-panel does not allow applets to be specified to be expandable at runtime (e.g. no expandable spacers). Instead positioning is done by way of GNOME-style CSS containers (left, center, right)
1. setting `hexpand` to `true` for  a `Budgie.Applet` at compilation does not cause it to filll up available space
2. I can override `get_preferred_width` and `get_preferred_width_for_height` to a hard-coded minimum value:

```diff
diff --git a/lib/budgie-plugin-appmenu.vala b/lib/budgie-plugin-appmenu.vala
index 89fb877..396f97a 100644
--- a/lib/budgie-plugin-appmenu.vala
+++ b/lib/budgie-plugin-appmenu.vala
@@ -58,9 +58,22 @@ public class GlobalMenuApplet: Applet
             add_budgie_style(layout);
         });
         this.add(layout);
-        add_budgie_style(layout);
+        add_budgie_style(layout);    
+        layout.set_hexpand(true);
+        this.set_hexpand(true);
+        queue_resize();
         show_all();
     }
+
+     public override void get_preferred_width(out int min, out int nat)
+    {
+        min = nat = 1000;
+    }
+
+    public override void get_preferred_width_for_height(int h, out int min, out int nat)
+    {
+        min = nat = 1000;
+    }
 } // End class
 
 [ModuleInit]
```

but it seems to me that the older behaviour was preferable, because it would push the center container out of the way to make space for long menus, only if they were very long. Also hard-coding a min width value seems inelegant.

**Comment by rilian-la-te** [comment]
Will look for it, because I also do not like scrollable menubar.

**Comment by darthoctopus** [comment]
The budgie plugin still isn't fixed, though; the alignment of the parent `BudgieMainPanel` is somehow changed from left to center (i.e. centered on the left half of the screen), rather than being anchored to the left.
![screenshot from 2018-01-06 20-34-20](https://user-images.githubusercontent.com/5761408/34645646-2c8bc138-f321-11e7-9997-ffba2f20e9e4.png)

**Comment by rilian-la-te** [comment]
Please, provide more information about your system. And do you have rebuild plugin from git?

**Comment by darthoctopus** [comment]
I'm building from git on arch linux using the PKGBUILD from the AUR (which also has to be updated now that you've renamed the folder from unity-gtk-module to appmenu-gtk-module btw)

After some experimentation I've found that commenting out line 55 (scroller.set_hexpand(true);) of menu-widget.vala fixes the issue.

**Comment by rilian-la-te** [comment]
![screenshot at 2018-01-07 04-50-46](https://user-images.githubusercontent.com/1329638/34645752-a2942254-f366-11e7-9458-37c756ca018e.png)

Fresh Budgie on Arch, latest master.

**Comment by darthoctopus** [comment]
yup, works for me too, many thanks
