### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by arifcatalyst** [rilian-la-te/vala-panel-appmenu#176]
```
make[2]: *** [applets/wnck/xembed/CMakeFiles/xembed.dir/build.make:106: applets/wnck/xembed/CMakeFiles/xembed.dir/xembed-socket.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2707: applets/wnck/xembed/CMakeFiles/xembed.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 99%] Built target i18n
make: *** [Makefile:163: all] Error 2

```

**Comment by rilian-la-te** [comment]
It is vala-panel issue. Please, post complete build log.

**Comment by rilian-la-te** [comment]
It works for me. Please, if issue persists, post it with complete information in right bugtracker
https://github.com/rilian-la-te/vala-panel

**Comment by arifcatalyst** [comment]
K, I am getting a build-error when I try to install ` appmenu-gtk-module-git`. I am on official branch of `vala-panel-appmenu-xfce`. Gtk2 apps can't export menus to the panel. 

Here is the log.

[appmenu.log](https://github.com/rilian-la-te/vala-panel-appmenu/files/1612680/appmenu.log)

**Comment by rilian-la-te** [comment]
Do not see any build error.

For export Gtk2 menus install outer registrar (on new release it is separate package, called vala-panel-appmenu-registrar-git)

**Comment by arifcatalyst** [comment]
All git packages are giving me build-error, will report it properly with log file when I have time. The issue can be at my end also, I hadn't gone through the log files yet.

**Comment by rilian-la-te** [comment]
Do you have a git installed? Can you build this directly from source?

And, please, report packaging bugs to vala-project-packages.

**Comment by arifcatalyst** [comment]
Yes, ofcourse I can build this from source. I will report it properly.

And one thing more, totally unrelated to this topic, since you are on coding streak, can I expect a fix for Jetbrain apps or it's just routine maintenance to brace up for Wayaland ?

**Comment by rilian-la-te** [comment]
JetBrains fix is strongly dependent on 
https://github.com/rilian-la-te/vala-dbusmenu/issues/10

because it is DBusMenu issue.

Can you test JetBrains app with my Jayatana and lestcape's gnome3 extension?

**Comment by arifcatalyst** [comment]
Yes, send me your Jayatana, I will test it when I get time. You want me to test in Gnome DE with Global-Menu extension ?

**Comment by rilian-la-te** [comment]
Yes. Jayatana is build per README instructions on vala-panel-appmenu, you can see it.

Yes, test it with IDEA or PyCharm. I want to know, is menu correct?
If is, this is my vala-dbusmenu fault.
If is not, this is my JAyatana fault.

**Comment by arifcatalyst** [comment]
K, I'll report you back with it and If it's vala-dbusmenu fault then ? Are you going to implement it even if it needs a whole rebuilt from scratch ?

**Comment by rilian-la-te** [comment]
if it is Jayatana fault, report also, if you will using JAyatana from this repo, not from others.
