### ISSUE TITLE
Request fot providing it for gnome-shell

### ISSUE THREAD

**Issue by Mamad026** [rilian-la-te/vala-panel-appmenu#177]
Hi there.
@rilian-la-te 
Can you provide a gnome-shell extension for GNOME DE? 
In other case we already have [this extension](https://extensions.gnome.org/extension/1250/gnome-global-application-menu/) for gnome, but the matter is it can't work on wayland sessions and it has some issue to display menu bar in panel (it's not completely fit, just try it once and you can see it). So if you can provide a global menu extension for gnome-shell like [this](https://github.com/rilian-la-te/vala-panel-appmenu) it would be great.
Regards.

**Comment by rilian-la-te** [comment]
Use https://github.com/lestcape/Gnome-Global-AppMenu

It is working AFAIK. Closing this.
