### ISSUE TITLE
Global appmenu cut off in mate-panel

### ISSUE THREAD

**Issue by dact221** [rilian-la-te/vala-panel-appmenu#179]
Hi,

I was using `mate-vala-panel-appmenu-plugin` from Fedora COPR repositories without problems, but now it's cut off.

Appmenu only shows application name and the first character of "File" menu.

I uninstalled `mate-vala-panel-appmenu-plugin` and compiled it from GitHub, but I get the same problem.

I'm using Fedora Workstation 27, MATE 1.19.2 and mate-panel 1.19.4

![screenshot-00](https://user-images.githubusercontent.com/35376194/34885854-27e509e0-f7b9-11e7-838b-067aae6e35b6.png)

![screenshot-01](https://user-images.githubusercontent.com/35376194/34885852-273edbb0-f7b9-11e7-90bc-da36589b2f1a.png)

**Comment by rilian-la-te** [comment]
Will look for it. Do removing and adding plugin work?

**Comment by andreymal** [comment]
Same problem for me after AUR upgrade today. Also, it crashed several times

**Comment by andreymal** [comment]
@rilian-la-te  Cannot build from AUR:

```
[ 73%] Generating mate-plugin-appmenu.c
aur-vala-panel-appmenu-mate-git/src/vala-panel-appmenu/lib/mate-plugin-appmenu.vala:30.5-30.7: error: syntax error, expected `;'
    var layout = new Appmenu.AppMenuBar();
    ^^^
aur-vala-panel-appmenu-mate-git/src/vala-panel-appmenu/lib/mate-plugin-appmenu.vala:34.1-34.1: error: expected end of file
}
^
```

**Comment by andreymal** [comment]
It works, thanks

**Comment by andreymal** [comment]
...but it still crashes. Dunno how to debug it

**Comment by dact221** [comment]
Thanks. Now I'm going to wait for @alunux to submit a new build to COPR.
