### ISSUE TITLE
Install description on README

### ISSUE THREAD

**Issue by moshpirit** [rilian-la-te/vala-panel-appmenu#18]
As an Arch user, I'm used to search all the packages on AUR or compile them by myself following some README instructions. Why is it relevant? Well... I've been thinking on install Debian XFCE and [since it's not in the official repositories](https://search.debian.org/cgi-bin/omega?DB=en&P=vala-panel-appmenu) it has to be manually installed. Since there's not .deb, the only way to install it is by compiling it onself. That's why I'm asking for some instructions. 

Thanks a lot for the software!!

**Comment by rilian-la-te** [comment]
This can be compiled by dpkg-buildpackage (it has a debian folder). And it needs libbamf and unity-gtk-module-standalone, which also not in repos in Debian.

**Comment by moshpirit** [comment]
dpkg-buildpackage OK, thanks a lot! :)

**Comment by moshpirit** [comment]
Sorry for commenting here again, this is a bit embarrassing but I only can find the package unity-gtk-module-standalone for Ubuntu (PPAs) and Arch (AUR). Please, would you mind to tell me where can I find the Debian package for this?

**Comment by rilian-la-te** [comment]
Install from PPA or use my patch and build unity-gtk-module from source
