### ISSUE TITLE
Menus than opening windows crashes DBusMenu sometimes.

### ISSUE THREAD

**Issue by andreymal** [rilian-la-te/vala-panel-appmenu#180]
Variant of steps to reproduce (not tested in non-Arch Linux or non-MATE DE, but ~~[YOU'RE GOING TO LOVE PSI](https://i.imgur.com/yleXWRJ.jpg)~~ I hope you can reproduce it):

1) Open Psi+
2) Open and click global menu "General" → "Help" → "About"
3) Close "About" window
4) ???
5) Crash!

Video: https://www.youtube.com/watch?v=evfjSuqeDxI

Also you can try to reproduce it with Krusader:

1) Open Krusader
2) Move the mouse cursor to "Tools" → "MountMan" menu item
3) It will be [autoclicked](https://github.com/rilian-la-te/vala-dbusmenu/issues/11) AND crashed

Full backtrace from gdb: https://pastebin.com/fg8z7rwT

**Comment by rilian-la-te** [comment]
Rebuild GTK and GLib with gnome stack. Bug confirmed, reproducible with vala-panel too.

**Comment by andreymal** [comment]
Found yet another way to reproduce: toggle the visibility of Telegram by clicking to tray icon

>Rebuild GTK and GLib and other gnome stack with debug symbols

Sounds hard to me... but maybe I'll try someday

**Comment by andreymal** [comment]
Looks like it crashes after closing of any non-gtk window, even xterm or glxgears. Maybe because you try to free gtk-specific nullptr somewhere

**Comment by andreymal** [comment]
i didn't rebuild gtk and glib yet, but i rebuilt vala applet with debug symbols, perhaps it will also be useful for you.

It crashes at [vala-panel-appmenu/lib/appmenu-bamf.vala:91](https://github.com/rilian-la-te/vala-panel-appmenu/blob/70ac645bf1833c5b769991b233e43566dad40ee4/lib/appmenu-bamf.vala#L91):

```vala
if (app is Bamf.Application)
```

Full backtrace: https://pastebin.com/7FdmxVCC

**Comment by rilian-la-te** [comment]
Ok, will look for it. But I need full backtrace.

**Comment by andreymal** [comment]
I rebuilt Arch packages `glib2-2.54.3-2-x86_64` and `gtk3-3.22.26+47+g3a1a7135a2-3-x86_64` with `options+=(debug, !strip)`, and there's new backtrace: https://pastebin.com/2kQKNbbV

**Comment by rilian-la-te** [comment]
Thanks

**Comment by rilian-la-te** [comment]
Check latest release, please.

**Comment by andreymal** [comment]
I works 👍

**Comment by rilian-la-te** [comment]
So, only remaining is Jayatana? It is good)
