### ISSUE TITLE
CMAKE Problem

### ISSUE THREAD

**Issue by peridot-idk** [rilian-la-te/vala-panel-appmenu#182]
So I decided to install this on Ubuntu but I am having a problem SO I get this:

> `-- Looking for RPMTools... - found rpmuild is /usr/bin/rpmbuild
-- RPMTools:: Using RPM_ROOTDIR=/home/kenneth/vala-panel-appmenu/RPM
-- Configuring spec file </home/kenneth/vala-panel-appmenu/rpm/vala-panel-appmenu.spec.in> --> </home/kenneth/vala-panel-appmenu/RPM/SPECS/vala-panel-appmenu.spec>
-- RPMTools:: Using RPM_ROOTDIR=/home/kenneth/vala-panel-appmenu/RPM
-- Configuring spec file </home/kenneth/vala-panel-appmenu/rpm/appmenu-gtk-module.spec.in> --> </home/kenneth/vala-panel-appmenu/RPM/SPECS/appmenu-gtk-module.spec>
-- RPMTools:: Using RPM_ROOTDIR=/home/kenneth/vala-panel-appmenu/RPM
-- Configuring spec file </home/kenneth/vala-panel-appmenu/rpm/java-appmenu.spec.in> --> </home/kenneth/vala-panel-appmenu/RPM/SPECS/java-appmenu.spec>
-- checking for a minimum Vala version of 0.24
--   found Vala, version 0.30.1
-- Checking for module 'gtk+-3.0>=3.20'
--   
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:70 (pkg_check_modules)

> -- Configuring incomplete, errors occurred!
> See also 

> "/home/kenneth/vala-panel-appmenu/CMakeFiles/CMakeOutput.log".`

It Doesn't say which package is missing at all. Is there a fix for it?

**Comment by rilian-la-te** [comment]
Gtk is not found, because it was latest. About a fix - I can consider it)

**Comment by peridot-idk** [comment]
Hmm thats weird. I have gtk installed hmm weird

**Comment by rilian-la-te** [comment]
If you do not have a good distro (like arch or gentoo), you also need devel packages of all dependencies? Do you have devel package? ```libgtk-3-dev``` for Ubuntu.

**Comment by peridot-idk** [comment]
Yep already have that and its still not working :(

**Comment by rilian-la-te** [comment]
Please, show me an error. And this package version.
