### ISSUE TITLE
build failure for vala

### ISSUE THREAD

**Issue by SolarAquarion** [rilian-la-te/vala-panel-appmenu#183]
[ 51%] Generating appmenu-bamf.c;appmenu-desktop.c;registrar.c;menubar.c;menu-widget.c;menu-widget-dbusmenu.c;menu-widget-menumodel.c;menu-widget-importer.c;/home/solaraquarion/build/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/vapi/config.c;vala-panel-appmenu.vapi;vala-panel-appmenu.h                                                                                            
error: Package `dbus-menu-importer' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)

**Comment by rilian-la-te** [comment]
Will fix it soon, forgot to remove line.

**Comment by rilian-la-te** [comment]
fixed
