### ISSUE TITLE
No AppMenu in Glade ( User Interface Designer ) and Firefox

### ISSUE THREAD

**Issue by gladosfromaperturelabs** [rilian-la-te/vala-panel-appmenu#184]
Everything works fine, chrome, openoffice, geany-gtk3,  virtualbox, gedit, qbittorrent... but in Firefox 58 there isn't appmenu and in Glade the menus are shown in the app.

(I'm using the budgie version on arch, installed using AUR)

**Comment by rilian-la-te** [comment]
Glade is blacklisted, remove blacklist in gsettings (removing will cause bugs ) . Firefox is not supported outside of Ubuntu.
