### ISSUE TITLE
Importer: Incorrectly parses DBusMenu and gives incorrect MenuModel

### ISSUE THREAD

**Issue by andreymal** [rilian-la-te/vala-panel-appmenu#185]
This bug appeared recently, perhaps after Psi+/Krusader autoclick fix. Few months ago virtualbox worked good

![](https://i.imgur.com/Mv8iaIs.png)

**Comment by rilian-la-te** [comment]
Will look for it, this is importer bug.

**Comment by rilian-la-te** [comment]
Today, perhaps.

**Comment by andreymal** [comment]
Now I found that flicker is also present in Psi+ and Krusader with any submenus :)

But GIMP works good without that, looks like yet another Qt problem

**Comment by rilian-la-te** [comment]
It is importer problem, it flickers because it loads a menu from DBus (yes, now loading is partial).
I will look for it, but for me it is minor issue.

**Comment by rilian-la-te** [comment]
Opening happens before loading.

**Comment by rilian-la-te** [comment]
I want to know all about flickering.
How many it happens? Only first opening of a menu or all times? On all levels of submenus or only on specific level?

**Comment by andreymal** [comment]
I tested Psi+ right now again, and some menus were missing again :D

I can't find some logic of this problem, please see this video: https://www.youtube.com/watch?v=2okVl93W4Dc

It can be:

- missing (0:05, 0:54)
- flickering (many times, e.g. 0:22)
- worked good (0:39)

Submenu in submenu is also buggy (0:22)

Same behavior with virtualbox and krusader

**Comment by rilian-la-te** [comment]
Ok, with next commit I will enable debugging mode for vala-panel-appmenu.
Can you run vala-panel (not another panel) with appmenu it terminal and send XMLs to me?

And with each XML I want info, what exactly not working.

**Comment by andreymal** [comment]
*(later, [it's time to go to bed](https://www.youtube.com/watch?v=mCk3y5FZaXg) in my timezone)*

**Comment by rilian-la-te** [comment]
It my timezone it is 03.22 MSK, so, I will wait)))

**Comment by rilian-la-te** [comment]
But I cannot confirm missing menus, sorry (I tried both VirtualBox, QtCreator, Krusader and Psi+). Max issue I see is flicker, but it is minor for me.

What PC configuration are you have? Do you have slow D-Bus?

**Comment by andreymal** [comment]
Missed menus are hard for reproduce, they are very random and very rare, I made this video at tenth attempt :)

**Comment by rilian-la-te** [comment]
By XMLs I need to determine a source of bug, this is incorrect parser (I really do not want to rewrite it 5th time), or just incorrect signal handling (So, then I need to emit fewer signals), or it is just my overhead tp avoid menu updating frequently (So, then I will disable some),

**Comment by andreymal** [comment]
>What PC configuration are you have?

[Acer Aspier E5-571G](https://www.acer.com/ac/en/LA/content/model/NX.MLZST.001) + Arch Linux + MATE

>Do you have slow D-Bus?

Dunno ¯\\(°_o)/¯

**Comment by rilian-la-te** [comment]
If you have mate-panel, you can use it for debugging (applets are executables then, you can just killall appmenu-mate and restart it in terminal, and just click "restart" on "Applet crashed" window).

**Comment by rilian-la-te** [comment]
But it is OK PC for me, it should work and use DBus normally.

**Comment by rilian-la-te** [comment]
And I really need some XMLs with missing menus (not flicker, but XMLs with missing menus and you should supply it with correct screen or text description of menu)

**Comment by rilian-la-te** [comment]
Короче, вот тебе описание по русски, как на ЛОРе , я удалю потом:

Я на [коммите](https://github.com/rilian-la-te/vala-panel-appmenu/commit/4796cf4344c3ce5b536b34a42c6d3e9d2f2425f8) полностью заменил реализацию протокола DBusMenu, что позволило мне более просто играть с менюшками.

Если раньше я отрисовывал менюшку сам через [vala-dbusmenu](https://github.com/rilian-la-te/vala-dbusmenu), то теперь я рисую ее посредством такой вещи, как Importer.

Importer работает следующим образом - он позволяет превратить Qtшный протокол DBusMenu в протокол MenuModel, который используется Gtk. Примерно также unity-gtk-module работает, но у него сложнее.

Ну и, собственно, сложности:
1. MenuModel не любит частой смены содержимого меню (а оно там неизменяемое, можно только пункт полностью заменить)
2. MenuModel понимает только один сигнал - items-changed, где и говорится, в каком месте сколько пунктов удалено, сколько добавлено.
3. В MenuModel нет пункта-разделителя (тогда б все просто было), там есть понятие секции, и эти секции из разделителя нужно как-то генерировать (и они тоже являются MenuModel, и для них нужен отдельный сигнал)
4. В MenuModel нет понятие открытого и закрытого меню (оно там может быть кое-как ограничено как submenu-action, но не очень-то и хорошо, потому что о закрытии он сигнал вроде не дает)
5. Теперь я получаю не всегда полностью всю структуру, а частично - только ту, что нужна на построение модели текущего уровня (по факту это 2 уровня - уровень секций и уровень их элементов)


Откуда может быть баг:
1. Сигналов летит очень много, и они могут теряться 
2. Я ограничил обновление меню из-за этого, оно может быть тупо не получено.

Вот как-то так.

**Comment by rilian-la-te** [comment]
And so, I will want info, did appmenu write some other info (about LayoutUpdated signal)?

**Comment by andreymal** [comment]
Right now menu items were duplicated LOL https://www.youtube.com/watch?v=GWVEfwyMrIs (0:31)
https://pastebin.com/5hUjtGL1

**Comment by rilian-la-te** [comment]
Ok, I will looking for it) Because I saw it too. Importer is very buggy now.

**Comment by andreymal** [comment]
...now appmenu-mate just finished with exit code 0
https://www.youtube.com/watch?v=uTxAztUt3YU
https://pastebin.com/tDQLiBue

But I'll still try to catch empty submenu later

**Comment by andreymal** [comment]
That was segfault
https://www.youtube.com/watch?v=AG5QTYYrhis
https://pastebin.com/NrrkVarx
But it looks like another issue, should I create it?

**Comment by rilian-la-te** [comment]
No there is this issue, but I will rename it)

**Comment by rilian-la-te** [comment]
Look to latest revision. If it will remove bugs - I will stick with it and try to fix Jayatana.

**Comment by andreymal** [comment]
Now I can't reproduce segfault, but it's still flickering. Missing or duplicated menu is a very rare case, I'll write about this later

It prints some garbage and gtk warnings, maybe it will be useful for you https://pastebin.com/fnw2xypD

**Comment by rilian-la-te** [comment]
Do not see any garbage, and warnings are my warnings, because for me this is not good. 
hex chars is icons than items give to us with DBusMenu.

**Comment by rilian-la-te** [comment]
I need to know about duplicating or missing, not flicker (flicker is very minor)

**Comment by andreymal** [comment]
Hm, now it also crashes sometimes, but very randomly, can't catch it yet

**Comment by andreymal** [comment]
Empty submenu in VLC... but also not catched :(

Okay, I will not flood now, I'll be back only with xml/video/bt

**Comment by rilian-la-te** [comment]
I know about VLC, it just sends too old version. What revision are you have?

**Comment by rilian-la-te** [comment]
Can you check latest revision?

**Comment by andreymal** [comment]
https://github.com/rilian-la-te/vala-panel-appmenu/commit/e3bf1e8ff2b0794d0032d2d8652b81ee14b2a127 ? I'm already testing it last hour

And it crashed right now https://www.youtube.com/watch?v=fGhV5BmdFdE
https://pastebin.com/UaAxF7fL

**Comment by andreymal** [comment]
It crashes when I close SMPlayer, this is repeatable crash for me

**Comment by rilian-la-te** [comment]
I will look for it now.

**Comment by vincentez1** [comment]
I think my problem belongs here... yesterday the menus in QGis (QT4) did not show. Today, with your revisions, they do appear but there are blank spots, empty submenus, and many grayed out options.  I'm using Xfce on Arch.
QGIS shows the following when launched:
Warning: QLayout: Attempting to add QLayout "" to QgsPanelWidgetStack "mWidgetStack", which already has a layout
Warning: void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "&Toolbox" under id 254 

PS. Liking the make_appname_bold option in compiling the software, but it still goes wrong in places like the desktop where the last entry is bold, not the appname.

**Comment by rilian-la-te** [comment]
I will fix it eventually, sorry for big change now.

**Comment by andreymal** [comment]
I confirm same problems with qgis
https://www.youtube.com/watch?v=2YumngzyxAU (0:04)
https://pastebin.com/wJUc1Vfe (line 1056+)

**Comment by rilian-la-te** [comment]
It is after or before fix?

**Comment by andreymal** [comment]
Before :)

Okay, I'll try to update it now

**Comment by rilian-la-te** [comment]
It should crash

**Comment by andreymal** [comment]
Yes, it crashes again with Psi+

But qgis works better (as long as I remember, some menu items were not clickable, now they're clickable)

**Comment by rilian-la-te** [comment]
I need backtrace. If it crashes and you want fix, you should give me backtrace.

**Comment by andreymal** [comment]
https://pastebin.com/6UZK9196

**Comment by rilian-la-te** [comment]
thanks. Looking for it.

**Comment by rilian-la-te** [comment]
Test it now, please. Only flickering should remain.

**Comment by andreymal** [comment]
VLC crashed if I hover mouse cursor to «Вид»
https://www.youtube.com/watch?v=5mYYRVKRZqg
https://pastebin.com/t60dRfnx

If VLC is not crashed, then there are some empty submenus (e.g. subtitles or audio stereo mode)

But SMPlayer, qgis and Psi+ are working good (except flicker)

**Comment by rilian-la-te** [comment]
Will look for this crash.

**Comment by rilian-la-te** [comment]
About empty submenus - it is in original VLC menu too. Crash will be fixed

**Comment by rilian-la-te** [comment]
Hmm, difflicult crash. Can you found another app when it crashes too?

**Comment by andreymal** [comment]
No, there were no other crashes today

**Comment by rilian-la-te** [comment]
Ok, I found a source AFAIK, will try to fix. And reduce flickering somehow as a side effect.

**Comment by rilian-la-te** [comment]
Try again) If only flickering remains, so, issue is solved)

**Comment by rilian-la-te** [comment]
Try now - now empty submenus is hidden from VLC (gtk problem - for MenuModels with submenus disabled is not working as I expect).

**Comment by rilian-la-te** [comment]
Crash is fixed now, but empty menus remain (because trying to remove it cause bugs, and MenuModels is not disabling items with submenus)

**Comment by rilian-la-te** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=793082

**Comment by rilian-la-te** [comment]
What is better, fickering or slow (as in #186 ) menus?

**Comment by andreymal** [comment]
Now it works good for me, no flicker or empty menus (except VLC) yet, but I should test it more days

>now empty submenus is hidden from VLC

Nothing changed (but this is minor)

>slow (as in #186 ) menus

Can't confim, VLC is very fast for me, everything works great now :)

**Comment by rilian-la-te** [comment]
I will looking for fixing empty submenus, it is GTK problem - it does not want to disable entries with submenus. But I will force it to disable or hide disabled submenus.

**Comment by rilian-la-te** [comment]
Empty submenus was hidden in that revision, but I reverted it later - causes major bug in QtCreator,

**Comment by rilian-la-te** [comment]
Empty submenus should be gone now)

**Comment by rilian-la-te** [comment]
Now it is good? If so, close the bug)

**Comment by rilian-la-te** [comment]
Please, write me about fixing this)

**Comment by andreymal** [comment]
It is good :)
