### ISSUE TITLE
vlc works slow

### ISSUE THREAD

**Issue by FastOSlinux** [rilian-la-te/vala-panel-appmenu#186]
when running a video the menu is slow

OS Fedora 27 xfce
VLC 3.0.0 rc2

i74790k
gtx 1060 nvidia driver
8gb ram

video attached

[vlcslow.zip](https://github.com/rilian-la-te/vala-panel-appmenu/files/1674296/vlcslow.zip)

**Comment by rilian-la-te** [comment]
It is slow first time opening or at all?

**Comment by rilian-la-te** [comment]
For me, VLC menu is not shown (but it is qt4 vlc).

**Comment by FastOSlinux** [comment]
@rilian-la-te as I show in the video, is slow when running videos. Nothing running is ok

**Comment by rilian-la-te** [comment]
Ok, I see. I will look for it)

**Comment by rilian-la-te** [comment]
Now is OK? Latest revision?

**Comment by rilian-la-te** [comment]
Again? Now is OK? Latest revision?

**Comment by FastOSlinux** [comment]
I decided to use vlc via flatpak, it has no menu lentidao, but global menu does not work

**Comment by rilian-la-te** [comment]
hmm, it is strange. Can you show me a VLC d-feet page?

**Comment by rilian-la-te** [comment]
Can you also give me a link to VLC Flatpak?

**Comment by FastOSlinux** [comment]
@rilian-la-te installed by flathub

**Comment by rilian-la-te** [comment]
ok. 

> Can you show me a VLC d-feet page?

And can you add a --talk-name=com.canonical.AppMenu.Registrar to your flatpak?

**Comment by FastOSlinux** [comment]
@rilian-la-te ??

**Comment by rilian-la-te** [comment]
flatpak --user override --talk-name=com.canonical.AppMenu.Registrar org.videolan.VLC

**Comment by rilian-la-te** [comment]
Do menu work after this?

**Comment by FastOSlinux** [comment]
@rilian-la-te no

**Comment by rilian-la-te** [comment]
but menu itself is shown or not?

**Comment by rilian-la-te** [comment]
Or it is shown in app?

**Comment by FastOSlinux** [comment]
@rilian-la-te 
![captura de tela_2018-02-02_22-51-58](https://user-images.githubusercontent.com/17401812/35761049-b516bec2-086b-11e8-8213-a1263e186280.png)

**Comment by rilian-la-te** [comment]
So, it will not working for Flatpak, because we need to write flatpak runtime extension with appmenu. Can you do it?

**Comment by rilian-la-te** [comment]
And I will close this, because it now preloads a menu and should work faster.
