### ISSUE TITLE
Appmenu takes too much space in xfce4-panel

### ISSUE THREAD

**Issue by hetake2** [rilian-la-te/vala-panel-appmenu#187]
Hi guys, just installed appmenu for xfce4 and noticed one problem with applets on my xfce4-panel: appmenu takes too much space for itself and my Clock with Notification Area cant be in the middle of panel. Separators don't work ether. 
![zvvk9iw](https://user-images.githubusercontent.com/16861224/35538979-a5747db4-0547-11e8-8f4e-a0ad62a734a8.png)

**Comment by rilian-la-te** [comment]
Symptoms, revision? Do this is true on other panels, especially vala-panel?

**Comment by hetake2** [comment]
> Symptoms, revision? Do this is true on other panels, especially vala-panel?
No, vala-panel is okay, only xfce4-panel has this problem with stretching.

**Comment by rilian-la-te** [comment]
Test, and if fixed, Close bug.

**Comment by hetake2** [comment]
> Test, and if fixed, Close bug.

Well, now its completely broken xD, the appmenu no more eating space, but it's kinda too short now.
(chromium)
![screenshot_2018-01-30_15-56-43](https://user-images.githubusercontent.com/16861224/35567461-10b000a6-05bd-11e8-8d81-4b60486e1255.png)

**Comment by rilian-la-te** [comment]
Ok, but it will eats space or you want old behaviour (when menu was unscrolled)?

**Comment by hetake2** [comment]
Have not tried the old behavior, but is there any possibility to make it taking like 1/3 of the panel space and not moving other applets when it expands? I mean, to give it fixed size.

**Comment by rilian-la-te** [comment]
Old behaviour is take all needed space for menu and no pixel more.
New is take all.

Take 1/3 is not good for me.

**Comment by hetake2** [comment]
So, how can I switch to the old one? :)

**Comment by rilian-la-te** [comment]
Latest old version commit: https://github.com/rilian-la-te/vala-panel-appmenu/commit/bb089f7829ffb377ac4ed2ae36d17e65464ce220

I do not support it for now. so, if you find a bugs, you will need to check it with latest version.

**Comment by rilian-la-te** [comment]
Warning: old version will not work with new vala-panel now!
