### ISSUE TITLE
XFCE Vala Panel Appmenu partially hidden

### ISSUE THREAD

**Issue by jppmarujo** [rilian-la-te/vala-panel-appmenu#188]
I'm on Manjaro XFCE, and installed vala-panel-appmenu-xfce-git from AUR. 

The menu is always partially hidden, as in here (image is from another Github user, the behavior is the same):

![image](https://user-images.githubusercontent.com/32954931/35615550-58cf1ac2-066a-11e8-9676-c8479812f0ce.png)

This happens for all applications, **not only Chromium**.
If i install a previous version from the Community repo, it shows, but force closes after some time.

What can i do in order to fix it (regarding the latest version)?

Thank you for your work, the Menu is great!

**Comment by rilian-la-te** [comment]
Will look for it, it is XFCE only bug. You can revert latest commit)

**Comment by rilian-la-te** [comment]
should be fixed
