### ISSUE TITLE
Can't compile Vala Panel Appmenu (Could NOT find Vala (missing: VALA_EXECUTABLE))

### ISSUE THREAD

**Issue by Alef990** [rilian-la-te/vala-panel-appmenu#189]
Hi, I've tried to install Vala Panel using the pre-compiled package on system's repo, but the applet doesn't appear when I try to add it to my MATE panel. Now, I'm trying to compile Vala Panel in openSUSE Leap 42.3, but the compiler isn't finding the Vala executable, as you can see below.

alef990@alef990-suse  ~/Downloads/Sources/vala-panel/build $ cmake .. -DENABLE_XFCE=OFF -DENABLE_BUDGIE=OFF -DENABLE_VALAPANEL=ON -DENABLE_MATE=ON -DENABLE_JAYATANA=ON -DENABLE_UNITY_GTK_MODULE=ON -DMAKE_BOLD_APPNAME=ON -DCMAKE_INSTALL_PREFIX=/usr
-- Looking for RPMTools... - found rpmuild is /usr/bin/rpmbuild
-- RPMTools:: Using RPM_ROOTDIR=/home/alef990/Downloads/Sources/vala-panel/build/RPM
-- Configuring spec file </home/alef990/Downloads/Sources/vala-panel/rpm/vala-panel.spec.in> --> </home/alef990/Downloads/Sources/vala-panel/build/RPM/SPECS/vala-panel.spec>
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Vala (missing: VALA_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindVala.cmake:55 (find_package_handle_standard_args)
  CMakeLists.txt:82 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/alef990/Downloads/Sources/vala-panel/build/CMakeFiles/CMakeOutput.log".
 alef990@alef990-suse  ~/Downloads/Sources/vala-panel/build $ 

How can I proceed to fix this?

**Comment by rilian-la-te** [comment]
Do you have vala installed? and which version?

**Comment by Alef990** [comment]
At this moment, I have no Vala installed.

**Comment by rilian-la-te** [comment]
so, what you want? you should install Vala compiler at least 0.36.0.

And read README, please.

**Comment by rilian-la-te** [comment]
I am closing this,
