### ISSUE TITLE
Instruction using this

### ISSUE THREAD

**Issue by wesleyotugo** [rilian-la-te/vala-panel-appmenu#19]
How do we go about using this, what do we do ? How do i use this in arch linux. I have installed the package what next

**Comment by rilian-la-te** [comment]
1. Install optional dependencies (without this appmenu works with very few programs like file-roller)
2. Add applet to the panel (No matter XFCE or Vala)
3. Add into .profile:
-  export UBUNTU_MENUPROXY=libappmenu.so
-  export GTK_MODULES=unity-gtk-module:$GTK_MODULES
4. Set properties gtk-shell-shows-appmenu && gtk-shell-shows-menubar in xfce4settingsd (XFCE) of .config/gtk-3.0/settings.ini (ValaPanel) to 1 (true)

Report success here.

If you understand Russian, search in [LOR](linux.org.ru)

**Comment by wesleyotugo** [comment]
Aye
