### ISSUE TITLE
Menu got out of screen if the panel is at the bottom.

### ISSUE THREAD

**Issue by snippins** [rilian-la-te/vala-panel-appmenu#190]
KDE Neon, xfce4-panel 4.12

For apps that use dbusmenu like Firefox, VSCode, Krusader, many menu entries when out of screen when the panel is at the bottom of the screen.

![bug](https://user-images.githubusercontent.com/6032077/35664600-c626b6e0-075d-11e8-925b-cdc23a269add.png)

**Comment by snippins** [comment]
As I remember I made workaround for a problem similar to this by calling out to AboutToShow() on level 1 menu entries. But since the recent changes I think that workaround is lost.

By the way on my machine I have never experience any flickering. It might be because in newer gtk versions they recalculate the position of the menu and cause the flickering? I suspect a similar workaround like pre-populating level 1 menu entries might able to solve both problems.

**Comment by rilian-la-te** [comment]
Will look for it, but for now it is not so simple.

**Comment by rilian-la-te** [comment]
Tomorrow will be commit than adds a hack back (sorry, no Internet now) :-(

**Comment by snippins** [comment]
Thanks, everything seem fixed. :D
