### ISSUE TITLE
does not work window game mode (opengl / vulkan)

### ISSUE THREAD

**Issue by FastOSlinux** [rilian-la-te/vala-panel-appmenu#192]
Fedora 27 xfce
or would it be a problem with the xfce function in disabling title bar?

![captura de tela_2018-02-04_17-30-40](https://user-images.githubusercontent.com/17401812/35781443-5a905e4c-09d1-11e8-93d9-16ab3fdb0b0f.png)

**Comment by rilian-la-te** [comment]
Appmenu have nothing to do with titlebar. So, closing this. Feel free to reopen, if it caused exactly by appmenu
