### ISSUE TITLE
Menu bars do not restore after uninstall (Fedora 27; XFCE)

### ISSUE THREAD

**Issue by ayhc** [rilian-la-te/vala-panel-appmenu#195]
My issue is similar to Issue #92. I'm using Fedora 27 with XFCE.

To replicate:
- Uninstall vala-panel-appmenu
- Reset the xfconf variables to "false"

Expected behaviour:
- Menubars reappear

Actual behaviour:
- Menubars do not reappear
- (After manually creating a GTK3 settings.ini) Thunar menubar reappears, but not anything else

**Comment by rilian-la-te** [comment]
Session was restarted?
All packages was removed?

**Comment by rilian-la-te** [comment]
And why you uninstalled it? It is so boring?

**Comment by ayhc** [comment]
Uninstalled everything and rebooted. My experience has been that the XFCE plugin doesn't always play nice with Firejail (Firetools in particular causes it to crash).

**Comment by rilian-la-te** [comment]
What is Firejail and Firetools? Can you provide a link to it?

**Comment by rilian-la-te** [comment]
Unity-gtk-module was installed? And if so, was it removed?

**Comment by rilian-la-te** [comment]
Looking to Firejail in ArchWiki, and do not understand which causes crashes. Can you provide a complete backtrace for it?

**Comment by ayhc** [comment]
Info on Firejail and Firetools here: https://firejail.wordpress.com/download-2/

Will try running a backtrace and post again once I do that.  Not sure if I did uninstall appmenu-gtk-module, but I don't think I did as it's also required by hud-menu (https://github.com/jamcnaughton/hud-menu).

**Comment by rilian-la-te** [comment]
If you are not uninstalled it, then killing Registrar should be sufficient to show a menus. Do you uninstalled Registrar?
Now if appmenu-gtk-module sees a Registrar, it removes a menus.
If someone provides com.canonical.AppMenu.Registrar for you - no menus.
You should use unity-gtk-module, if you want menus with Registrar enabled. appmenu-gtk-module does not support it for now, because it will complicate things in Wayland. (appmenu-gtk-module supports Wayland in GNOME with @lestcape plugin.

**Comment by rilian-la-te** [comment]
If Firetools crashes a menu, I will look for this in Importer (it should not be)

**Comment by rilian-la-te** [comment]
Cannot confirm a firetools crash. Just installed it and ran, all is OK (but no menu appears except stub). Latest vala-panel-appmenu master with Importer.

**Comment by rilian-la-te** [comment]
Do it fixed now?

**Comment by ayhc** [comment]
Just tried installing the latest version from git, and now I get "Plugin 'AppMenu Plugin' unexpectedly left the panel, do you want to restart it?" every time I open the XFCE Whisker menu :-(

**Comment by rilian-la-te** [comment]
Ok, will look for it. I do not use XFCE, sorry. Only Whisker Menu? Or another?

**Comment by rilian-la-te** [comment]
Does not crashes for me, just installed Whisker Menu. On ArchLinux.

**Comment by rilian-la-te** [comment]
Closing this. Feel free to reopen if happens.

Now this is INCOMPLETE
