### ISSUE TITLE
appmenu-gtk-module: GTK+2 apps don't show menu at all under KDE Plasma

### ISSUE THREAD

**Issue by dos1** [rilian-la-te/vala-panel-appmenu#197]
With appmenu-gtk-module installed and active, and with the global menu being enabled in KDE Plasma (so, the registrar is working), the menu bar of GTK+2 apps is hidden and there is no global menu displayed.

Global menus work well with Qt4, Qt5 and Electron apps. I'm not sure how to make them work with GTK+3, but at least the menu is shown inside the window there. With appmenu-gtk-module, there is no menu whatsoever with GTK+2 apps. (unless uninstalled or disabled with `UBUNTU_MENUPROXY=0`)

**Comment by rilian-la-te** [comment]
Because appmenu-gtk-module thinks than global menu is enabled and gives a menu to Plasma, which Plasma does not understand. You can disable appmenu-gtk-module in KDE.

It is a KDE issue, or at least enhancement.

In the repo nearly you can find a bunch of code to starting a fix.

If you have trouble with disabling it, write here.

**Comment by dos1** [comment]
The point it - Plasma does understand the appmenu. It implements the Ubuntu's API (com.canonical.AppMenu.Registrar), so it should work. Other implementations using appmenu's registrar that I tested work, only appmenu-gtk-module does not. I would guess that there's some minor incompatibility in those implementations.

**Comment by rilian-la-te** [comment]
appmenu-gtk-module not implements a Registrar at all. It uses MenuModel (org.gtk.Menus) API. But it monitors a Registrar only for one purpose to determine a requirement of hiding a menus. And if it sees a Registrar - it hides menus.

**Comment by rilian-la-te** [comment]
I consider it similar to #196

**Comment by rilian-la-te** [comment]
WIP fix from KDE guys (X11 only)
https://phabricator.kde.org/D10461

**Comment by rilian-la-te** [comment]
Closed as upstream, because KDE start fixing this.
