### ISSUE TITLE
The type name `Backend' could not be found

### ISSUE THREAD

**Issue by willmrbr** [rilian-la-te/vala-panel-appmenu#198]
Hello.

I was trying to install on arch linux using aur package (appmenu-gtk-module-git) with makepkg -si and I got this error.

error: The type name `Backend' could not be found internal class BackendBAMF : Backend

is there anything I can do? or I should wait for a fix? 

Thank you for your time.

**Comment by rilian-la-te** [comment]
Fixed in https://github.com/rilian-la-te/vala-panel-appmenu/commit/e097a80c8f6a4579d148ddd793963129377b802a
