### ISSUE TITLE
Not Working In Some Apps

### ISSUE THREAD

**Issue by wesleyotugo** [rilian-la-te/vala-panel-appmenu#20]
It works for thunar and all xfce related apps but not for chromium or any browser based software like visual studio code, it worked before but not now.

I am using arch linux x86

**Comment by rilian-la-te** [comment]
Try XDG_CURRENT_DESKTOP=Unity
With Firefox it is not working, about VSCode - Which toolkit it uses

**Comment by wesleyotugo** [comment]
VScode uses gtk2

**Comment by rilian-la-te** [comment]
As Firefox uses,  as Atom editor uses,  as chromium uses or uses properly?

**Comment by Defman21** [comment]
Isn't VSCode built on top of Electron or something? The only thing that it will use from GTK is a theme for native elements (those without styling, such as buttons, inputs, etc.).

**Comment by rilian-la-te** [comment]
If this is True,  appmenu will require an extension or patch (for exporting DBusMenu or GMenuModel). It works on Unity?

**Comment by Defman21** [comment]
Well Firefox uses XUL for its interface and GTK3 for styling. `firefox` package contains special patch that make global menu works.

**Comment by rilian-la-te** [comment]
Not in Arch,  AFAIK

**Comment by wesleyotugo** [comment]
XDG_CURRENT_DESKTOP=Unity does not work, tried in both vala-panel & xfce-panel

**Comment by wesleyotugo** [comment]
Seems to affect all cross-platform apps for some reason

**Comment by rilian-la-te** [comment]
Chromium must work.
![screenshot from 2016-08-24 20-52-58](https://cloud.githubusercontent.com/assets/1329638/17941619/2cd9f238-6a45-11e6-9465-159014a8ab30.png)

**Comment by rilian-la-te** [comment]
VSCode also works
![screenshot from 2016-08-24 21-37-23](https://cloud.githubusercontent.com/assets/1329638/17943185/63758c2a-6a4b-11e6-8713-6519dbdc6454.png)

**Comment by Defman21** [comment]
Offtop: what's your GTK theme? :)

**Comment by rilian-la-te** [comment]
Adapta

**Comment by wesleyotugo** [comment]
I will try again on a fresh install of arch linux

**Comment by wesleyotugo** [comment]
@rilian-la-te this plagues me 
![screenshot_20160824_214901](https://cloud.githubusercontent.com/assets/17808627/17947497/e047a7c6-6a44-11e6-83bd-b83b8a9d6edb.png)

**Comment by wesleyotugo** [comment]
This was my pc before i uninstalled vala-panel [here](https://imgur.com/a/QvfrL)

**Comment by rilian-la-te** [comment]
Chromium like XDG_CURRENT_DESKTOP + killall chromium after add menu.

**Comment by rilian-la-te** [comment]
Why are you uninstall vala-panel?

**Comment by wesleyotugo** [comment]
I tried it and still not works, is there a way i can get the log of the appmenu

**Comment by rilian-la-te** [comment]
For appmenu itself log is useless. For Unity stack - I do not know. I will post my settings here this evening.

**Comment by rilian-la-te** [comment]
Do you have libdbusmenu related packages? You can check chromium menu via
d-feet.

**Comment by wesleyotugo** [comment]
Tried on a fresh install on arch linux and still the same, yes i have all libdbusmenu related packages. GIMP uses GTK2 and works same will all other gtk2/qt applications work.

The apps refusing to work are browser based and all gtk3 applications

**Comment by rilian-la-te** [comment]
Do you read instruction part about settings.ini? Do you have this file?

**Comment by wesleyotugo** [comment]
I installed the following from AUR: 
libdbusmenu-glib-16.04.0-1-i686.pkg.tar.xz
libdbusmenu-gtk2-16.04.0-1-i686.pkg.tar.xz
libdbusmenu-gtk3-16.04.0-1-i686.pkg.tar.xz
libindicator-gtk2-12.10.1-6-i686.pkg.tar.xz
libindicator-gtk3-12.10.1-6-i686.pkg.tar.xz
python-pyparsing-2.1.8-1-any.pkg.tar.xz
libappindicator-gtk2-12.10.0-10-i686.pkg.tar.xz
libappindicator-gtk3-12.10.0-10-i686.pkg.tar.xz
libappindicator-sharp-12.10.0-10-i686.pkg.tar.xz

It now works. Seems you need to add unity-gtk and the ones i listed above as dependecies
