### ISSUE TITLE
FTBFS when building appmenu-gtk-module standalone

### ISSUE THREAD

**Issue by sunweaver** [rilian-la-te/vala-panel-appmenu#200]
The GTK&lt;X>_LIBDIR variable are unknown/unset and thus not used in the module dirs. This is my current work around:

https://anonscm.debian.org/cgit/pkg-ayatana/appmenu-gtk-module.git/diff/debian/patches/2001_unknown-gtk-libdirs.patch?id=ad140e902041fc46d525c52baaa26d4ef5385961

**Comment by rilian-la-te** [comment]
Will look for it.

**Comment by rilian-la-te** [comment]
Not a good workaround, but libdir variables are gone, you are true.

**Comment by sunweaver** [comment]
Thanks, that was quick!

**Comment by rilian-la-te** [comment]
Wait for tarball then, or generate it yourself)

**Comment by sunweaver** [comment]
On  Do 15 Feb 2018 21:47:26 CET, Konstantin wrote:

> Wait for tarball then, or generate it yourself)

maybe another beta release for vala-panel-appmenu including tarball  
for appmenu-gtk-module? 0.6.81?

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by rilian-la-te** [comment]
Will be soon, after I finished work for referenced registrar.
It will be 0.6.90 AFAIK.
