### ISSUE TITLE
vala-panel crash with gdbus error when applet is loaded.

### ISSUE THREAD

**Issue by IKRadulov** [rilian-la-te/vala-panel-appmenu#202]
I get this error when vala-panel-appmenu is loaded on vala-panel.

```
GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: GetMenus is not a valid method of interface com.canonical.AppMenu.Registrar

GDBus.Error:org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 736, in _message_cb
    (method_name, signature))
TypeError: GetMenuForWindow has multiple output values in signature so but did not return a sequence

[1]    11873 segmentation fault (core dumped)  vala-panel
```
OS: Arch Linux
WM: i3-gaps
vala-panel: Version 0.3.74
vala-panel-appmenu: Version  0.6.92.r7.g650755a
vala-panel-appmenu-registrar: 0.6.92.r7.g650755a
appmenu-gtk-module: 0.6.1.r123.g1d2f408
// All from aur pkgbuild

Happends with Gtk applications:
Tilix,Nautilus and e.g.

**Comment by rilian-la-te** [comment]
Describe problem more, please:
1. What applications opened? 
2. What Registrar used?

**Comment by rilian-la-te** [comment]
If you use a non-standard Registrar, please, show me introspection data from it.

**Comment by IKRadulov** [comment]
Sorry . Updated topic info.

**Comment by rilian-la-te** [comment]
Will look for it.

**Comment by rilian-la-te** [comment]
Do you use systemd or openrc? What dbus provider are you using? Why python exceptions?

**Comment by rilian-la-te** [comment]
I need more info.
this GetMenus is using to get DBus-activatable registrar to up.

**Comment by IKRadulov** [comment]
Systemd . Wath do you mean by dbus provider ? Idk why python .

**Comment by rilian-la-te** [comment]
Backtrace, please.

**Comment by IKRadulov** [comment]
Idk. what happend but today I can't replacate it today . Now works normal . Closing untill it happens again .
