### ISSUE TITLE
Doesn't work for xfce4-terminal ?

### ISSUE THREAD

**Issue by d4em0n** [rilian-la-te/vala-panel-appmenu#203]
no appmenu on xfce4-terminal
![image](https://user-images.githubusercontent.com/29397847/36340835-7225338a-13b2-11e8-9b42-6bdc97b495b3.png)

**Comment by d4em0n** [comment]
if follow intructions from README, also i installed appmenu-gtk-module and enable in .gtkrc.

**Comment by rilian-la-te** [comment]
Xfconf command? CMake log? Is pluma or GTK3 mousepad works?

**Comment by d4em0n** [comment]
i did the xfconf command. where is cmake log ?
mousepad works, uget doesn't work

![image](https://user-images.githubusercontent.com/29397847/36341101-0ec5c28c-13b7-11e8-851a-4a17588b4bf8.png)

**Comment by d4em0n** [comment]
is my mouspad using gtk2 ?
```
$ ldd $(which mousepad) | grep gtk
        libgtksourceview-2.0.so.0 => /usr/lib/libgtksourceview-2.0.so.0 (0x00007fd077427000)
        libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007fd076de5000)
```

**Comment by rilian-la-te** [comment]
Uget is using gtk3? What about atril and pluma (or some other MATE apps)?

**Comment by d4em0n** [comment]
i check with ldd, uget and xfce4-terminal using gtk3
pluma doesn't works.

**Comment by rilian-la-te** [comment]
Uget is using gtk3? What about atril and pluma (or some other MATE apps)?

**Comment by rilian-la-te** [comment]
Strange. Gtk2 works, gtk3 is not?

**Comment by rilian-la-te** [comment]
GTK3 is built with Wayland support?

**Comment by rilian-la-te** [comment]
And locate appmenu-gtk-module, please.

**Comment by rilian-la-te** [comment]
Do you created settings.ini? Or a bash snippet is used somewhere ?

**Comment by d4em0n** [comment]
```
/home/asd/vala-panel-appmenu/RPM/SPECS/appmenu-gtk-module.spec
/home/asd/vala-panel-appmenu/rpm/appmenu-gtk-module.spec.in
/home/asd/vala-panel-appmenu/subprojects/appmenu-gtk-module
> snip <
/home/asd/vala-panel-appmenu-0.6.80/subprojects/appmenu-gtk-module/tests/demos/menusource.c
/home/asd/vala-panel-appmenu-0.6.80/subprojects/appmenu-gtk-module/tests/demos/menusource.h
/home/asd/vala-panel-appmenu-0.6.80/subprojects/appmenu-gtk-module/tests/demos/test-radio.c
/home/asd/vala-panel-appmenu-0.6.80/subprojects/appmenu-gtk-module/tests/demos/unity-gtk-menu-tester.c
/usr/lib/systemd/user/appmenu-gtk-module.service
/usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libappmenu-gtk-module.so
/usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libappmenu-gtk-module.so
/usr/share/doc/appmenu-gtk-module-common
/usr/share/doc/appmenu-gtk-module-common/changelog.Debian.gz
/usr/share/doc/appmenu-gtk-module-common/copyright
/usr/share/glib-2.0/schemas/org.valapanel.appmenu-gtk-module.gschema.xml
/var/cache/apt/archives/appmenu-gtk-module-common_0.6.1-1_all.deb
/var/lib/dpkg/info/appmenu-gtk-module-common.list
/var/lib/dpkg/info/appmenu-gtk-module-common.md5sums
```

**Comment by d4em0n** [comment]
i created settings.ini, and settings in .profile
```
if [ -n "$GTK_MODULES" ]; then
    GTK_MODULES="${GTK_MODULES}:appmenu-gtk-module"
else
    GTK_MODULES="appmenu-gtk-module"
fi

if [ -z "$UBUNTU_MENUPROXY" ]; then
    UBUNTU_MENUPROXY=1
fi

export GTK_MODULES
export UBUNTU_MENUPROXY
```

**Comment by rilian-la-te** [comment]
Do you using 0.6.80 or latest master?

What system are you using?
Version, package versions?
Do xfconf snippet was used (from appmenu-gtk-module's Readme)?

**Comment by rilian-la-te** [comment]
If it is not, what DE are you using (especially settings-daemon)?

**Comment by rilian-la-te** [comment]
Bamfdaemon is running?

**Comment by d4em0n** [comment]
i'm using latest master. my OS kali linux and my DE is xfce 4.12.
yes, i did xfconf command
bamfdaemon running.

**Comment by rilian-la-te** [comment]
And then gtk3 apps not working, but gtk2 works?

**Comment by rilian-la-te** [comment]
What commands exactly are you did?

**Comment by d4em0n** [comment]
pluma works with command `pluma --gtk-module=appmenu-gtk-module`

**Comment by d4em0n** [comment]
is appmenu-gtk-module gtk3 not loaded ?

**Comment by rilian-la-te** [comment]
I know. Which commands do you run to xfconf?

**Comment by rilian-la-te** [comment]
AFAIK, yes

**Comment by rilian-la-te** [comment]
So, you have did something wrong, maybe, or my instructions is not full.

**Comment by d4em0n** [comment]
i'm following instructions in README
```
xfconf-query -c xsettings -p /Gtk/ShellShowsMenubar -n -t bool -s true
xfconf-query -c xsettings -p /Gtk/ShellShowsAppmenu -n -t bool -s true
```

**Comment by rilian-la-te** [comment]
And latest from appmenu-gtk-module's one?

**Comment by rilian-la-te** [comment]
Look now to its Readme and do Xfce section.

**Comment by d4em0n** [comment]
now it's works, using command `xfconf-query -c xsettings -p /Gtk/Modules -n -t string -s "appmenu-gtk-module"`.

**Comment by d4em0n** [comment]
thanks very much for fast response
