### ISSUE TITLE
Menus not opened or rolled over in top few pixel rows of screen

### ISSUE THREAD

**Issue by mdmayfield** [rilian-la-te/vala-panel-appmenu#208]
Thank you very much to the developers for your work on this.

On the MATE desktop at least, when I move the cursor all the way up to the very top of the screen, I can't open the global menus. I need to move the cursor at least a few pixels down from the top, before a click will register and cause the menu to open.

This also makes it more difficult to roll over between different menus (i.e. File, Edit, etc.) because whenever the cursor moves too far toward the top of the screen, the menus no longer "see" it.

This defeats a large part of the purpose of the global menu for my use case, which is to make it physically easier to access the menus (thanks to Fitt's Law).

Is this issue appropriate to raise in this project, or is it something that would have to be addressed in MATE-Panel or elsewhere?

**Comment by rilian-la-te** [comment]
Can you show a video? I does not full understand a problem.

This project just uses GtkMenuBar to show a menus. But I will look for it.

And try vala-panel. If on vala-panel issue persists, then it is 70% my issue, 30% gtk. If it is not, this is MATE - only.

**Comment by mdmayfield** [comment]
Sure, here is a 15 second video: https://photos.google.com/share/AF1QipPo-BS_gP_uWyHz9js10FNJpZiDr9DBpujMsbPy5QLSVYmuU87dAPwIXOeOLdJa1A/photo/AF1QipP5tVZxYnS4hv1LbopRkeR_0ENcM_Gp5EyRvl8R?key=TS1VM20zZnZhQlhSVmd2N0R4S2Q3UEFzSVU5UThn

I have not yet tried vala-panel, but I just noticed that the indicator icons on the MATE panel show this same behavior, so I'm starting to think this is an issue with the panel's margins, not the menu plugin. I will open an issue in mate-desktop.

**Comment by mdmayfield** [comment]
Ah nevermind - checking again, only the menu does this, not the indicator icons. I will investigate vala-panel next.

**Comment by mdmayfield** [comment]
Yes, the menus behave as desired in vala-panel. They still work even when the mouse cursor is in the top row of pixels, so this is a mate-panel issue. Thanks!

**Comment by rilian-la-te** [comment]
No, this can be mate-only issue of my applet.

**Comment by rilian-la-te** [comment]
Please, test another menubar applet in mate-panel check a bug.

**Comment by mdmayfield** [comment]
Ah, interesting - the GNOME 2 style menus work as expected:

https://photos.google.com/share/AF1QipMoCZ32bWheolgsLb4ly5wAEhZxMziqp8t-ZwCbLd_lIMzvHEDAgJaB3XvzAp2UTA/photo/AF1QipN4-4juX1IU_AV0PRUFRN-sEp9_pgTDRwcy8PGy?key=NHBocFZHa3dQMV9aYWtwdXhqM3JrZ2dEWUt0RW5R

**Comment by rilian-la-te** [comment]
I need to look for it on mate-panel. You need to test in-process and out-of-process applets, both appmenu and gnome 2 style.

**Comment by mdmayfield** [comment]
I rolled back my test Ubuntu MATE 18.04 VM to a snapshot (from almost two months ago in this case) and the issue is not present there!

Doing apt upgrade again to current, and will test the different menus as soon as that is done.

**Comment by mdmayfield** [comment]
When I upgraded at first, a number of packages were held back including mate-panel and vala-panel-appmenu. Before re-installing those packages, the issue was not present.

After re-installing all so that the system is fully up to date, the issue returns. Here are the results of more testing and comparing with the other menu - first, old system version, then after upgrade.

https://photos.google.com/share/AF1QipPNnf1mwbh922t7k4racUFhYpDNH1tzp3-2tq-KrVbWtp4HLH-xBIp0kI8YIpx4uA/photo/AF1QipPm29N8syFseGTPpeizSsjxu8feGfxdIMlMasRQ?key=UEdBdGlfUUEzRlliRzVfN2pHNi03dE00VFh1MDhR

**Comment by rilian-la-te** [comment]
Versions of vala-panel-appmenu, please. And try another gtk theme and another out of process applet, like sntray.

**Comment by rilian-la-te** [comment]
I need two versions. Old and new.

**Comment by mdmayfield** [comment]
Thanks for clarifying. Here is some more info:

* Changing gtk theme does not affect the issue
  - working system still works; non-working system still doesn't work
  - tried with Ambiant/Radiant-MATE, BlueMenta, High Contrast, Green-Submarine, etc.
* The package versions appear identical
  - Output of `apt show vala-panel-*` from **new** version 2018-02-22 (not working): https://pastebin.com/GMcL2qSq
  - Output of `apt show vala-panel-*` from **old** version 2017-12-30 (working): https://pastebin.com/zNt73ema
  - These files match; is there a way to obtain more vala-panel-appmenu version info?


sntray appears to be only for xfce4-panel and vala-panel, but after [some research](https://github.com/mate-desktop/mate-indicator-applet/blob/master/src/applet-main.c#L113), it seems that the MATE Indicator Applet is also out-of-process. It does *not* show the issue; it behaves correctly.

I have another daily live ISO dated 2018-02-07, and upon booting it, the issue is still present. An older ISO dated 2017-12-28 does not show the issue.

FWIW, I noticed that the MATE team seems to have made some theme tweaks - on the versions I have with the menu issue, the default pointer theme is Breeze, while on the versions I have that work properly, the default pointer theme is DMZ-White.

**Comment by mdmayfield** [comment]
Closed by mistake

**Comment by mdmayfield** [comment]
I tested my own theme (forked from Ambiant-MATE on 2018-01-19) and it does not affect the issue (systems working still work; systems with issue still show the issue).

This is also an indication that the issue was introduced later than 2018-01-19 but before 2018-02-18.

**Comment by rilian-la-te** [comment]
Sntray can be used in MATE.
vala-panel-appmenu is too old. Try 0.6.92. 
If issue still persists, write here.

**Comment by mdmayfield** [comment]
Thank you for all your time helping deal with this.

I cloned latest git source for vala-panel-appmenu and logged out/in, but do not see a difference. However I don't know how to be 100% sure that my system is using the version I compiled and installed from source or not.

I did `sudo apt remove vala-panel-appmenu` and it said it was not installed.

**Comment by rilian-la-te** [comment]
You can check it by using a right click. If this is a Preferences option, this is 0.7 series after 0.6.80.

**Comment by rilian-la-te** [comment]
I will try it on mate-panel tomorrow. If issue exists, it is my issue.

**Comment by mdmayfield** [comment]
I got the 0.7 version installed (was missing some dependencies earlier so it wasn't updating). Confirmed by Preferences option:
![image](https://user-images.githubusercontent.com/26154258/36638018-194cdc48-19ae-11e8-99f9-97c211633af7.png)
The margins are still incorrect such that the menus don't extend to the top of the screen.

Thanks again for your help!

**Comment by mdmayfield** [comment]
Hello Konstantin,

Thank you for your work on this issue. It has improved the situation significantly, so that the menus roll over correctly in most of the top few pixels of the screen.

Unfortunately, although it does now work to *open* a menu on the the very topmost pixel row of the screen, the menus still do not work to roll over with the mouse at the very top.

Incidentally, I notice that you recently added the ability to roll over between the application name and the other menus - that is very nice to see!

If there is any way to resolve the issue where the mouse cannot roll over between menus on the very top pixel, I'm sure I and other users would be very grateful.

Thanks again,

Matt

**Comment by rilian-la-te** [comment]
Show me a video, please.

**Comment by rilian-la-te** [comment]
With latest version.

**Comment by mdmayfield** [comment]
Sure, here is a video:https://photos.google.com/share/AF1QipMxBX7KDY5r--HjZ5YpJAcEEM7rHCoLa4Ra1T2Vus2VCJMyoiGDYleNWjfbuiOSwA/photo/AF1QipMW_by66CnCQK9wxQKiTMMJxipp-_cLKafm7ieK?key=MGJDZUI0NG5HRDFKNXBKSWFwU3VjSWt0OWNzTDhn

I made the first video with the 0.7 development currently included with Ubuntu-MATE, then also compiled latest vala-panel-appmenu from Git source to verify behavior was the same, and it was: https://photos.google.com/share/AF1QipMxBX7KDY5r--HjZ5YpJAcEEM7rHCoLa4Ra1T2Vus2VCJMyoiGDYleNWjfbuiOSwA/photo/AF1QipNVLEgnCaG5H82t71K46m7NZiMzDQWQkvPaJCWN?key=MGJDZUI0NG5HRDFKNXBKSWFwU3VjSWt0OWNzTDhn

Thank you very much for all your work.

**Comment by mdmayfield** [comment]
It appears that the mate-indicator-applet does not roll over in the top pixel, either. This makes me suspect it is an issue with the mate-panel rather than vala-panel-appmenu; do you agree?

**Comment by rilian-la-te** [comment]
And what about Mate menubar, especially out-of-process (I mean applications place system thing)?

**Comment by mdmayfield** [comment]
Yes, same exact behavior in traditional mate-menus: top pixel row works to open menu, but not to roll over. Moving down even 1 pixel allows rollover.

**Comment by rilian-la-te** [comment]
So, I think this is mate-panel issue then.

**Comment by mdmayfield** [comment]
OK, thank you! I will open an issue there.

**Comment by rilian-la-te** [comment]
Or maybe a GtkMenubar, if vala-panel also has it.
