### ISSUE TITLE
Available as a plasmoid for KDE?

### ISSUE THREAD

**Issue by ChrisP4** [rilian-la-te/vala-panel-appmenu#209]
Hey, I'm not sure what label should be used (enhancement?), and I don't know if this is even possible, but could vala-panel-appmenu be a plasmoid or somehow work on KDE perhaps with latte dock? 

Could that happen?

Thanks :)

**Comment by rilian-la-te** [comment]
Use KDE's builtin appmenu with gmenu proxy and my appmenu-gtk-module with JAyatana (it will cover all appmenu cases ) . I do not want to implement builtin functionality, especially in Qt, because appmenu in Qt needs much more work.
If you want you use builtin menu, I can provide links.

**Comment by ChrisP4** [comment]
Wow, thanks for the amazingly fast reply. I'd like to use KDE's builtin appmenu,
I found this: https://phabricator.kde.org/D10461 on phabricator but unfortunately I'm not familiar with phabricator and don't understand how to go about installing the gmenu proxy.

Thanks!

**Comment by rilian-la-te** [comment]
You absolutely need this and appmenu-gtk-module.
