### ISSUE TITLE
Bar between application name and menus in MATE applet

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#215]
Thank you for implementing menu rollover from the application name to the menus. I have noticed there is a bar between the application name and the menus. Can it be removed please?

![bar between application name and menus](https://user-images.githubusercontent.com/304639/36904317-4e90213e-1e28-11e8-840d-9b6f03253797.png)

This was tested on Ubuntu MATE 18.04 daily and vala-panel-appmenu 0.6.92 with appmenu-gtk-module 0.6.92.

**Comment by rilian-la-te** [comment]
Will look for it. I know about it.

**Comment by rilian-la-te** [comment]
try now. If fixed, please close.

**Comment by rilian-la-te** [comment]
May create a setting then? to show a bar to someone who likes it?

**Comment by flexiondotorg** [comment]
@rilian-la-te Thanks for the fix, that is so much better :smile:
