### ISSUE TITLE
Buggy applications (VLC 3.0.1) crashes Importer.

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#217]
If I roll over the global menu for VLC a few times it causes the MATE applet to crash. This only seems to affect VLC and it can be reproduced reliably by rolling over the VLC global menu left to right a few times. I've not encountered this issue with the 0.5.3 release. I'm not sure when this issue started but it has been present since at least 0.6.80.

I've also tested OSB Studio and kdenlive, both Qt applications like VLC, and they do not exhibit the problem.

I'm running Ubuntu MATE 18.04 (daily), vala-panel-appmenu 0.62.92 and appmenu-gtk-module 0.6.92. VLC is 3.0.1 and appmenu-qt is 0.2.7+14.04.20140305-0ubuntu2.

**Comment by rilian-la-te** [comment]
Some other symptoms like incorrect menu exists?
About VLC - it sends highnly incorrect menu (many hidden separators).

**Comment by rilian-la-te** [comment]
And I cannot reproduce it with master on ArchLinux. I need exact instruction

**Comment by flexiondotorg** [comment]
I've made a short video clip showing how I made it crash.

  * http://imgur.com/a/t6iSF

**Comment by rilian-la-te** [comment]
@flexiondotorg can you get a backtrace of crash of appmenu-mate?

**Comment by rilian-la-te** [comment]
I still cannot reproduce it, but I have VLC 2.2.8.

**Comment by rilian-la-te** [comment]
Reproduced it with 3.0.1 (but menus is duplicated).
Will look for it, know VLC bug.

**Comment by rilian-la-te** [comment]
New VLC is sending 2 or 3 visible separators together. We need to ignore unneeded separators.

**Comment by rilian-la-te** [comment]
But regardless of source, I will fix it ASAP, probably today-tomorrow.

**Comment by flexiondotorg** [comment]
I'm going to test your Firefox fix later today. If you drop a fix for VLC I can test today.

**Comment by rilian-la-te** [comment]
Thanks. But I am not sure than I will can drop a fix today.

**Comment by flexiondotorg** [comment]
No problem. I'm ready when you are 😀

**Comment by rilian-la-te** [comment]
Waiting for test.

**Comment by flexiondotorg** [comment]
I'm travelling today bit was able to test briefly before I left. Sadly no change, rolling over the menus was still able to crash the applet.

**Comment by rilian-la-te** [comment]
Ok, will try to reproduce it again (but I cannot do it with vlc3 now)

**Comment by rilian-la-te** [comment]
Cannot reproduce it with VLC 3.0.1 on ArchLinux. Can you provide a backtrace?

**Comment by rilian-la-te** [comment]
I need to fix (it is ubuntu-only now, I cannot reproduce it on Arch anymore after last commit):
1. Exact way to reproduce (as most simple case)
2. Backtrace of crash (from gdb or strace, with debuginfo installed)
3. Is it happen on vala-panel (vala-panel is primary target and easiest to test)

**Comment by flexiondotorg** [comment]
It turns out I installed an unpatched version of the build. I've tested the patch this morning and it is working great. Thank you!
