### ISSUE TITLE
Failed to install to ubuntu budgie 17.10

### ISSUE THREAD

**Issue by cgiannakidis70** [rilian-la-te/vala-panel-appmenu#218]
Hi.
Compiling master  branch with git as readme says I have this output: 

 cmake .. -DENABLE_XFCE=OFF -DENABLE_MATE=OFF -DENABLE_VALAPANEL=OFF -DENABLE_BUDGIE=ON -DENABLE_UNITY_GTK_MODULE=OFF -DCMAKE_INSTALL_PREFIX_PATH=/usr 
-- Looking for RPMTools... - found rpmuild is /usr/bin/rpmbuild
-- RPMTools:: Using RPM_ROOTDIR=/home/christoforos/vala-panel-appmenu/build/RPM
-- Configuring spec file </home/christoforos/vala-panel-appmenu/rpm/vala-panel-appmenu.spec.in> --> </home/christoforos/vala-panel-appmenu/build/RPM/SPECS/vala-panel-appmenu.spec>
-- RPMTools:: Using RPM_ROOTDIR=/home/christoforos/vala-panel-appmenu/build/RPM
-- Configuring spec file </home/christoforos/vala-panel-appmenu/rpm/appmenu-gtk-module.spec.in> --> </home/christoforos/vala-panel-appmenu/build/RPM/SPECS/appmenu-gtk-module.spec>
-- RPMTools:: Using RPM_ROOTDIR=/home/christoforos/vala-panel-appmenu/build/RPM
-- Configuring spec file </home/christoforos/vala-panel-appmenu/rpm/java-appmenu.spec.in> --> </home/christoforos/vala-panel-appmenu/build/RPM/SPECS/java-appmenu.spec>
-- Found GTK: /usr/lib/x86_64-linux-gnu/libgdk-3.so;/usr/lib/x86_64-linux-gnu/libgtk-3.so (found suitable version "3.22.25", minimum required is "3.22") found components:  GDK GTK X11 WAYLAND 
Using libwnck, will be X-dependent
-- Checking for module 'libmatepanelapplet-4.0'
--   Found libmatepanelapplet-4.0, version 1.18.4
-- Checking for module 'vala-panel'
--   Found vala-panel, version 0.3.65
-- Checking for module 'budgie-1.0'
--   Found budgie-1.0, version 2
Using 0.4 ValaPanelApplet api
-- Found GTK: /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so;/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so (found suitable version "2.24.31", minimum required is "2.24") found components:  GDK GTK X11 
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- Checking for module 'systemd'
--   Found systemd, version 234
-- Could NOT find Java (missing: Java_JAVAC_EXECUTABLE Java_JAVAH_EXECUTABLE Java_JAVADOC_EXECUTABLE) (found version "1.8.0.151")
-- Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
-- Checking for module 'xkbcommon'
--   Found xkbcommon, version 0.7.1
-- Checking for module 'dbusmenu-glib-0.4>=16.04.0'
--   Found dbusmenu-glib-0.4, version 16.04.0
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- Configuring done
-- Generating done
-- Build files have been written to: /home/christoforos/vala-panel-appmenu/build

I continue with make and make install but nothing is being installed.
what am I doing wrong?

**Comment by rilian-la-te** [comment]
Make and make install logs, please.

**Comment by rilian-la-te** [comment]
And set correct CMAKE_INSTALL_PREFIX, as in distro budgie. It noted in README.

**Comment by rilian-la-te** [comment]
You misspelled prefix, it should written as I wrote in previous message

**Comment by cgiannakidis70** [comment]
OK.You are right.
I am sorry .
