### ISSUE TITLE
Build problem (again) Ubuntu 16.04.4

### ISSUE THREAD

**Issue by re23071998** [rilian-la-te/vala-panel-appmenu#219]
user1@linux-x86:~/vala-panel-appmenu/build$ cmake -DENABLE_XFCE=ON -DENABLE_JAYATANA=ON -DENABLE_APPMENU_GTK_MODULE=ON -DMAKE_BOLD_APPNAME=ON -DCMAKE_INSTALL_PREFIX=/usr ..
-- Looking for RPMTools... - found rpmuild is /usr/bin/rpmbuild
-- RPMTools:: Using RPM_ROOTDIR=/home/user1/vala-panel-appmenu/build/RPM
-- Configuring spec file </home/user1/vala-panel-appmenu/rpm/vala-panel-appmenu.spec.in> --> </home/user1/vala-panel-appmenu/build/RPM/SPECS/vala-panel-appmenu.spec>
-- RPMTools:: Using RPM_ROOTDIR=/home/user1/vala-panel-appmenu/build/RPM
-- Configuring spec file </home/user1/vala-panel-appmenu/rpm/appmenu-gtk-module.spec.in> --> </home/user1/vala-panel-appmenu/build/RPM/SPECS/appmenu-gtk-module.spec>
-- RPMTools:: Using RPM_ROOTDIR=/home/user1/vala-panel-appmenu/build/RPM
-- Configuring spec file </home/user1/vala-panel-appmenu/rpm/java-appmenu.spec.in> --> </home/user1/vala-panel-appmenu/build/RPM/SPECS/java-appmenu.spec>
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Vala: Found unsuitable version "0.30.1", but required is at
  least "0.34" (found /usr/bin/valac)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindVala.cmake:60 (find_package_handle_standard_args)
  CMakeLists.txt:41 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/user1/vala-panel-appmenu/build/CMakeFiles/CMakeOutput.log".

**Comment by rilian-la-te** [comment]
You have too low Vala version. If you sure to try new vala-panel-appmenu with this Vala, you can change requirement in CMakeLists.txt. If you do not want to test unsupported versions - install new Vala from any backport PPA (do not know any, I am on Arch). Wontfix this.

**Comment by re23071998** [comment]
which release works with 16.04?

**Comment by rilian-la-te** [comment]
Which DE are you need?

**Comment by re23071998** [comment]
xfce4

**Comment by re23071998** [comment]
and openbox

**Comment by rilian-la-te** [comment]
Which version of xfce4-panel are you have?

**Comment by re23071998** [comment]
xfce4-panel 4.12.0

**Comment by rilian-la-te** [comment]
You can try 0.5 series (0.5.6 is latest AFAIK).
But it is EOL now.
