### ISSUE TITLE
Doesn't work with Qt5 apps

### ISSUE THREAD

**Issue by qarkai** [rilian-la-te/vala-panel-appmenu#22]
It works for KDevelop 4 but not for KDevelop 5 (also Kate, SMPlayer, etc.).
Also doesn't work for Google Chrome.
Also there is no icons in menu for GTK apps. Though there are icons for Qt4 apps (KDevelop 4).
OS: ArchLinux x64
DE: XFCE

**Comment by wesleyotugo** [comment]
Try installing from AUR ["appmenu-qt"](https://aur.archlinux.org/packages/appmenu-qt/) and ["appmenu-qt5-bzr"](https://aur.archlinux.org/packages/appmenu-qt5-bzr/) 

Then logout and login

**Comment by qarkai** [comment]
Already installed. I did everything from https://github.com/rilian-la-te/vala-panel-appmenu#installation-after-building of course.

**Comment by wesleyotugo** [comment]
If there is no icon in gtk menus, you can change that in XFCE settings manager.

[Checkout this issue to get it working with chrome](https://github.com/rilian-la-te/vala-panel-appmenu/issues/23)

There is already an ongoing issue in KDE development about KDE software and appmenu possibilities but due to recent changes in Gnome. See [here](https://forum.kde.org/viewtopic.php?f=285&t=125058) and [here](https://forum.kde.org/viewtopic.php?f=285&t=125058) and [here](https://bugs.kde.org/show_bug.cgi?id=341071) .

**Comment by qarkai** [comment]
Thanks for your help with Chrome! I think libappindicator, libappindicator-gtk3, libappindicator-sharp should be in (optional) dependencies of vala-panel-appmenu-xfce-git package. And appmenu-qt5 package name in dependencies should be fixed.

> If there is no icon in gtk menus, you can change that in XFCE settings manager.

It's odd that I have menu icons in global menu for GTK apps when I use TopMenu instead of Appmenu.

> See here and here and here

BTW you wrote https://forum.kde.org/viewtopic.php?f=285&t=125058 link twice.

**Comment by rilian-la-te** [comment]
About icons - unity-gtk-module does not share menu icons.  About QT5 - you are right

**Comment by wesleyotugo** [comment]
@qarkai Sorry about that, but i know the appmenu support is currently in work. No immediate success but most likely something will done by December.

@rilian-la-te Created a pull for the dependencies issue in PKGBUILD

**Comment by dontpanic92** [comment]
Hi,

After a recent update of KDE Applications ( or Qt? I'm not sure),  Qt5 apps can automatically support the appmenu feature. But when I try to show a submenu from the global menu, the whole DE is stuck. I'm using XFCE and Archlinux with Qt version 5.7.1 / KDE Applicatoin version 16.11.

Thanks

**Comment by rilian-la-te** [comment]
Will test it:)

**Comment by DrWesleyDekstar** [comment]
Lo and behold, my prediction comes true

**Comment by rilian-la-te** [comment]
> Lo and behold, my prediction comes true

What are you means?

**Comment by DrWesleyDekstar** [comment]
This comment https://github.com/rilian-la-te/vala-panel-appmenu/issues/22#issuecomment-242987735

**Comment by rilian-la-te** [comment]
> I mean i predicted the addition of appmenu to KDE. This is the comment #22 (comment)

This was in Qt 5.7 roadmap)) But not working submenus is not good:( So, it must be investigated...

**Comment by rilian-la-te** [comment]
Fixed for me
