### ISSUE TITLE
Some non default apps of ubuntu budgie 17.10 have both global and local menus.

### ISSUE THREAD

**Issue by cgiannakidis70** [rilian-la-te/vala-panel-appmenu#220]
hello .
As the title says.
I don't know if this is an issue but in "mousepad", " gnome-terminal" "synaptic-package-manager", "screenshot" etc. there are both menus.See below in the screeshot:

![screenshot from 2018-03-11 23-39-50](https://user-images.githubusercontent.com/33185625/37258857-f7beee06-2586-11e8-8a87-40d3b3c9d3da.png)

**Comment by rilian-la-te** [comment]
You have a registrar? And you are set an gtk-shell-shows-menubar as in appmenu-gtk-module's [README](subprojects/appmenu-gtk-module/README.md) described?

**Comment by rilian-la-te** [comment]
Thanks for pointing. I will add budgie to README.

**Comment by rilian-la-te** [comment]
see updated README

**Comment by cgiannakidis70** [comment]
Hi.I followed the instructions there, and now there is global only menu except  in those apps
"synaptic package manager", "Glade" "Eric IDE".

**Comment by rilian-la-te** [comment]
Synaptic with sudo?
Glade is not supported.
Eric is Qt4 or Qt5?

**Comment by cgiannakidis70** [comment]
You are right about synaptic because is with  the  use of sudo.
About Eric  is a Qt5 app.

**Comment by rilian-la-te** [comment]
1. Sudo is also not supported.

Eric is not working for me, strange. I will look in its source...

**Comment by rilian-la-te** [comment]
Eric do not export a menu now, you should report about it in eric bugtracker. Closing this.
