### ISSUE TITLE
Plugin crash when rapidly switching tabs in Kate text editor.

### ISSUE THREAD

**Issue by snippins** [rilian-la-te/vala-panel-appmenu#223]
Use latest git, happen on xfce4-panel.

GDB Logs:
[1521197930_gdb_appmenu_2.log](https://github.com/rilian-la-te/vala-panel-appmenu/files/1818941/1521197930_gdb_appmenu_2.log)

**Comment by rilian-la-te** [comment]
Your gdb logs is unusable. Install debug packages, please.

**Comment by snippins** [comment]
Install the debug package seems does not solve the logging problem, but at least stdout have this interesting line:

`(wrapper-2.0:22128): Gtk-CRITICAL **: gtk_label_set_text_with_mnemonic: assertion 'str != NULL' failed
`

**Comment by rilian-la-te** [comment]
Do it fixed by latest commit?

**Comment by snippins** [comment]
Thank you, it's fixed
