### ISSUE TITLE
Can't get rid of duplicates

### ISSUE THREAD

**Issue by bleamb** [rilian-la-te/vala-panel-appmenu#226]
I know similar issues have been posted before, but I am still having issues.

I am using XFCE and installed from AUR. I have the menubar showing up in both the panel and the window, despite using the two xfconf commands given in the readme. What else can I do?

**Comment by rilian-la-te** [comment]
Appmenu-gtk-module's readme is finished?

**Comment by rilian-la-te** [comment]
You should use recipes from it.
2. Do you have vala-panel-appmenu-registrar installed?

**Comment by bleamb** [comment]
I didn't have vala-panel-appmenu-registrar installed. Installing it fixed the problem immediately. Thanks! Not sure why this package wasn't included in the dependencies when I installed from AUR though...

**Comment by rilian-la-te** [comment]
It is in optional)
