### ISSUE TITLE
Duplicate app name in compact mode

### ISSUE THREAD

**Issue by Addrael** [rilian-la-te/vala-panel-appmenu#228]
Would be great if the menu in compact mode would behave like standard mode for gnome applications that only have one menu, because right now the app name is displayed in the panel and then again in the cascading menu although there is only one submenu:
![compact_menu](https://user-images.githubusercontent.com/16519548/38064947-0218388a-3301-11e8-9379-6facd7b3aa79.png)
Meaning it would be better if displayed like this:
![standard-menu](https://user-images.githubusercontent.com/16519548/38065033-68cb49a0-3301-11e8-856a-f8e5c4843c06.png)

**Comment by rilian-la-te** [comment]
But what about apps with both appmenu and menubar?

**Comment by Addrael** [comment]
In that case there's going to be multiple submenus anyway, so it could be left as is. If possible, the submenu could be renamed 'Appmenu' instead of the app name to avoid duplication.

**Comment by rilian-la-te** [comment]
Maybe. But for now MenuModels does not know about mode.

**Comment by Addrael** [comment]
I'm not familiar with Gtk APIs. What is the resulting problem?

**Comment by rilian-la-te** [comment]
This is not GTK API, this is my architecture decision - MenuWidget does not know, which MenuModels we send to it.

**Comment by Addrael** [comment]
Oh alright. Wouldn't it be possible to determine if there is only one submenu? Then there'd be no need to determine if only appmenu is being used. And as I said, if both appmenu and menubar are being used, it could be left as is, without any changes. Or am I misunderstanding something?

**Comment by rilian-la-te** [comment]
But we need to change incoming appmenu then. So, I will think about it, but it is low priority for me.

**Comment by Addrael** [comment]
Of course. It's just a minor inconvenience anyway.
