### ISSUE TITLE
XFCE AppMenu Crashes w/ VLC 2.x

### ISSUE THREAD

**Issue by gideonguillen** [rilian-la-te/vala-panel-appmenu#229]
Using the XFCE AppMenu Plugin, using the latest the master branch 04570b2f55d2adf0b45fcbaf5c0cf660e2ada5a1.

The xfce appemnu crashes when I switch from VLC to another application then switch back to VLC. I've included the back trace from the crash.
[vlc-crash-backtrace.txt](https://github.com/rilian-la-te/vala-panel-appmenu/files/1858913/vlc-crash-backtrace.txt)

**Comment by rilian-la-te** [comment]
1. To what other application? Can you share its name?
2. How I can reproduce it with vala-panel?
3. What VLC version?

VLC is evil to appmenu, because its menu it full of useless separators.

**Comment by rilian-la-te** [comment]
Cannot confirm it with latest ArchLinux (VLC 3.0)

**Comment by gideonguillen** [comment]
It's VLC 2.2.6-6 on Xubuntu 17.10.

To reproduce it, I just launch VLC, switch to another windows then switch back to the VLC window, then appmenu crashes.

**Comment by rilian-la-te** [comment]
Any window?

**Comment by gideonguillen** [comment]
Any other application window.

**Comment by rilian-la-te** [comment]
It is strange. Will look for it.

**Comment by rilian-la-te** [comment]
Cannot confirm with downgraded VLC 2.2.6 on ArchLinux.

**Comment by rilian-la-te** [comment]
Can you test it with another panels?

**Comment by gideonguillen** [comment]
I'll try to test it over the weekend. Can't switch my daily driver to another desktop environment. I'll spin another VM during the weekend and use vala-panel on that. But for now I can only test it on xubuntu/xfce.

**Comment by rilian-la-te** [comment]
Ok. But I cannot confirm this, it is strange. Maybe an Ubuntu bug and I need to test it on Ubuntu VM?

**Comment by rilian-la-te** [comment]
Try this. If this not prevent a crash, I wll revert it.

**Comment by gideonguillen** [comment]
Hi. Looks like 96321c276c4eabbc5b51aa7b7f9a815d95cc216d fixed the xfce4 appmenu crash.

**Comment by rilian-la-te** [comment]
Close then)
