### ISSUE TITLE
Not working with Chromium

### ISSUE THREAD

**Issue by Snisser** [rilian-la-te/vala-panel-appmenu#23]
Hey, i'm on Arch and i set it up exactly as in the description but it just won't work for application like chromium/firefox. On xfce4-terminal or thunar it works just fine, but i'm not getting it to work with browsers or something like that. Neither does it work for Gparted. I'm sure for some other programs it won't work either.

**Comment by wesleyotugo** [comment]
Just install from [AUR "libappindicator"](https://aur.archlinux.org/packages/libappindicator-gtk2/) [and "libappindicator-gtk3"](https://aur.archlinux.org/packages/libappindicator-gtk3/) [and "libappindicator-sharp"](https://aur.archlinux.org/packages/libappindicator-sharp/)

**Comment by Snisser** [comment]
You are seriously my hero! Thank you so much and for your patience for explaining this all to me.
 Everything works now, i think this thread can be closed.
