### ISSUE TITLE
Option to remove the black border around the plugin

### ISSUE THREAD

**Issue by Dr-Dd** [rilian-la-te/vala-panel-appmenu#232]
As you can see in the picture, for people who like to use transparent panels it's kind of annoying.

A minor problem, but is there any way to remove it?

![appmenu-blackborder](https://user-images.githubusercontent.com/37450282/39405987-ce1a8ec6-4baf-11e8-835e-8ea791dbf986.png)

**Comment by rilian-la-te** [comment]
Theme, DE, version?

**Comment by Dr-Dd** [comment]
Sorry, i totally forgot.

I'm using OSX-Arc-Shadow (https://github.com/LinxGem33/X-Arc-Darker) on xfce4, running manjaro. 
Version is 0.6.94

**Comment by rilian-la-te** [comment]
OK. What about another themes, do they have this issue?

**Comment by Dr-Dd** [comment]
No change at all, tried changing both compiz's windows decoration theme and xfce theme, same effect.

I also tried changing from compiz to the default xfwm4, the box still remains.

**Comment by rilian-la-te** [comment]
What about gtk3 theme? Plugin uses gtk3, not gtk2.

**Comment by rilian-la-te** [comment]
Yes, just add  .-vala-panel-appmenu-core as class.
