### ISSUE TITLE
How to make appmenu transparent  like panel?

### ISSUE THREAD

**Issue by PsykeDady** [rilian-la-te/vala-panel-appmenu#233]
if I have a transparent panel, the plugin is not.
how to make it transparent?
![schermata a 2018-05-03 21-26-28](https://user-images.githubusercontent.com/27916449/39598388-adf6fc44-4f18-11e8-8a23-e53d90c1a58a.png)

**Comment by rilian-la-te** [comment]
What panel are you using?

**Comment by PsykeDady** [comment]
xfce4-panel, but i've already tested on mate-panel and vala-panel also. Same result

**Comment by rilian-la-te** [comment]
vala-panel should work. Please, post your theme details.

**Comment by PsykeDady** [comment]
I have black-mate theme, on mate DE with compiz wm.
My distro is archlinux

**Comment by PsykeDady** [comment]
Oh, changing theme works! Thanks
