### ISSUE TITLE
Jayatana do not remember the menu items identifier, between update cycles.

### ISSUE THREAD

**Issue by lestcape** [rilian-la-te/vala-panel-appmenu#236]
Jayatana, create a new menu items identifier any time we make an update "sendAboutToShow". This can be traduced in a poor performance and create a lot of noises and graphics glitches.

The idea is try to find a way to not create new menu items identifier while the menu items are the same menu items  between update cycles.

**Comment by rilian-la-te** [comment]
Do you using new Jayatana (from me) or from Ubuntu repos?
There is a difference between 2 libraries.
In my fork ID is mostly static, but in Ubuntu Jayatana ID is changed frequently.

**Comment by lestcape** [comment]
@rilian-la-te  The ubuntu version... Is your package some how in the ubuntu repositories? Where is the commit when you change that?

**Comment by lestcape** [comment]
I think is this: https://github.com/rilian-la-te/vala-panel-appmenu/commit/8f359e54a46df886ef92c461dcf5cab0a2e4b65e#diff-984d397bb8393f19ca7d850995ad4942

**Comment by lestcape** [comment]
@flexiondotorg can you add this commit to the jayatana ubuntu packages? Is terrible see how all menu items are updating for nothing...

**Comment by rilian-la-te** [comment]
Yes, it is)

**Comment by rilian-la-te** [comment]
Closed as fixed (because it is fixed by https://github.com/rilian-la-te/vala-panel-appmenu/commit/8f359e54a46df886ef92c461dcf5cab0a2e4b65e#diff-984d397bb8393f19ca7d850995ad4942)
