### ISSUE TITLE
Hide window title

### ISSUE THREAD

**Issue by dimztimz** [rilian-la-te/vala-panel-appmenu#237]
Before the file menu, the window title is shown. Is there a way to hide it?

![image](https://user-images.githubusercontent.com/6236568/39752783-c5846872-52bc-11e8-947a-4ccf57ee8d2a.png)

**Comment by rilian-la-te** [comment]
Why?

**Comment by dimztimz** [comment]
In Ubuntu Unity and in Mac OS, there is no title, so the File menu is always on the same position. That gives a better user experience, it's faster to find it.

When the Title is shown, the file menu is shifted left or right for different windows.

**Comment by rilian-la-te** [comment]
In MacOS X AFAIK there is an appmenu.

In Ubuntu - I do not know.

**Comment by dimztimz** [comment]
This is in Ubuntu
![global menu](https://cloud.addictivetips.com/wp-content/uploads/2011/10/Global-Menu.jpg)

You see the title is shown, but then it fades away so File menu is at fixed position.

IF you maximize the window, the title is hidden by the window buttons, the FIle menu still starts at the same position.

![global menu maximized](https://hanynowsky.files.wordpress.com/2012/05/workspace-1_0011.png)

**Comment by rilian-la-te** [comment]
I prefer a MacOS solution.

**Comment by dimztimz** [comment]
I'm not saying to switch to Unity layout, but to give option to hide that. The option would be well, optional.

Appmenu is used only by a few Gnome apps, other apps don't implement it, so the panel shows some generic appmenu which isn't very useful.

Maybe use the follwing logic
```
If application has custom appmenu
    render app menu

render normal menus
```

**Comment by dimztimz** [comment]
OR actually Unity smth like this:

```
If application has normal menus
    rendel only normal menus
else if has appmenu
    render only appmenu
else
    just show title, or generic appmenu.
```

I think this is the Unity behavior.

**Comment by rilian-la-te** [comment]
I do not like a removal of appmenu. Because I like consistent interfaces. And Gnome application can have both appmenu and normal menus (then both should be rendered).

**Comment by dimztimz** [comment]
Gnome 3 apps like nautilus don't use normal menus at all. They use one appmenu and the rest of the menus are put under a single button. 

Lets not argue any more. Can you tell me which part of the code needs changing to hide the appmenu and i will experiment asaide on my own.

**Comment by CreamyCookie** [comment]
@rilian-la-te Is there really not a chance that such an option will be included? I really love Unity's behavior, where by default the window title is shown, and when you move your mouse over it, it immediately changes to the menu, thus always showing the menu at the position (which I assume results in a small efficiency boost, i.e. you'll find what you're looking for faster)

Anyway, thank you for vala panel appmenu! :)

**Comment by CreamyCookie** [comment]
Oops, sorry! I also just saw that the Mate desktop actually doesn't show the title before the menu so it's fine for me! :)
