### ISSUE TITLE
Can't to install, because I never did сompilation!

### ISSUE THREAD

**Issue by Yashalta** [rilian-la-te/vala-panel-appmenu#239]
Hi,
I have Debian v9.4 x64bit, XFCE4
What i have done without questions!:
1. Clone this repository to your home directory...
It is ok, everything is regular, no questions!
2. ... then cd into the directory. 
it is also ok, everything is regular, no questions!
3. git submodule init && git submodule update, It's done!
4. mkdir build && cd build It's also done without any questions!

But next are some questions!
a) How to exactly write the commands for terminal?
something like this -DENABLE_XFCE=[ON/OFF]? and after that i will get a question and I will should answer "ON"?
Or should it be like that? cmake -DENABLE_XFCE=[ON/OFF]
I ask because I tried both options and both are not correct!
b) Which flags do I need to use in my case? (Debian v9.4 x64bit, XFCE4)
c) By default, Vala-Panel-Appmenu will install in the /usr/local directory...
cmake -DCMAKE_INSTALL_PREFIX=/usr - Is this the right command in my case?

Please help me!

**Comment by rilian-la-te** [comment]
c) - yes.
a) You do not need to enable XFCE explicitly, just install required packages (devel version).
b) Prefix should be enough. All other flags will be determined automatically. For preventing a wrong combination of flags, install all devel packages required (do not know what exactly, I am not on Debian-based)
