### ISSUE TITLE
Change font of the menu.

### ISSUE THREAD

**Issue by mtuchowski** [rilian-la-te/vala-panel-appmenu#26]
Not really a bug, but a question. Is it possible tho change it? If yes, this information should probably go to README.

**Comment by wesleyotugo** [comment]
Yes, for xfce4-appmenu you can change it  by changing your panel size.

Same thing can be done for the vala-panel-appmenu

**Comment by mtuchowski** [comment]
I don't get it… I do use xfce4-appmenu, and while changing the panel size does work, in a sense that the appmenu adjusts, the font face setting is not there. The font used for appmenu is the same as set for GTK with the difference that it seems to use a bold version of the font. Is that intentional?

**Comment by rilian-la-te** [comment]
It uses GtkMenuBar fonts. Yes. it is possible, by setting custom CSS. And for vala-panel you can change it in settings.
