### ISSUE TITLE
make mate-panel an optdepend?

### ISSUE THREAD

**Issue by CadaverLab** [rilian-la-te/vala-panel-appmenu#27]
I was about to update this when I noticed it wanted to install mate-panel (and with it mate-desktop). Is this really necessary? I am on xfce after all. Distro is arch.

**Comment by rilian-la-te** [comment]
If you does not need mate-panel applet for appmenu, you does not need mate-panel. This is true for vala-panel also. Just use only XFCE version. As a package - I does not know, how to write split package with shared build and split makedepends. Help welcomed.

**Comment by rilian-la-te** [comment]
Closing this.
