### ISSUE TITLE
Support for Java based apps?

### ISSUE THREAD

**Issue by CadaverLab** [rilian-la-te/vala-panel-appmenu#28]
I've noticed the menu for, say, the Arduino IDE stays attached to its window. Processing probably does this too, but I haven't tested it. Is there any way to make these work with appmenu?

**Comment by rilian-la-te** [comment]
Try Jayatana. It may work, because it is basically Unity stack ported to other desktops.

**Comment by rilian-la-te** [comment]
Let's write here about issues (but issues of appmenu and vala-dbusmenu only, not Jayatana)

**Comment by lestcape** [comment]
jatana, will probably can cause some instabilities... I cant use it properly in cinnamon...

**Comment by rilian-la-te** [comment]
Try JAyatana to support Java, please.

**Comment by rilian-la-te** [comment]
AFAIK, experimental support is done by JAyatana.
