### ISSUE TITLE
Chromium based applications cause the panel to crash

### ISSUE THREAD

**Issue by St1rling** [rilian-la-te/vala-panel-appmenu#29]
When using any chromium based applications (Chrome, Atom, VSCode, etc) it freezes and both vala-panel, and bamfdaemons cpu usage hits ~25% each. My apologises if I'm wrong, but would this be caused by vala-panel incorrectly passing information from chromium into bamf and when it fails once, it tries over and over. Just what I believe to be happening, I'm probably wrong. If I use chrome or open any sort of app, it takes ~5s before vala-panel crashes.

**Comment by rilian-la-te** [comment]
Logs, please. It is works for me, but for you I need more info. Distro, running panel Logs at least, and also used applets.

**Comment by St1rling** [comment]
Distro: Arch Linux 64-bit

Logs - Start

$ vala-panel

(vala-panel:8252): GLib-GIO-CRITICAL **: g_menu_remove: assertion '0 <= position && position < menu->items->len' failed

(vala-panel:8252): Gtk-WARNING **: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkToggleButton)

(vala-panel:8252): Gtk-WARNING **: Negative content height -7 (allocation 1, extents 4x4) while allocating gadget (node menuitem, owner GtkModelMenuItem)

(vala-panel:8252): Gtk-WARNING **: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkToggleButton)

(vala-panel:8252): Gtk-CRITICAL **: gtk_label_set_text_with_mnemonic: assertion 'str != NULL' failed

(vala-panel:8252): GLib-GIO-CRITICAL **: g_menu_remove: assertion '0 <= position && position < menu->items->len' failed

(vala-panel:8252): GLib-GIO-CRITICAL **: g_menu_remove: assertion '0 <= position && position < menu->items->len' failed
GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

** (vala-panel:8252): WARNING **: Failed to fetch property `_GTK_UNIQUE_BUS_NAME': GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/41943042

** (vala-panel:8252): CRITICAL **: appmenu_menu_widget_get_window_id: assertion 'self != NULL' failed

** (vala-panel:8252): WARNING **: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/41943042
[1]    8252 segmentation fault (core dumped)  vala-panel

Logs - End

Plugins: http://imgur.com/a/IUovc

**Comment by rilian-la-te** [comment]
Please fill bug to vala-panel-appmenu, panel itself does not interact with libbamf.

**Comment by rilian-la-te** [comment]
Looking to logs, it has string 
```
** (vala-panel:8252): WARNING **: Failed to fetch property `_GTK_UNIQUE_BUS_NAME': GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/41943042

** (vala-panel:8252): CRITICAL **: appmenu_menu_widget_get_window_id: assertion 'self != NULL' failed
```
But Chromium must use DBusMenu, not GMenuModel. Do you have installed dbusmenu (libdbusmenu-glib)?

**Comment by St1rling** [comment]
Yes I do, see [here](http://imgur.com/a/geL7J)
I checked by trying to remove it, it's installed.

**Comment by rilian-la-te** [comment]
This evening I will show my appmenu related packages. Look which is not installed in your PC.

**Comment by rilian-la-te** [comment]
what about UBUNTU_MENUPROXY and other instruction based installs?

**Comment by St1rling** [comment]
I've followed the instructions completely, they're all installed

**Comment by rilian-la-te** [comment]
What version of libbamf do you have? What window manager do you using?

**Comment by St1rling** [comment]
Compiz, latest version of libbamf. It's not been happening as frequently since I reinstalled it, I'll post in a while if it crops up again

**Comment by rilian-la-te** [comment]
I does not test vala-panel with compiz, sorry. Is it happens with openbox or mutter?

**Comment by St1rling** [comment]
I wouldn't know, I don't use either of those WMs, sorry.

**Comment by rilian-la-te** [comment]
What version of Compiz?

**Comment by St1rling** [comment]
0.9.12

**Comment by rilian-la-te** [comment]
Closing this as works for me and inactive for 6 months.
