### ISSUE TITLE
Replace MATE with XFCE in necessary places

### ISSUE THREAD

**Issue by rilian-la-te** [rilian-la-te/vala-panel-appmenu#30]

**Comment by VartanBelavejian** [comment]
Not sure if relevant but I'm running xfce on Arch 64 bit and certain applications like transmission and latexila will display the menu in the xfce panel but when i click on any of the options it causes the application to crash. Also chromium based apps and libre office don't seem to work for me. I installed via the AUR package and followed the instructions in the readme here. gtk2 applications like thunar and terminal work great and so do thunderbird and gimp. Any ideas?

**Comment by rilian-la-te** [comment]
LO and chromium works, but for LO you need to set gtk_shell_shows_menubar in xfce4-settings-manager (file-based options works only for vala-panel in no-DE setup). About transsmission - it works for me. About latexila - does not use it. Can you prove logs and create new bugreport (This report is for MATE support)

**Comment by rilian-la-te** [comment]
Fixed all AFAIK.
