### ISSUE TITLE
Cinnamon global menu in Arch?

### ISSUE THREAD

**Issue by lestcape** [rilian-la-te/vala-panel-appmenu#31]
I really don't know what you do here, but i think that nothing relate with cinnamon.

Your code could be installed a will work for all app finally?

As we use the same backend (unity-gtk-module), I think not all of your code will be needed, but some of your code probably yes. I need something of your code to run my implementation of the global menu in Arch?

As i know, you test some things about this with Arch and some application work ok, probably you can said me what it's needed...

Thanks any way...

**Comment by rilian-la-te** [comment]
Yes, you need [this patch](https://github.com/rilian-la-te/unity-gtk-module-packages/blob/master/unity-gtk-module-gsettings.patch)

Without this patch, unity-gtk-module requires patched GTK2.

**Comment by lestcape** [comment]
Thanks!!! Is not for me, but some people ask me how to install this on Arch and really  I can not give it an appropriate response. Now i can. Thanks.
