### ISSUE TITLE
Build Error In Arch Linux

### ISSUE THREAD

**Issue by wesleyotugo** [rilian-la-te/vala-panel-appmenu#33]
![screenshot at 2016-09-30 01-49-46](https://cloud.githubusercontent.com/assets/17808627/18977282/72e86e10-86a8-11e6-97e1-feac6de4a041.png)

Here is the [build log](http://pastebin.com/fS7YgXqB)

**Comment by St1rling** [comment]
I get the same

**Comment by rilian-la-te** [comment]
Will fix it this evening

**Comment by rilian-la-te** [comment]
Fixed with recent vala-panel commit.
