### ISSUE TITLE
AUR build error

### ISSUE THREAD

**Issue by St1rling** [rilian-la-te/vala-panel-appmenu#34]
[ 55%] Building C object lib/CMakeFiles/appmenu-valapanel.dir/menu-widget-dbusmenu.c.o
[ 57%] Building C object lib/CMakeFiles/appmenu-valapanel.dir/menu-widget-menumodel.c.o
[ 59%] Building C object lib/CMakeFiles/appmenu-valapanel.dir/valapanel-plugin-appmenu.c.o
/home/obadiah/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/lib/valapanel-plugin-appmenu.c:84:89: error: unknown type name ‘PanelToplevel’
 appmenu_applet_real_get_applet_widget (ValaPanelAppletPlugin* base, PanelToplevel* toplevel, GSettings* settings, guint number);
                                                                     ^~~~~~~~~~~~~
/home/obadiah/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/lib/valapanel-plugin-appmenu.c:85:43: error: unknown type name ‘PanelToplevel’
 GlobalMenuApplet* global_menu_applet_new (PanelToplevel* top, GSettings* settings, guint number);
                                           ^~~~~~~~~~~~~
/home/obadiah/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/lib/valapanel-plugin-appmenu.c:86:68: error: unknown type name ‘PanelToplevel’
 GlobalMenuApplet* global_menu_applet_construct (GType object_type, PanelToplevel* top, GSettings* settings, guint number);
                                                                    ^~~~~~~~~~~~~
/home/obadiah/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/lib/valapanel-plugin-appmenu.c:98:89: error: unknown type name ‘PanelToplevel’
 appmenu_applet_real_get_applet_widget (ValaPanelAppletPlugin* base, PanelToplevel* toplevel, GSettings* settings, guint number) {
                                                                     ^~~~~~~~~~~~~
/home/obadiah/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/lib/valapanel-plugin-appmenu.vala: In function ‘appmenu_applet_vala_panel_applet_plugin_interface_init’:
/home/obadiah/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/lib/valapanel-plugin-appmenu.vala:24:71: error: unknown type name ‘PanelToplevel’
 public class AppmenuApplet : AppletPlugin, Peas.ExtensionBase
                                                                       ^            
/home/obadiah/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/lib/valapanel-plugin-appmenu.vala:24:107: error: expected ‘;’ before ‘appmenu_applet_real_get_applet_widget’
 public class AppmenuApplet : AppletPlugin, Peas.ExtensionBase
                                                                                                           ^                                    
valapanel-plugin-appmenu.c: At top level:
valapanel-plugin-appmenu.c:178:68: error: unknown type name ‘PanelToplevel’
 GlobalMenuApplet* global_menu_applet_construct (GType object_type, PanelToplevel* top, GSettings* settings, guint number) {
                                                                    ^~~~~~~~~~~~~
valapanel-plugin-appmenu.c:199:43: error: unknown type name ‘PanelToplevel’
 GlobalMenuApplet* global_menu_applet_new (PanelToplevel* top, GSettings* settings, guint number) {
                                           ^~~~~~~~~~~~~
make[2]: *** [lib/CMakeFiles/appmenu-valapanel.dir/build.make:283: lib/CMakeFiles/appmenu-valapanel.dir/valapanel-plugin-appmenu.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:327: lib/CMakeFiles/appmenu-valapanel.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
:: Building neofetch-git package(s)...

**Comment by rilian-la-te** [comment]
fixed

**Comment by St1rling** [comment]
I gotta say man, you're absolutely amazing. That was such a fast response! :)
