### ISSUE TITLE
Xfce Terminal

### ISSUE THREAD

**Issue by andreyorst** [rilian-la-te/vala-panel-appmenu#35]
Well, this is kinda weird, but I've done everything as shown in README file. 
And got this:
![123](https://cloud.githubusercontent.com/assets/19470159/19685088/5b332ccc-9ac3-11e6-9329-ffa69385cf15.png)
When i click "show menubar" in Xfce Terminal menubar itself shows in panel. But if i hide it from window - I only see title in panel. The reason why menubar in Xfce Terminal was not autohided, as it was in thunar for example is mysterious. Every other app works fine.

**Comment by rilian-la-te** [comment]
It happens only in xfce4-terminal?

**Comment by andreyorst** [comment]
Checked some apps- same in transmission-gtk and dconf-editor

**Comment by rilian-la-te** [comment]
GTK3 applications?

**Comment by andreyorst** [comment]
sorry, don't have any.

**Comment by rilian-la-te** [comment]
try file-roller. Gnome-terminal is known issue.

**Comment by andreyorst** [comment]
I thought that CSD applications don't suppose to work at all, because they don't use such menu in traditional way. 
![aas](https://cloud.githubusercontent.com/assets/19470159/19735498/87e7521a-9bb4-11e6-9311-2e2a7880bcbe.png)

**Comment by rilian-la-te** [comment]
It must work:
![screenshot from 2016-10-26 20-39-21](https://cloud.githubusercontent.com/assets/1329638/19737486/b6798a02-9bc4-11e6-851e-96b473f58501.png)

**Comment by andreyorst** [comment]
Ok then. Maybe I missed something. What i've done: 
Made files with settings as written in readme.
![image](https://cloud.githubusercontent.com/assets/19470159/19745847/393e3ce6-9bdc-11e6-9796-131942ae93e0.png)
installed  unity-gtk-module-standalone-bzr from AUR,  Appmenu-qt and Appmenu-qt5, and  libdbusmenu-glib libdbusmenu-gtk3 libdbusmenu-gtk2. Did i've done something wrong?
_________________________________
Some info:
I'm using XFCE 4.12 with compton.

**Comment by rilian-la-te** [comment]
Afaik, you do it right. Do it works under another WM? And try to edit xsettings value in xfce4-settings-editor to match your settings.ini.

**Comment by andreyorst** [comment]
Don't have any other WM, but will try in mate. 

> And try to edit xsettings value in xfce4-settings-editor to match your settings.ini.
match my /home/usermane/.config/gtk-3.0/settings.ini? 

Maybe you can advice me where i could get logs of this plugin, so it will be easer to find where i was wrong, or bug

**Comment by rilian-la-te** [comment]
You can install GTK3 version of mate. You do not need a logs of the plugin, because you need to create key Gtk/ShellShowsMenubar with boot of true and GtkShellShowsAppmenu with bool of true in xsettings of XFCE.

**Comment by rilian-la-te** [comment]
On my screen there is Openbox.

**Comment by andreyorst** [comment]
Yes. That worked. Thanks for your patience
