### ISSUE TITLE
No Appmenu in VLC and Gparted

### ISSUE THREAD

**Issue by mentofa123** [rilian-la-te/vala-panel-appmenu#38]
Hey, i freshly installed Manjaro Xfce 16.10 on my Pc and wanted to try out the app menu. i installed the package from the aur, the unity-gtk-module-standalone-bzr, appmenu and appmenu qt5, and the libdbusmenu packages. 
So far i don't get neither on VLC, gparted nor on Firefox the app menu. 

Greetings

**Comment by rilian-la-te** [comment]
Firefox not working, and root applications also. It is known limitations.
Do you have platformtheme appmenu-qt5?

**Comment by d-belyakin** [comment]
Hi, I'm using Ubuntu with xfce4 desktop installed manually. I have no global menu for gparted as well, also for Pidgin. It works for QtCreator and Firefox(!), for most gtk apps.
And I experienced some troubles with font rendering or alising:
![_2016-11-14_22-26-25](https://cloud.githubusercontent.com/assets/5464178/20279384/691cf556-aab9-11e6-9f33-8c09eb574a0d.png)

**Comment by rilian-la-te** [comment]
Ok, for Pidgin and transmission I have an answer,
You can install GTK3 version of mate. You do not need a logs of the plugin, because you need to create key Gtk/ShellShowsMenubar with boot of true and GtkShellShowsAppmenu with bool of true in xsettings of XFCE.

**Comment by rilian-la-te** [comment]
Fonts coming from theme, not from me:)

**Comment by d-belyakin** [comment]
Still no effect with ShellShowsMenuBar etc, but I think i should dig deeper with this settings, thanks for clarification.
It also seems that I found a reason for Gparted: gparted usually starts as root)
Regarding fonts: yep, font fetched from theme and I successfully changed it yesterday, but I mean that something not OK with rendering or antialiasing.

**Comment by rilian-la-te** [comment]
So, I will closing this
