### ISSUE TITLE
Question about a desktop menu

### ISSUE THREAD

**Issue by wapsi** [rilian-la-te/vala-panel-appmenu#39]
I noticed that if I use Xfce for example and if there aren't any windows selected or I press desktop space I will get a generic menu that shows Desktop and Files menus. I've a custom CSS that bolds the first item of the menu:
```
.-vala-panel-appmenu-private:nth-child(1) > * > * {
font-weight: 600;
}
```
But in that genreic desktop menu the Desktop menu entry is nth-child(2) so it doesn't get bold although (it looks like) it is the first menu item. So my question is: Is it possible to add some custom text into nth-child(1) item in that special desktop menu or move that Desktop submenu to be nth-child(1) and not nth-child(2). I tried to review the code and I think the Desktop submenu is added in appmenu-desktop.vala:
```
                if (name == null)
                    name = _("_Desktop");
                menu.prepend_submenu(name,gmenu);
                menu.freeze();
```
But I don't know how to change it to be nth-child(1).

**Comment by rilian-la-te** [comment]
What is First child in generic menu? Can you use gtk - inspector to
determine that?

**Comment by wapsi** [comment]
Hmmm, It's impossible to open the tree in gtk inspector app because vala-panel-appmenu changes the menu to gtk inspector menu if I click in inspector window something and then of course the isn't the generic desktop menu active :smiley:

**Comment by rilian-la-te** [comment]
Ok, will look for it.

**Comment by rilian-la-te** [comment]
Ok, I think that I know bug source, and I does not want to fix it.
Vala-panel-appmenu uses two menubars - one for appmenu, and one for
menubar. Desktop menu show on menubar side, after empty appmenu (if desktop
selected). If you want, you can fix it. Simply moving it to appmenu side
won't work. And I am too lazy to implement a proper fix, especially before
overall C rewrite .

**Comment by jp1995** [comment]
@wapsi Hey, I stumbled upon your post on /r/unixporn and then I found this post. How did you end up making it work?

**Comment by wapsi** [comment]
@jp1995 I noticed that if I enabled Gnome's desktop icons in gnome-shell using following command: gsettings set org.gnome.desktop.background show-desktop-icons true the menu looks same as in my screenshots. Xfce4's menu didn't look that and that's why created this issue.

**Comment by jp1995** [comment]
@wapsi Wow, that is weird. Okay, thanks.

**Comment by rilian-la-te** [comment]
This is fixed.
