### ISSUE TITLE
Applications wont close, Menu bar stick  after closing the current window

### ISSUE THREAD

**Issue by snippins** [rilian-la-te/vala-panel-appmenu#40]
The kubuntu backports PPA now include qt 5.6.1. This Qt version's default platform theme already exports the menus so I remove appmenu-qt5 and test it.

## Summary
The menu works fine but when closing the program, its window is closed but it still running in background and the menu got stuck. The problem happen with krusader (new kf5 version 2.5.0), vlc,   

## Step to reproduce
1. Open terminal and run:  QT_QPA_PLATFORMTHEME="" krusader
2. Close the window 

## What happened
The window is closed but the menu of is still visible and krusader still runs in background. After about ~20s, the following errors appears

> Failed to unregister window menu, reason: org.freedesktop.DBus.Error.NoReply ("Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.")

## What is expected
The krusader process is closed immediately after its window is closed.

## More details
Also tested on vlc, same problem

**Comment by rilian-la-te** [comment]
Will test it on New Year.

**Comment by hotice** [comment]
I can confirm this issue in Ubuntu (MATE/Xubuntu). Installing ``appmenu-qt5`` gets rid of this issue though.

**Comment by rilian-la-te** [comment]
Do this bug exists with Qt 5.7?

**Comment by hotice** [comment]
I for one did not test this, as Ubuntu (MATE/Xubuntu) 16.10 has Qt 5.6.1 and I didn't try it in the Ubuntu development version (which does have 5.7.1).

**Comment by rilian-la-te** [comment]
Bug exists, I must investigate it.

**Comment by rilian-la-te** [comment]
It is Qt failure. Qt implementation of appmenu does not unregister windows after use (so, appmenu try to recreate menu and fails with a timeout). 
appmenu-qt5 is more proper implementation, I think.

**Comment by rilian-la-te** [comment]
Added workaround in https://github.com/rilian-la-te/vala-dbusmenu/commit/84daace18ce8327ac1497747fd362727904d5783
Need to test SNTray with it.

**Comment by rilian-la-te** [comment]
AFAIK, not.
