### ISSUE TITLE
Ubuntu ppa

### ISSUE THREAD

**Issue by Malezha** [rilian-la-te/vala-panel-appmenu#41]
Can u update [ppa](https://launchpad.net/~rilian-la-te/+archive/ubuntu/vala-panel-plugins)?
And please, change your gpg key to other algorithm, because sha1 is deprecated.
```
W: http://ppa.launchpad.net/rilian-la-te/vala-panel-plugins/ubuntu/dists/vivid/Release.gpg: При подписи ключом D8E33663F67511A70FBC4954DAFB9218E22FC538 используется нестойкий алгоритм свёртки (SHA1)
```

**Comment by rilian-la-te** [comment]
I does not have Ubuntu now:( But will look for it (maybe OBS repo will be used instead).

**Comment by rilian-la-te** [comment]
Using webupd8 ppa, please. My PPA is outdated a lot.

**Comment by Malezha** [comment]
Detailed instructions can be found [here](http://www.webupd8.org/2017/02/alternative-global-menu-for-mate-and.html).
