### ISSUE TITLE
Wanting to use XFCE4 Panel in Openbox

### ISSUE THREAD

**Issue by Dobbie03** [rilian-la-te/vala-panel-appmenu#42]
but the module fails to load:

Gtk-Message: Failed to load module "topmenu-gtk-module" 

Does this only work in XFCE?

**Comment by rilian-la-te** [comment]
Topmenu is not my module. My project needs unity-gtk-module:) You are confused with another project. Any questions?

**Comment by rilian-la-te** [comment]
Not a bug, closing.
