### ISSUE TITLE
Double menu bar

### ISSUE THREAD

**Issue by antonysmart** [rilian-la-te/vala-panel-appmenu#43]
Hi, I'm using your vala-panel-appmenu in Arch Linux XFCE. I've installed all dependencies, following your guide and it works fine, but in some applications, like Parole Media Player or Xfce Terminal I have both my global-menu applet in the top bar and the classic menu bar in the application window.

How can I solve this, to have just the global-menu?
Thanks.

![screenshot_2017-01-15_20-12-07](https://cloud.githubusercontent.com/assets/25137986/21965473/d25e12d4-db60-11e6-82c9-058e224e4d50.png)

**Comment by rilian-la-te** [comment]
What unity-gtk-module do you have?

**Comment by antonysmart** [comment]
I installed it from AUR.

**Comment by antonysmart** [comment]
I share you also my ~/.profile and ~/.config/gtk-3.0/settings.ini

**~/.profile**
export GTK_MODULES=unity-gtk-module:$GTK_MODULES
export UBUNTU_MENUPROXY=1

**~/.config/gtk-3.0/settings.ini**
gtk-shell-shows-app-menu=true
gtk-shell-shows-menubar=true

**Comment by rilian-la-te** [comment]
Name of the AUR package?

**Comment by antonysmart** [comment]
unity-gtk-module-standalone-bzr

**Comment by rilian-la-te** [comment]
Do you enable GSettings setting to disable GTK2 menubars?

**Comment by antonysmart** [comment]
So, in dconf-editor I set /com/canonical/unity-gtk-modules/gtk2-shell-shows-menubar like true, and  now I have just global-menu, except for Parole Media Player and Terminal, where I still have both menus.

Do you think it is a problem of those applications?

**Comment by rilian-la-te** [comment]
What about other GTK3 apps?

**Comment by antonysmart** [comment]
In other GTK3 apps like Transmission I have the same problem, but I haven't tried a lot of GTK3 apps because most of them use CSD (GTK HeaderBar).

When I start root applications, like GParted it doesn't work.

Then I've tested it with LibreOffice, Thunar and Gimp and it's perfect.

**Comment by antonysmart** [comment]
Sorry if I go out topic, but I want to ask you if you are going to make a global-menu applet for Gnome-Shell.

**Comment by rilian-la-te** [comment]
For Gnome-Shell - no.
For GTK3 apps - there are another bug (closed) with guide for GTK3 appmenu
for XFCE (i simple does not remember xfce4-settings-editor options
exactly). If asked about principle, then you must find GtkSettings category
in xfce4-settings-editor, and add 2 options: ShellShowsAppmenu and
ShellShowsMenubar. Both boolean and true.

**Comment by rilian-la-te** [comment]
[here](https://github.com/rilian-la-te/vala-panel-appmenu/issues/35) is the manual. Please configure GTK3 apps and close this.

**Comment by antonysmart** [comment]
Ok. Now it works perfect!

Can you add this solution in your README.md? It might be useful for other users.

Thanks to help me and for your patience!

**Comment by rilian-la-te** [comment]
Install registrar (vala-panel-appmenu-registrar-git from AUR)
