### ISSUE TITLE
Change font colour?

### ISSUE THREAD

**Issue by ai23** [rilian-la-te/vala-panel-appmenu#44]
Hello, I'm using your vala-panel-appmenu plugin for XFCE on Arch Linux. My one issue is that the font color does not go with my preferred panel color (the font color and my panel color is white). Is there any way to change the font colour to black? By the way: I installed this from the AUR (vala-panel-appmenu-
xfce-git) and followed your instructions to properly make it work. Thanks.

**Comment by rilian-la-te** [comment]
The color of plugin matches your current GTK3 theme, but rest of panel maybe GTK2. So, one oblivious way to change color - change GTK3 theme (look to indicator plugin for reference)

**Comment by ai23** [comment]
Hmm, is there anyway to hard code the font color onto the plugin? The problem is I cannot find a GTK3 theme that is as the one I'm using right now. Thanks for responding!

**Comment by rilian-la-te** [comment]
No, I do not want to hardcode color into a plugin (because vala-panel can change font color itself)

**Comment by ai23** [comment]
How would I go about hard coding a font color for personal use? Thanks.

**Comment by jmaris** [comment]
Could you give us an idea what the name of the GTK property is so we can manually override it in GTK config ?

**Comment by rilian-la-te** [comment]
Use gtk-inspector for determine unique name, and write simple CSS.

**Comment by rilian-la-te** [comment]
If you using vala-panel, you can change font color directly.

**Comment by jmaris** [comment]
If you are using Xfce Panel, the way to change it is to create or edit ~/.config/gtk-3.0/gtk.css
and insert
```
.-vala-panel-appmenu-private {
color:black;}
```
replacing black by your color choice ofc :)

**Comment by ai23** [comment]
It worked! Thank you so much jmaris!
