### ISSUE TITLE
CSS for the App menu?

### ISSUE THREAD

**Issue by peridot-idk** [rilian-la-te/vala-panel-appmenu#45]
OK so I am making an Mac Style DE made with XFCE but I want know how can I edit the css? is it part of the GTK theme or is there a seperate css for this?

**Comment by rilian-la-te** [comment]
Part of GTK theme, standard menubar component, AFAIK.

**Comment by peridot-idk** [comment]
I do have a theme that supports gtk2 and gtk3 but XFCE uses the gtk2 version instead of the gtk3 version hmm :/

**Comment by rilian-la-te** [comment]
Nope. XFCE is using whatever version programs using. For example, my plugin uses GTK3, but rest of panel uses GTK2

**Comment by peridot-idk** [comment]
Hmm I didn't know that lol

**Comment by peridot-idk** [comment]
I tried to add this into the panel.rc (IDK if that's the right file)

.-vala-panel-appmenu-private:nth-child(1) > * > GtkLabel {
  font-weight: 600;
}

.-vala-panel-appmenu-private > * > GtkLabel {
    font-size: 18px;
}

It's not working

**Comment by rilian-la-te** [comment]
what is panel.rc? you must modufy a whole theme itself:)

**Comment by misterair** [comment]
And I find the solution! For the Greybird theme in Ubuntu repo (the Github version has a lot of bug in Ubuntu 16.04), just add at the end of the file "_Greybird/gtk-3.0/apps/xfce.css_":

```
.-vala-panel-appmenu-private > * > GtkLabel, .-vala-panel-appmenu-private > * > GtkWidget > * {
	color: #fcfcfc;
	font-weight: normal;
	padding: 0 4px 0 2px;
}
.-vala-panel-appmenu-private:nth-child(1) > * > GtkLabel {
	font-style: italic;
}
```

You're welcome ;-)

**Comment by rilian-la-te** [comment]
I am closing this, so.
