### ISSUE TITLE
Solving problem in xfce and arch

### ISSUE THREAD

**Issue by alireza-amirsamimi** [rilian-la-te/vala-panel-appmenu#46]
Hello
Thanks for this nice app! It worked for me in Qt and gtk2 and gtk3 applications!

maintainer of [unity-gtk-module-standalone-bzr](https://aur.archlinux.org/packages/unity-gtk-module-standalone-bzr/) forgot to add bzr package as dependency . If you are the maintainer , please fix this :)

**Comment by rilian-la-te** [comment]
Fixed
