### ISSUE TITLE
Conflict appmenu-qt5 and qt5ct

### ISSUE THREAD

**Issue by sujaataarya** [rilian-la-te/vala-panel-appmenu#47]
Hello!

I encountered a problem appmenu-qt5 qt5ct and simultaneous use.

In the configuration file ~/.profile,
these two lines are not capable of working simultaneously:
export QT_QPA_PLATFORMTHEME=appmenu-qt5
export QT_QPA_PLATFORMTHEME="qt5ct"

The result is
1) or qt5ct use to customize design qt applications
2) or the use of appmenu-qt5 to implement the global menu bar.

Is it possible to solve such a conflict?
I would be very grateful for the answer.

Best regards, Sergey.

**Comment by rilian-la-te** [comment]
If you use qt 5.7, you may remove appmenu-qt5.

**Comment by sujaataarya** [comment]
Thank you very much for your answer!
I removed appmenu-qt5 and applications such as digiKam Krusader start from the menu, but only when this line is in the configuration file ~ /.profile:
export QT_QPA_PLATFORMTHEME=appmenu-qt5
It is necessary to delete it, as in the menu on the panel, only the title of the application is displayed
Tell me what to do in order not to use this record or something else to advise.

**Comment by rilian-la-te** [comment]
What version of Qt are you using?

**Comment by sujaataarya** [comment]
Qt 5.8.0

**Comment by sujaataarya** [comment]
OS: Arch Linux 
 Kernel: x86_64 Linux 4.9.11-1-ARCH
 Uptime: 7h 1m
 Packages: 2102
 Shell: bash 4.4.12
 Resolution: 1920x1080
 DE: XFCE4
 WM: Xfwm4
 WM Theme: Ambiance
 GTK Theme: Ambiance [GTK2]
 Icon Theme: Humanity
 Font: Ubuntu 11
 CPU: Intel Core2 Duo CPU E7600 @ 3.066GHz
 GPU: AMD/ATI RV770 [Radeon HD 4850]
 RAM: 2399MiB / 7987MiB

**Comment by rilian-la-te** [comment]
Oh. I does not have such issue (not using qt5ct). What you see without platformtheme?

**Comment by sujaataarya** [comment]
Without using the string
export QT_QPA_PLATFORMTHEME = appmenu-qt5
The QT application menu does not work, only GTK.

**Comment by sujaataarya** [comment]
Where can I send screenshots?

**Comment by rilian-la-te** [comment]
It is strange. Do you using Arch? You can post screenshots here.

**Comment by sujaataarya** [comment]
**Here is the result of the removal**
_export QT_QPA_PLATFORMTHEME = appmenu-qt5_
All QT applications work fine!
![_2017-03-12_21-53-55](https://cloud.githubusercontent.com/assets/12985719/23834202/430d0028-0774-11e7-9b83-2f48b748e767.png)

**There is a conflict arises from the presence**
_export QT_QPA_PLATFORMTHEME="qt5ct"_
It was worth putting it into .profile as the menu ceased to be displayed for QT applications
![_2017-03-12_22-28-41](https://cloud.githubusercontent.com/assets/12985719/23834206/535fee68-0774-11e7-8a56-78d383576f4c.png)

That is, the conflict remained
or qt5ct use to customize design qt applications
or the use of appmenu to implement the global menu bar

I prefer to use appmenu, but if I get the same result in a single interface design, it will be great.
Perhaps the developers of QT applications and KDE will provide competent support for the design for GTK as it was in KDE4.

Probably you can close this question until better times.
Thank you for your participation and support!  I wish all the best!

**Comment by rilian-la-te** [comment]
Write a bug to qt5ct to support new qt 5.7 appmenu:) May it helps:)

**Comment by rilian-la-te** [comment]
Now it works without appmenu-qt. Closing.
