### ISSUE TITLE
Support for Elementary OS?

### ISSUE THREAD

**Issue by giovannicaligaris** [rilian-la-te/vala-panel-appmenu#49]
Is there any way to install this in eOS? I tried it in Xubuntu 17.04 and it looks beautiful.

I think it would be a great addition to eOS.

**Comment by rilian-la-te** [comment]
Install vala-panel or xfce4-panel:-)

**Comment by rilian-la-te** [comment]
If you want help building a package, you can write here.

**Comment by giovannicaligaris** [comment]
I would love to, but I can't code.

**Comment by rilian-la-te** [comment]
I built appmenu for 17.04:
```
sudo add-apt-repository ppa:rilian-la-te/vala-panel-plugins
sudo apt-get update
```

**Comment by rilian-la-te** [comment]
Closing this as wontfix, because i will not support wingpanel, sorry.
If someone writes a patch - I will reopen it. Wontfix.
