### ISSUE TITLE
Menus render in space larger than themselves ?

### ISSUE THREAD

**Issue by jmaris** [rilian-la-te/vala-panel-appmenu#50]
I've recently ran into an interesting issue, I use compton as my compositor, and I noticed that if I enable blur behind menus, it blurs outside of the actual menu.

Compton thinks they are rendering something in that space, hence blurs behind. i was wondering if you had any idea why ?

![screenshot_2017-03-13_10-41-45](https://cloud.githubusercontent.com/assets/342289/23848994/e3d1bb7e-07d9-11e7-9f5a-de88b4d22da6.png)

**Comment by rilian-la-te** [comment]
Look into your gtk theme. If it uses shadows around menus - compton may think that shadow is part of menu window.

**Comment by jmaris** [comment]
Thanks ! I'll take a look ! :)

**Comment by jmaris** [comment]
adding 
```
.-vala-panel-appmenu-private *{
box-shadow:none;}
```
to ~/.config/gtk-3.0/gtk.css fixes it for me ;) thanks again for your help !
