### ISSUE TITLE
Xfce4 appmenu plugin looks very broken

### ISSUE THREAD

**Issue by jp1995** [rilian-la-te/vala-panel-appmenu#51]
Just giving you a pic should describe the problem pretty well: http://i.imgur.com/40c5paj.png

The text in the menus is blurry and the menus themselves have no padding between them.

I am using Arch Linux. Fonts render fine everywhere else in my system.

I installed vala-panel-appmenu-xfce-git from the AUR and I did everything in the Installation after building section of the Readme.

I should add that the plugin is also very unstable on my system. Sometimes it lags behind when I switch windows and I've had some crashes.

This is probably just me doing something wrong. Can you point me in the right direction? 

Thanks in advance.

**Comment by rilian-la-te** [comment]
What GTK theme do you use?

**Comment by jp1995** [comment]
I'm using a modified Arc theme, arc-osx. Switched to adwaita and the problem is solved. 

Am I missing some gtk related packages? I've noticed some other things being broken while using this theme, like the gnome-terminal preferences window. I know the theme is solid tho, so this must be on my end.

**Comment by rilian-la-te** [comment]
This is theme issue. Ask its creator:) Maybe you use wrong GTK version. So,closing this.
