### ISSUE TITLE
Cannot build package in Arch

### ISSUE THREAD

**Issue by jp1995** [rilian-la-te/vala-panel-appmenu#52]
running makepkg in ~/vala-panel-appmenu/archlinux/ works until: 

```
==> Starting prepare()...
rm: cannot remove '/home/johan/vala-panel-appmenu/archlinux/src/vala-panel-appmenu/vapi/glib-2.0.vapi': No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
```

I'm aware the package is in the AUR. I'd like to compile it myself if possible.

Thank you!

**Comment by rilian-la-te** [comment]
Get PKGBUILD from AUR and make pull request from it:) This PKGBUILD is broken.

**Comment by rilian-la-te** [comment]
I just too lazy to copy my PKGBUILD to github:)

**Comment by jp1995** [comment]
Alright, thanks

**Comment by rilian-la-te** [comment]
Just updated it myself, you can download and try to build now:)
