### ISSUE TITLE
[mate-panel] Applet binary not called when adding applet to panel.

### ISSUE THREAD

**Issue by IKRadulov** [rilian-la-te/vala-panel-appmenu#56]
Since I  have not recompiled the applet for a month when I modified the pkgbuild for arch I updated the packages .After recompiling I noticed that mate factory doesn't call the binary file . I checked the factory file but the Exec line has the  proper path . Then I tried rebuilding with old pkgbuild and same thing happens . Any thoughts on this ? Shoudn't there be a dbus service file along with the factory file?

**Comment by rilian-la-te** [comment]
Fixed.
