### ISSUE TITLE
Unable to build from AUR

### ISSUE THREAD

**Issue by Meitoncz** [rilian-la-te/vala-panel-appmenu#57]
Hi,

I have this issue where INSTALL cannot find appmenu-mate.service, but the file is actually available if I check the destination. Please see the bellow.

-- Install configuration: ""
-- Installing: /tmp/yaourt-tmp-meiton/aur-vala-panel-appmenu-valapanel-git/pkg/vala-panel-appmenu-xfce-git/usr/share/xfce4/panel/plugins/appmenu.desktop
CMake Error at cmake_install.cmake:56 (file):
  file INSTALL cannot find
  "/tmp/yaourt-tmp-meiton/aur-vala-panel-appmenu-valapanel-git/src/vala-panel-appmenu/data/appmenu-mate.service".

make: *** [Makefile:84: install] Error 1
make: Leaving directory '/tmp/yaourt-tmp-meiton/aur-vala-panel-appmenu-valapanel-git/src/vala-panel-appmenu/data'
==> ERROR: A failure occurred in package_vala-panel-appmenu-xfce-git().
    Aborting...
==> ERROR: Makepkg was unable to build vala-panel-appmenu-xfce-git.
==> Restart building vala-panel-appmenu-valapanel-git ? [y/N]
==> ---------------------------------------------------------
==> ^C
[meiton@meiton-pc ~]$ 
[meiton@meiton-pc ~]$ 
[meiton@meiton-pc ~]$ 
[meiton@meiton-pc ~]$ cd /tmp/yaourt-tmp-meiton/aur-vala-panel-appmenu-valapanel-git/src/vala-panel-appmenu/data/
[meiton@meiton-pc data]$ 
[meiton@meiton-pc data]$ 
[meiton@meiton-pc data]$ ls -al
total 60
drwxr-xr-x  3 meiton meiton  340  1. dub 18.28 .
drwxr-xr-x 13 meiton meiton  440  1. dub 18.28 ..
-rw-r--r--  1 meiton meiton  302  1. dub 18.28 appmenu.desktop
-rw-r--r--  1 meiton meiton   96  1. dub 18.28 appmenu.desktop.plugin.in
-rw-r--r--  1 meiton meiton  177  1. dub 18.28 appmenu.desktop.xfce.in
-rw-r--r--  1 meiton meiton  265  1. dub 18.28 appmenu-mate.desktop
-rw-r--r--  1 meiton meiton  236  1. dub 18.28 appmenu-mate.desktop.in
-rw-r--r--  1 meiton meiton  255  1. dub 18.28 appmenu-mate.desktop.plugin.in
-rw-r--r--  1 meiton meiton  255  1. dub 18.28 appmenu-mate.plugin
-rw-r--r--  1 meiton meiton  102  1. dub 18.28 appmenu-mate.serivce
-rw-r--r--  1 meiton meiton  121  1. dub 18.28 appmenu-mate.service.in
-rw-r--r--  1 meiton meiton  225  1. dub 18.28 appmenu.plugin
drwxr-xr-x  2 meiton meiton   80  1. dub 18.28 CMakeFiles
-rw-r--r--  1 meiton meiton 4042  1. dub 18.28 cmake_install.cmake
-rw-r--r--  1 meiton meiton  944  1. dub 18.28 CMakeLists.txt
-rw-r--r--  1 meiton meiton  387  1. dub 18.28 CTestTestfile.cmake
-rw-r--r--  1 meiton meiton 7542  1. dub 18.28 Makefile
[meiton@meiton-pc data]$ 

Any tips how to fix it?
By the way, it is amazing plugin, I am using it on my desktop already, great work! :)

Many thanks.

Meiton

**Comment by rilian-la-te** [comment]
Will look for it tomorrow.

**Comment by rilian-la-te** [comment]
Just typo - used russian A.

**Comment by IKRadulov** [comment]
The error is in  "vala-panel-appmenu/data/CMakeLists.txt"  . A typo error .

**Comment by Meitoncz** [comment]
Hi again,

It fixed the issue, however I am having another issue now.

==> Continue installing vala-panel-appmenu-xfce-git ? [Y/n]
==> [v]iew package contents [c]heck package with namcap
==> ---------------------------------------------------
==> 

loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (4) vala-panel-appmenu-mate-git-0.3.3.r2.gc698ed7-1  vala-panel-appmenu-translations-git-0.3.3.r2.gc698ed7-1
             vala-panel-appmenu-valapanel-git-0.3.3.r2.gc698ed7-1  vala-panel-appmenu-xfce-git-0.3.3.r2.gc698ed7-1

Total Installed Size:  0,52 MiB

:: Proceed with installation? [Y/n] 
(4/4) checking keys in keyring                                                          [##################################################] 100%
(4/4) checking package integrity                                                        [##################################################] 100%
(4/4) loading package files                                                             [##################################################] 100%
(4/4) checking for file conflicts                                                       [##################################################] 100%
error: failed to commit transaction (conflicting files)
/usr/share/dbus-1/services/org.mate.panel.applet.AppmenuAppletFactory.service exists in both 'vala-panel-appmenu-mate-git' and 'vala-panel-appmenu-xfce-git'
Errors occurred, no packages were upgraded.
==> WARNING: Your packages are saved in /tmp/yaourt-tmp-meiton
cp: overwrite '/tmp/yaourt-tmp-meiton/vala-panel-appmenu-mate-git-0.3.3.r2.gc698ed7-1-x86_64.pkg.tar.xz'? 
cp: overwrite '/tmp/yaourt-tmp-meiton/vala-panel-appmenu-translations-git-0.3.3.r2.gc698ed7-1-any.pkg.tar.xz'? 
cp: overwrite '/tmp/yaourt-tmp-meiton/vala-panel-appmenu-valapanel-git-0.3.3.r2.gc698ed7-1-x86_64.pkg.tar.xz'? 
cp: overwrite '/tmp/yaourt-tmp-meiton/vala-panel-appmenu-xfce-git-0.3.3.r2.gc698ed7-1-x86_64.pkg.tar.xz'? 
[meiton@meiton-pc ~]$ 
[meiton@meiton-pc ~]$ cd /usr/share/dbus-1/services
[meiton@meiton-pc services]$ ls -al
total 148
drwxr-xr-x 2 root root 4096  1. dub 17.24 .
drwxr-xr-x 8 root root 4096  1. dub 16.17 ..
-rw-r--r-- 1 root root   69 25. pro 18.00 blueman-applet.service
-rw-r--r-- 1 root root   70 28. čec  2016 ca.desrt.dconf.service
-rw-r--r-- 1 root root   92  3. srp  2016 gnome-vfs-daemon.service
-rw-r--r-- 1 root root  120 26. zář  2016 org.a11y.Bus.service
-rw-r--r-- 1 root root  114  2. lis 11.04 org.ayatana.bamf.service
-rw-r--r-- 1 root root   95 27. úno 17.47 org.bluez.obex.service
-rw-r--r-- 1 root root   86 27. led 08.18 org.fedoraproject.Config.Printing.service
-rw-r--r-- 1 root root  123 24. lis 14.21 org.freedesktop.ColorHelper.service
-rw-r--r-- 1 root root  122 30. zář  2016 org.freedesktop.secrets.service
lrwxrwxrwx 1 root root   51 28. led 23.32 org.freedesktop.systemd1.service -> ../system-services/org.freedesktop.systemd1.service
-rw-r--r-- 1 root root   66  9. srp  2016 org.gnome.GConf.service
-rw-r--r-- 1 root root   86 23. říj 01.47 org.gnome.keyring.PrivatePrompter.service
-rw-r--r-- 1 root root  116 30. zář  2016 org.gnome.keyring.service
-rw-r--r-- 1 root root   85 23. říj 01.47 org.gnome.keyring.SystemPrompter.service
-rw-r--r-- 1 root root  127 24. zář  2016 org.gtk.GLib.PACRunner.service
-rw-r--r-- 1 root root  141 22. pro 00.41 org.gtk.vfs.AfcVolumeMonitor.service
-rw-r--r-- 1 root root  100 22. pro 00.41 org.gtk.vfs.Daemon.service
-rw-r--r-- 1 root root  152 22. pro 00.41 org.gtk.vfs.GPhoto2VolumeMonitor.service
-rw-r--r-- 1 root root  113 22. pro 00.41 org.gtk.vfs.Metadata.service
-rw-r--r-- 1 root root  140 22. pro 00.41 org.gtk.vfs.MTPVolumeMonitor.service
-rw-r--r-- 1 root root  152 22. pro 00.41 org.gtk.vfs.UDisks2VolumeMonitor.service
-rw-r--r-- 1 root root   63 25. pro 18.45 org.hexchat.service.service
-rw-r--r-- 1 root root   78 17. bře 20.38 org.mate.Engrampa.service
-rw-r--r-- 1 root root  100 17. bře 21.14 org.mate.panel.applet.ClockAppletFactory.service
-rw-r--r-- 1 root root   98 17. bře 21.14 org.mate.panel.applet.FishAppletFactory.service
-rw-r--r-- 1 root root  123 17. bře 21.14 org.mate.panel.applet.NotificationAreaAppletFactory.service
-rw-r--r-- 1 root root   95 17. bře 21.14 org.mate.panel.applet.WnckletFactory.service
-rw-r--r-- 1 root root   56  7. kvě  2016 org.xfce.calendar.service
-rw-r--r-- 1 root root   72 14. úno 04.32 org.xfce.FileManager.service
-rw-r--r-- 1 root root   56  7. kvě  2016 org.xfce.orage.service
-rw-r--r-- 1 root root   67 14. úno 04.32 org.xfce.Thunar.service
-rw-r--r-- 1 root root   88 23. pro 06.36 org.xfce.Tumbler.Cache1.service
-rw-r--r-- 1 root root   90 23. pro 06.36 org.xfce.Tumbler.Manager1.service
-rw-r--r-- 1 root root   94 23. pro 06.36 org.xfce.Tumbler.Thumbnailer1.service
-rw-r--r-- 1 root root  130 14. úno 05.01 org.xfce.xfce4-notifyd.Notifications.service
-rw-r--r-- 1 root root   72 24. říj 17.57 org.xfce.Xfconf.service
[meiton@meiton-pc services]$

**Comment by IKRadulov** [comment]
I submitted a patch . 
change package_vala-panel-appmenu-xfce-git to
---
package_vala-panel-appmenu-xfce-git() {
  pkgdesc="AppMenu (Global Menu) plugin for xfce4-panel"
  depends=('gtk3' 'bamf>=0.5.0' 'xfce4-panel>=4.11.2' 'xfconf' 'libwnck3')
  optdepends=('gtk2-ubuntu: for hiding gtk2 menus'
            'unity-gtk-module: for gtk2/gtk3 menus'
            'gtk2-appmenu: for gtk2 menus, alternate way'
            'gtk3-appmenu: for gtk3 menus, alternate way'
            'appmenu-qt: for qt4 menus'
            'appmenu-qt5: for qt5 menus')
  cd "${srcdir}/${_pkgbase}"
  make -C "lib" DESTDIR="${pkgdir}" install
  make -C "data" DESTDIR="${pkgdir}" install
  rm -rf "${pkgdir}/usr/lib/vala-panel"
  rm -rf "${pkgdir}/usr/lib/mate-panel"
  rm -rf "${pkgdir}/usr/share/mate-panel"
  rm -rf "${pkgdir}/usr/share/dbus-1"
}
---

**Comment by Meitoncz** [comment]
I have no idea how to use the code which you provided, could you please help me?
I was trying to add it to PKGBUILD, but I don´t think this is the way how to use it, right?

**Comment by IKRadulov** [comment]
Just add --- rm -rf "${pkgdir}/usr/share/dbus-1" --- at the end of package_vala-panel-appmenu-xfce-git() in the braces.

**Comment by IKRadulov** [comment]
Merged in master now !

**Comment by Meitoncz** [comment]
It works! Many thanks for quick actions. :)
