### ISSUE TITLE
Arch/Mate 1.18 - GTK apps have visible menu bar

### ISSUE THREAD

**Issue by adamjedlicka** [rilian-la-te/vala-panel-appmenu#60]
For example in Caja or Mate terminal menu bar is still visible even though vala-panel-appmenu is enabled and functioning properly. And if I choose to hide menu-bar in Mate terminal global menu-bar disappears too.

screenshots: http://imgur.com/a/MRAI4

**Comment by rilian-la-te** [comment]
Because patch not upstreamed yet.
You need a workaround:
To ~/.config/gtk-3.0/settings.ini
```
[Settings]
gtk-shell-shows-app-menu=true
gtk-shell-shows-menubar=true
```

**Comment by adamjedlicka** [comment]
Yeah that helped. I didn't have [Settings] header in the settings.ini. It's missing from your readme.

Also this breaks Mate Menu Bar (Applications, Places, System menus). Do you think it's a bug or is it intentionally caused by those two commands?

BTW Thank you so much for this application. Only properly working menu bar out there <3

**Comment by rilian-la-te** [comment]
Show me a screen, please.

**Comment by rilian-la-te** [comment]
It is upstream issue, so, closing this.
