### ISSUE TITLE
budgie support

### ISSUE THREAD

**Issue by fossfreedom** [rilian-la-te/vala-panel-appmenu#61]
Hi - more of a curiosity - I note in the README that this supports budgie 10.x - but I dont see any corresponding makefile, budgie-plugin files etc.  Mistake?  or a future aspiration?

**Comment by rilian-la-te** [comment]
Yes, I was planning it, but abandoned for now. Feel free to implement (you can take xfce4-sntray-plugin as example).

**Comment by fossfreedom** [comment]
@rilian-la-te sounds exciting!  Can you give me a hint please how I can compile this project just for budgie applet support - dont want to compile xfce etc - thanks in advance.

**Comment by rilian-la-te** [comment]
```
mkdir build
cd build
cmake .. -DENABLE_XFCE=OFF -DENABLE_MATE=OFF -DENABLE_VALAPANEL=OFF -DENABLE_BUDGIE=ON -DENABLE_UNITY_GTK_MODULE=ON
make
sudo make install
```

**Comment by fossfreedom** [comment]
thanks.  I've added also -DCMAKE_INSTALL_PREFIX:PATH=/usr because stuff was being installed in /usr/local

However the budgie-desktop plugin libraries are being installed in /usr/lib/x86_64_linux_gnu/budgie-desktop instead of /usr/lib/budgie-desktop

Is there another cmake parameter to not install in the multiarch location?

BTW installing with ubuntu 17.04

**Comment by rilian-la-te** [comment]
You can try change CMAKE_INSTALL_LIBDIR

**Comment by fossfreedom** [comment]
think I'm almost there - I'm seeing this error:

```
dad@dad-VirtualBox:~/Downloads/vala-panel-appmenu-0.2.8/build$ sudo make install
[ 17%] Built target appmenu-gtk3-parser
[ 34%] Built target appmenu-gtk2-parser
[ 40%] Built target appmenu-gtk2-module
[ 45%] Built target appmenu-gtk3-module
[ 48%] Built target vala-dbusmenu
[ 54%] Built target appmenu-core
[100%] Built target appmenu-budgie
[100%] Built target i18n
Install the project...
-- Install configuration: ""
-- Installing: /usr/include/appmenu-gtk-module/unity-gtk-parser.h
-- Installing: /usr/include/appmenu-gtk-module/unity-gtk-menu-shell.h
-- Installing: /usr/include/appmenu-gtk-module/unity-gtk-action-group.h
-- Installing: /usr/share/glib-2.0/schemas/org.valapanel.appmenu-gtk-module.gschema.xml
-- Compiling GSettings schemas
-- Up-to-date: /lib/systemd/system/appmenu-gtk-module.service
CMake Error at unity-gtk-module/data/cmake_install.cmake:68 (file):
  file INSTALL cannot find
  "/home/dad/Downloads/vala-panel-appmenu-0.2.8/unity-gtk-module/data/appmenu-gtk3-parser.pc".
Call Stack (most recent call first):
  unity-gtk-module/cmake_install.cmake:45 (include)
  cmake_install.cmake:37 (include)


Makefile:83: recipe for target 'install' failed
make: *** [install] Error 1
dad@dad-VirtualBox:~/Downloads/vala-panel-appmenu-0.2.8/build$ 
```

**Comment by rilian-la-te** [comment]
just write -DENABLE_UNITY_GTK_MODULE=OFF, as you in Ubuntu, you can install your own unity-gtk-module

**Comment by fossfreedom** [comment]
ok - thanks.

when I add the applet to the budgie-panel the whole panel crashes.

this is a gdb backtrace.  any thoughts?

https://pastebin.com/cmqVYSWs

**Comment by rilian-la-te** [comment]
I need to test it myself. Wait a bit, please.

**Comment by rilian-la-te** [comment]
Try latest master. And theme is incorrect.
I don't know CSS well, so budgie-compatible theme is in your hands.

**Comment by fossfreedom** [comment]
awesome.  many - many thanks :)

**Comment by fossfreedom** [comment]
@rilian-la-te had a quick look at the CSS stuff.  If I change line 60 class string https://github.com/rilian-la-te/vala-panel-appmenu/blob/master/lib/menu-widget.vala to "budgie-polkit-dialog" then the theming for the global menu's dropdowns work correctly for budgie's inbuilt system theme.  The panel menu items remains though crunched together.

On the other hand - leaving line 60 as is and changing the raven "inbuilt theme" to off (i.e. use the current GTK arc-theme for the panel) - the global menu options are correctly spaced.

unfortunately I can't use GTK Inspector to look at the styles and structure of the global menu because the focus to the inspector window changes the appmenu to the inspector window ... difficult to diagnose this theming with budgie's inbuilt panel theme.  Anyway - thought I'd drop this an initial investigation.

**Comment by rilian-la-te** [comment]
You can add budgie hacks to https://github.com/rilian-la-te/vala-panel-appmenu/blob/master/lib/budgie-plugin-appmenu.vala.

**Comment by rilian-la-te** [comment]
And made a pull request.
