### ISSUE TITLE
gtk2 application in fedora

### ISSUE THREAD

**Issue by raveit65** [rilian-la-te/vala-panel-appmenu#64]
Hi, i've created a first spec file for a rpm for official fedora-26.
It is working fine exept for gtk2 applications, tested with xchat, claws-mail and exaile.
I used vala-panel-appmenu from master with appmenu-gtk-modul to avoid running in fedora issue with unity-gtk-module.
My spec file (a bit simpler than yours):
https://www.dropbox.com/s/bgupgfcv3gy3mvl/vala-panel-appmenu.spec?dl=0
Installed is:
appmenu-gtk-module-0.4.4-1.fc26.x86_64.rpm
libappmenu-gtk-parser-0.4.4-1.fc26.x86_64.rpm
mate-applet-vala-panel-appmenu-0.4.4-1.fc26.x86_64.rpm
```
[rave@mother ~]$ env | grep GTK_MODULES
GTK_MODULES=gail:atk-bridge:appmenu-gtk-module
[rave@mother ~]$ env | grep UBUNTU
UBUNTU_MENUPROXY=1
```
```
[rave@mother ~]$ gsettings get org.valapanel.appmenu-gtk-module 
blacklist                 gtk2-shell-shows-menubar  whitelist
[rave@mother ~]$ gsettings get org.valapanel.appmenu-gtk-module gtk2-shell-shows-menubar
true
[rave@mother ~]$ gsettings get org.mate.interface gtk-shell-shows-app-menu
true
[rave@mother ~]$ gsettings get org.mate.interface gtk-shell-shows-menubar
true
```
I thought vala-panel-appmenu would work with own modul or isn't this ready yet ?
With kaffeine it works nicely here.
And what about applications running as root or sudo?
```
[root@mother rave]# env | grep GTK_MODULES
GTK_MODULES=appmenu-gtk-module
[root@mother rave]# env | grep UBUNTU
UBUNTU_MENUPROXY=1
[root@mother rave]# 
```
At least this more a help call than a bug report ;-)

**Comment by rilian-la-te** [comment]
What issue are you have exactly with GTK2 applications?

**Comment by rilian-la-te** [comment]
Do you build gtk2 version of module?

**Comment by rilian-la-te** [comment]
About root - no, root not working (and this is protocol limitation for now)

**Comment by raveit65** [comment]
With gtk2 applications the menubar is displayed in application windows and not in panel.
And yes, those files are installed, imo.
```
[rave@mother ~]$ rpm -ql appmenu-gtk-module
/etc/profile.d/appmenu-gtk-module.csh
/etc/profile.d/appmenu-gtk-module.sh
/usr/lib/systemd/user/appmenu-gtk-module.service
/usr/lib/systemd/user/default.target.wants
/usr/lib/systemd/user/default.target.wants/mate-applet-vala-panel-appmenu.service
/usr/lib64/gtk-2.0/modules/libappmenu-gtk-module.so
/usr/lib64/gtk-3.0/modules/libappmenu-gtk-module.so
/usr/share/glib-2.0/schemas/org.valapanel.appmenu-gtk-module.gschema.xml
/usr/share/licenses/appmenu-gtk-module
/usr/share/licenses/appmenu-gtk-module/LICENSE

[rave@mother ~]$ rpm -ql libappmenu-gtk-parser
/usr/lib64/libappmenu-gtk2-parser.so.0
/usr/lib64/libappmenu-gtk2-parser.so.0.4.4
/usr/lib64/libappmenu-gtk3-parser.so.0
/usr/lib64/libappmenu-gtk3-parser.so.0.4.4
/usr/share/licenses/libappmenu-gtk-parser
/usr/share/licenses/libappmenu-gtk-parser/LICENSE

[rave@mother ~]$ rpm -ql mate-applet-vala-panel-appmenu
/usr/lib64/mate-panel/appmenu-mate
/usr/share/dbus-1/services/org.mate.panel.applet.AppmenuAppletFactory.service
/usr/share/doc/mate-applet-vala-panel-appmenu
/usr/share/doc/mate-applet-vala-panel-appmenu/README.md
/usr/share/licenses/mate-applet-vala-panel-appmenu
/usr/share/licenses/mate-applet-vala-panel-appmenu/LICENSE
/usr/share/locale/aa/LC_MESSAGES/vala-panel-appmenu.mo
.....
cut
```

**Comment by rilian-la-te** [comment]
Do you see any errors in console when running gtk2 app?

**Comment by rilian-la-te** [comment]
And where is other gtk2 modules (like atk-bridge) placed?

**Comment by raveit65** [comment]
Weird, if i start those apps from terminal than the menubar is in panel, but from normal men it does not work.
claws-mail or xchat report only warnings not related to vala-panel-appmenu
```
[rave@mother ~]$ claws-mail 
** (claws-mail:25999): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
exaile displays a weird error if i select the menus in panel
```
[rave@mother ~]$ exaile
INFO    : Loading Exaile 3.4.5 on Python 2.7.13...
INFO    : Loading settings...
INFO    : Using de_DE UTF-8 locale

** (exaile.py:25341): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
INFO    : Loading plugins...
INFO    : Loading collection...
WARNING : Exception occurred while loading /home/rave/.local/share/exaile/music.db
WARNING : Exception occurred while loading /home/rave/.local/share/exaile/music.db
WARNING : Exception occurred while loading /home/rave/.local/share/exaile/music.db
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Using GTK+ 2.24.31
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
INFO    : WARNING: could not open podcast file
/usr/share/exaile/xlgui/widgets/menu.py:86: GtkWarning: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
  item.set_submenu(submenu)

** (exaile.py:25341): WARNING **: (/home/rave/rpmbuild/BUILD/vala-panel-appmenu-0.4.4/unity-gtk-module/lib/unity-gtk-action-group.c:1029):unity_gtk_action_group_disconnect_item: code should not be reached

** (exaile.py:25341): WARNING **: (/home/rave/rpmbuild/BUILD/vala-panel-appmenu-0.4.4/unity-gtk-module/lib/unity-gtk-action-group.c:1029):unity_gtk_action_group_disconnect_item: code should not be reached
/usr/share/exaile/xlgui/widgets/menu.py:248: GtkWarning: gtk_menu_detach(): menu is not attached
  c.remove_submenu()
```
But exaile's menu is in panel if starting from terminal.

**Comment by rilian-la-te** [comment]
Seems than GTK_MODULES is not loaded from session shell, but loaded from terminal. You need a Fedora-specific way to enforce it. You may look to unity-project-packages repository for help.

**Comment by rilian-la-te** [comment]
https://github.com/rilian-la-te/vala-project-packages/blob/master/archlinux/vala-panel-appmenu-xfce-git/80appmenu-gtk-module

You may try to install this file with package.

**Comment by raveit65** [comment]
I used this from opensuse
```
[root@mother rave]# cat /etc/profile.d/appmenu-gtk-module.sh 
if [ -z "$GTK_MODULES" ]; then
    export GTK_MODULES="appmenu-gtk-module"
else
    export GTK_MODULES="$GTK_MODULES:appmenu-gtk-module"
fi
if [ -z "$UBUNTU_MENUPROXY" ]; then
    export UBUNTU_MENUPROXY=1
fi
[root@mother rave]# cat /etc/profile.d/appmenu-gtk-module.csh 
if ( -z "$GTK_MODULES" ) then
    setenv GTK_MODULES "appmenu-gtk-module"
else
    setenv GTK_MODULES "${GTK_MODULES}:appmenu-gtk-module"
endif
if ( -z "$UBUNTU_MENUPROXY" ) then
    setenv UBUNTU_MENUPROXY 1
fi
```
Is this wrong?

**Comment by rilian-la-te** [comment]
No, AFAIK. What login manager are you using, and what shell user have?

**Comment by raveit65** [comment]
Using your file does not make any different, same results, gt3 apps OK, gtk2 apps ok only from terminal.

[root@mother rave]# rpm -qa lightdm
lightdm-1.18.3-2.fc26.x86_64

[root@mother rave]# rpm -qa lightdm-gtk
lightdm-gtk-2.0.2-4.fc26.x86_64

[root@mother rave]# rpm -qa bash
bash-4.4.12-1.fc26.x86_64

**Comment by rilian-la-te** [comment]
Try to dropping my file to /etc/X11/xinit/xinitrc.d/

**Comment by rilian-la-te** [comment]
So, it is working?

**Comment by raveit65** [comment]
No, same result with putting this file to /etc/X11/xinit/xinitrc.d/
```
[rave@mother ~]$ cat /etc/X11/xinit/xinitrc.d/80-appmenu-gtk-module.sh 
#!/bin/bash

if [ -n "$GTK_MODULES" ]; then
    GTK_MODULES="${GTK_MODULES}:appmenu-gtk-module"
else
    GTK_MODULES="appmenu-gtk-module"
fi

if [ -z "$UBUNTU_MENUPROXY" ]; then
    UBUNTU_MENUPROXY=1
fi

export GTK_MODULES
export UBUNTU_MENUPROXY

```
Well, i will give a rebuild of fedora unty-gtk-modul with your patch from report a try the next days, and see how it works.
Maintainer is a friend of mine, than i can ask him for help if it does not work.

**Comment by rilian-la-te** [comment]
Wait a bit, I will install Fedora in virtual environment and try to install appmenu-gtk-module.

**Comment by raveit65** [comment]
I think i found the problem.
```
/usr/lib/systemd/user/appmenu-gtk-module.service
/usr/lib/systemd/user/default.target.wants/mate-applet-vala-panel-appmenu.service
```
The symlink from default.target expect '/usr/lib/systemd/user/mate-applet-vala-panel-appmenu.service as target.

**Comment by rilian-la-te** [comment]
It works after changing to right target? If yes, can you submit your spec as PR to spec.in file? Is your spec usable on non-fedora RPM distros (Mageia, OpenSUSE)?

**Comment by rilian-la-te** [comment]
And I am against collecting GTK2 and GTK3 libraries in one package. It is not good for building a GTK3-only system.

**Comment by raveit65** [comment]
> And I am against collecting GTK2 and GTK3 libraries in one package. It is not good for building a GTK3-only system.

Don't worry, at the moment i don't get it working, so i am far away from building it for fedora.
Now with patched gtk-untity-module from fedora and new rpm from latest release which includes only
```
%files -f %{internal_name}.lang
%doc README.md
%license LICENSE
%{_datadir}/dbus-1/services/org.mate.panel.applet.AppmenuAppletFactory.service
%{_datadir}/mate-panel/applets/org.vala-panel.appmenu.mate-panel-applet
%{_libdir}/mate-panel/appmenu-mate
%config %{_sysconfdir}/profile.d/%{module_name}.*
```
```
[rave@mother ~]$ env | grep GTK_MODULES
GTK_MODULES=gail:atk-bridge:unity-gtk-module
```
It works only if i start an app from terminal and i get those weird warning
``
[rave@mother ~]$ pluma
Gtk-Message: Failed to load module "appmenu-gtk-module"
```

I have no ideas any more......

**Comment by rilian-la-te** [comment]
>It works only if i start an app from terminal and i get those weird warning

This warning must be removed after removing appmenu-gtk-module package.
OK, I will address it this evening.


> Now with patched gtk-untity-module from fedora and new rpm from latest release which includes only

Two modules (patched unity and appmenu) are identical. For now.

**Comment by raveit65** [comment]
```
[root@mother rave]# ls -l /usr/lib64/gtk-2.0/modules
insgesamt 532
-rwxr-xr-x 1 root root   6728 21. Mär 11:12 libatk-bridge.so
-rwxr-xr-x 1 root root  27408 11. Feb 02:46 libcanberra-gtk-module.so
-rwxr-xr-x 1 root root  35944 10. Feb 08:35 libcaribou-gtk-module.so
-rwxr-xr-x 1 root root  61048 10. Feb 21:20 libferret.so
-rwxr-xr-x 1 root root 376632 10. Feb 21:20 libgail.so
-rwxr-xr-x 1 root root   6640 24. Mär 11:08 libpk-gtk-module.so
-rwxr-xr-x 1 root root  24264 17. Apr 08:02 libunity-gtk-module.so
[root@mother rave]# ls -l /usr/lib64/gtk-3.0/modules
insgesamt 108
-rwxr-xr-x 1 root root 27368 11. Feb 02:46 libcanberra-gtk3-module.so
lrwxrwxrwx 1 root root    26 11. Feb 02:46 libcanberra-gtk-module.so -> libcanberra-gtk3-module.so
-rwxr-xr-x 1 root root 35952 10. Feb 08:35 libcaribou-gtk-module.so
-rwxr-xr-x 1 root root 15240 24. Mär 11:08 libpk-gtk-module.so
-rwxr-xr-x 1 root root 28440 17. Apr 08:02 libunity-gtk-module.so
```
They are removed, immo

**Comment by rilian-la-te** [comment]
What about support files?

**Comment by raveit65** [comment]
Ok, same rpms are working fine in f26 VM :-)
Menubars are in panel with gtk3 and gtk2 apps out of box.
Now i need to find out what is wrong here with my main box :-/
What do you mean with 'support files' ?

Btw. i think the patch in fedora report should be updated. Better not to enable it as default, same as with mate gsettings keys.    imo.....

**Comment by rilian-la-te** [comment]
Mate gsettings keys is not enabled by default:) And if you want, add override to unity-gtk-module or appmenu-gtk-module. Can you test appmenu-gtk-module on VM?

**Comment by raveit65** [comment]
I meant
```
[rave@mother ~]$ gsettings get com.canonical.unity-gtk-module gtk2-shell-shows-menubar
true
```
> Can you test appmenu-gtk-module on VM?

Sure, after i have fixed my main box.....

> What about support files?

What do you mean with 'support files' ?

**Comment by rilian-la-te** [comment]
> What do you mean with 'support files' ?
For example, /etc/x11/xinit/xinit.rc.d/80appmenu-gtk-module.

Or another profile scripts and systemd units.


And second step: check all support files in unity-gtk-module, and try to replicate it in your package of appmenu-gtk-module.

**Comment by raveit65** [comment]
The warning i could solved, it was an remnant from mate-panel PR where we load the module via ~.config/gtk-3.0/settings.ini.
```
[Settings]
gtk-modules = unity-gtk-module:gail:atk-bridge
```
But removing this file does not solved the issue on bare metal box.
I see the menubars only in panel if i start applications from terminal.
And i use same rpms as in VM.
Sadly i have no ideas any more to debug this.
....i hat to work like try&error, without knowing where i have to look....
All looks OK:
```
[rave@mother ~]$ systemctl --user list-units | grep unity
unity-gtk-module.service                                                                         loaded active exited  Unity GTK Module Environment variables 

[rave@mother ~]$ systemctl --user list-units | grep bamf
bamfdaemon.service                                                                               loaded active running BAMF Application Matcher Framework

[rave@mother ~]$ env | grep GTK_MODULES
GTK_MODULES=gail:atk-bridge:unity-gtk-module
[rave@mother ~]$ env | grep UBUNTU
UBUNTU_MENUPROXY=1
```

**Comment by rilian-la-te** [comment]
What differences are you have in login sequence against VM Fedora?

**Comment by raveit65** [comment]
With another user account it is working like a charm on bare metal :-)
So what the hell is different in my home folder......

**Comment by raveit65** [comment]
huh, resetting dconf fixes the issue.
This is bad as it indicates a conflicting setting somewhere.

**Comment by raveit65** [comment]
gsettings reset-recursively org.mate.interface
fixes the problem. For some reasons resetting a few keys by hand didn't help.
Ie. those were enabled in my setup
```
org.mate.interface gtk-shell-shows-app-menu true
org.mate.interface gtk-shell-shows-menubar true
```
All other keys except gtk-theme key weren't enabled.

Ok, all fine now....... i will test appmenu-gtk-module later....
...need a break.

**Comment by raveit65** [comment]
A rpm with appmenu-gtk-module works fine now.
I only patched the systemd unit a bit.
https://www.dropbox.com/s/zpihyvqylsu1jq3/mate-applet-vala-panel-appmenu-0.4.5-1.fc26.src.rpm?dl=0

The only thing i don't understand why i need a systemd unit enable by a target, if it doesn't work without
a env var loading with /etc/profiles.d/file.sh ?

**Comment by rilian-la-te** [comment]
Can you make a PR against systemd unit?
About profile things - you forgot about gentoo. It uses OpenRC. 
Do you tried to remove profile things?

**Comment by raveit65** [comment]
> Can you make a PR against systemd unit?

Done!

> Do you tried to remove profile things?

Without using /etc/profiles.d or /etc/X11/xinit/xinitrc.d the module don't load.

Btw. after all that testing i found a show stopper related to unity-gtk-module :-/
Only loading it without installing your applet breaks caja canvas.
https://www.dropbox.com/s/vlj54h1yvdiys2j/unity-gtk-module-fedora.ogv?dl=0

**Comment by rilian-la-te** [comment]
I do not see any issue. Can you show it in Red square, please? And post a bug here with label prefix Gtk Module, please.

**Comment by raveit65** [comment]
It's the background of the draged icon, normally this is transparent.
It is confirmed by our opensuse maintainer.

**Comment by rilian-la-te** [comment]
But how unity-gtk-module affects desktop?

**Comment by raveit65** [comment]
It's not only the desktop dir in caja, same with all other dirs in caja-browser using icon-view modus.
Btw. i can reproduce this in ubuntu-17.04 too.
@flexiondotorg ^^^^
I think it's better you handle this issue as it is probably a issue with unity-modul, and/or caja, and or gtk+-3.22.

**Comment by rilian-la-te** [comment]
And me must handle it too, AFAIK.

**Comment by flexiondotorg** [comment]
@raveit65 I'm testing `vala-panel-appmenu` 0.4.3 on Ubuntu MATE 17.10 and I see that same issue with dragging icons around the desktop and within Caja itself.

**Comment by flexiondotorg** [comment]
@rilian-la-te @raveit65 I'm also seeing the issue where no GTK2+ have a global menu. I'm using the Ubuntu packages for `unity-gtk2-module` and `unity-gtk3-module`.

**Comment by rilian-la-te** [comment]
Did unity-gtk2-module is loaded? What Ubuntu version are you used?

**Comment by fossfreedom** [comment]
@rilian-la-te this issue seems to have gone rather quiet :(

Testing v0.5.3 that Martin has uploaded on Ubuntu Budgie 17.10.  GTK2 apps like hexchat don't work.  GTK3 apps work just fine.  I've done the .gtkrc, .profile and .bashrc tweaks as per the Ubuntu section in the README.  no joy.  Anything else to look out for?

**Comment by rilian-la-te** [comment]
You tried appmenu-gtk-module and others? What did not work?

**Comment by fossfreedom** [comment]
For gtk 2 apps the global menu works. However, the same menu appears within the app so the user sees both a global menu and the same application menu within the app.

**Comment by rilian-la-te** [comment]
appmenu-gtk-module or unity-gtk-module?

**Comment by fossfreedom** [comment]
I presume I am using the unity gtk 2 and gtk3 modules. That is what is installed by Martin's package

**Comment by rilian-la-te** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1387884

To workaround use appmenu-gtk-module or patch provided.

**Comment by rilian-la-te** [comment]
Sorry, confused with fedora. But anyway, try appmenu-gtk-module, it can be same bug.

**Comment by flexiondotorg** [comment]
I have discovered that applications launched via `mate-panel` menus/launchers do not display the global menu. However, opening a terminal with the `Ctrl` + `Alt` +`t` keybinding and then executing the same application the Global Menus are present.

Firefox, Thunderbird, LibreOffice always work regardless of how they are launched.

**Comment by rilian-la-te** [comment]
Look for environment variables then. Because you do not have set some, when
started from mate-panel, but set it in bashrc. This is misconfiguration

**Comment by rilian-la-te** [comment]
Show me a env, when you launched mate-terminal from mate-panel launcher on such half-configured environment, please.

**Comment by flexiondotorg** [comment]
I did some testing last night. Yes, this is a result of a "half configured" setup. Sadly a "full configured" system presents another issue I'll raise a bug for.

Long story short there was a bug in `mate-session-manager` which is fixed via https://github.com/mate-desktop/mate-session-manager/pull/138 and is released in `mate-session-manager` 1.18.1. Adding the following to `/etc/profile.d/appmenu.sh` will make all GTK2+ and GTK3+ application works with the Global Menu regardless of how applications are launched:

```
if [ -z "$GTK_MODULES" ]; then
    GTK_MODULES="unity-gtk-module"
else
    GTK_MODULES="$GTK_MODULES:unity-gtk-module"
fi
export GTK_MODULES
export UBUNTU_MENUPROXY=1
```

**Comment by rilian-la-te** [comment]
did you tried appmenu-gtk-module? Bug is mine (appmenu side) or not mine?

**Comment by flexiondotorg** [comment]
@rilian-la-te I haven't tested with appmenu-gtk-module yet, that is quite complex to build on Debian and will take some time. But I don't think the GTK2+ global menu not showing is a bug `appmenu-gtk-module` or `unity-gtk-module`, I think it was an upstream MATE issue that was recently fixed.

**Comment by rilian-la-te** [comment]
Maybe. But test with it, please. And with it we finally can port vala-panel-appmenu to upstream Debian:)

**Comment by monsta** [comment]
@flexiondotorg: so, is the fix from https://github.com/mate-desktop/mate-session-manager/pull/138 actually good? I see you've reverted it via patch in Debian and Ubuntu, but later removed that patch, so the fix is back again in the end.

**Comment by flexiondotorg** [comment]
@monsta The fix is good. I'll be updating the Debian packages with the new releases tomorrow and will clean up mate-session-manager.

**Comment by monsta** [comment]
Ok good, so I'll keep it in 1.18 for the next release then 🙂

**Comment by rilian-la-te** [comment]
Closing this, because we have now independent gtk2 handling in appmenu-gtk-module
