### ISSUE TITLE
Please help! How to return appmenus back?

### ISSUE THREAD

**Issue by malbiruk** [rilian-la-te/vala-panel-appmenu#66]
What do I need to do to return menus back in applications, if I don't want to use a panel (I used xfce4-panel extension)?

**Comment by rilian-la-te** [comment]
What DE are you using?

**Comment by malbiruk** [comment]
I already did `xfconf-query -c xsettings -p /Gtk/ShellShowsAppmenu -n -t bool -s false && xfconf-query -c xsettings -p /Gtk/ShellShowsMenubar -n -t bool -s false` and removed `gtk-shell-shows-app-menu=true gtk-shell-shows-menubar=true` from .config/gtk-3.0/settings.ini, but menus didn't return after relogging.
I installed vala-panel appmenu for xfce4-panel via AUR (on Manjaro). And now I have this problem. What should I do?

**Comment by malbiruk** [comment]
I used xfce4-panel without DE (i3wm, if it matters)

**Comment by malbiruk** [comment]
Now I can select a menu item (Alt+F for File, for example) and applications show submenu, but appmenu is just hidden.

**Comment by rilian-la-te** [comment]
Do you use unity-gtk-module or appmenu-gtk-module?

**Comment by malbiruk** [comment]
unity-gtk-module

**Comment by rilian-la-te** [comment]
`/com/canonical/unity-gtk-module/gtk2-shell-shows-menubar` to false

**Comment by malbiruk** [comment]
It worked! Thank you!
