### ISSUE TITLE
Arm based Builds

### ISSUE THREAD

**Issue by eumario** [rilian-la-te/vala-panel-appmenu#68]
Just wanted to post a note, that Vala-Panel-AppMenu, will build on ARM based CPU's under ArchLinux, and possibly others.  Limiting to x86/x64 based CPU's should be changed, to allow for building on other archs.

**Comment by rilian-la-te** [comment]
PKGBUILD issues goes to [Vala Project Packages](https://github.com/rilian-la-te/vala-project-packages)
