### ISSUE TITLE
Budgie: Menu Items not arranged and transparent.

### ISSUE THREAD

**Issue by fossfreedom** [rilian-la-te/vala-panel-appmenu#69]
Hi,
  this is the CSS I applied to each menuitem for my budgie applet "budgie-indicator-applet" -  this is to ensure menuitems are padded correctly.

I've no idea how to apply it in the source for this applet - any hints?

"menuitem {
  background: transparent; \n"
  border-radius: 0; \n"
  padding: 1px 2px 1px 1px; \n"
 text-shadow: none;}
"

then I want to add the style class "budgie-polkit-dialog" for each menuitem

I can't grasp where in the code where you can iterate over each menuitem. Thoughts?

**Comment by rilian-la-te** [comment]
What is budgie-indicator-applet?

About applying - why so many hardcoding.
To prove working, you may add in to your home gtk-3.0.css with class .-vala-panel-appmenu-private.

**Comment by fossfreedom** [comment]
Hi,
 ok I had a play and have got this to give a working (non transparent) global menu.

Does the CSS look ok?  What's the best way to apply this CSS via code?

**Comment by rilian-la-te** [comment]
1. Made this works with any theme (not just budgie-desktop's Arc)
2. Made a class that can be easily applied with css_apply_with_class function.
3. I will include this css to resources of applet.

**Comment by fossfreedom** [comment]
k - well that's the best I can do. Hopefully someone else can sort this out :/

**Comment by rilian-la-te** [comment]
You can write a Vala function that generates a valid CSS for applet. I will try to do it, if I will have some free time and when I release vala-panel 0.4.

**Comment by fossfreedom** [comment]
ok - just giving feedback. have recompiled and installed.  The menu drop-downs remains transparent.

Does it matter that both the private and budgie style classes appear to being applied?

![ubuntu budgie - new development running - oracle vm virtualbox_010](https://cloud.githubusercontent.com/assets/996240/25641128/620280fa-2f8a-11e7-880e-4e86c1c4f03c.jpg)

**Comment by rilian-la-te** [comment]
No, AFAIK, this is because budgie style having lower priority than private, and because menus is on its own GdkWindow. So, I think than I need to find a better way to integrate Budgie classes... 
More tomorrow.

**Comment by rilian-la-te** [comment]
Try now:) If not working, I need to investigate budgie internals...

**Comment by fossfreedom** [comment]
Hi,
 ok - the latest changes have not worked.

However - as you have suggested this must be the budgie internals.

So what I have done to make things work, I have deleted all the budgie bits from appmenu.css

Then I have changed in menu-widget.vala "context.add_class("budgie-menubar");" instead of "context.add_class("-vala-panel-appmenu-private");"

I've moved the CSS into budgie-desktop itself under the class "budgie-menubar" - this works nicely.

What I could not figure out (if you can help please) is how to apply the styleclass "budgie-menubar" from within  budgie-plugin-appmenu.vala. 

The style class must be applied at the object hierarchy level in menu-widget.vala - not at the higher level in budgie-plugin-appmenu.vala

I'm going to-do some more testing with GTK+3.18 budgie-desktop before submitting a PR to ikey

**Comment by rilian-la-te** [comment]
1.-vala-panel-appmenu-private is required.
2. I will try to change the style from menu-widget (but menu-widget is shared, so, no DE-specific changes).
3. I will not care about 3.18. If it works - I will be happy, if not - patches welcome, but no deprecations and use GTK4 migration guide.

**Comment by rilian-la-te** [comment]
Show me a resulted CSS, please (may a slight CSS change will make it work with higher hierarchy). About MenuWidget applying - it is difflicult, because MenuWidget is a base class for all menubars. So, I will need monitor for menus.

**Comment by fossfreedom** [comment]
sure - this is the key commit https://github.com/UbuntuBudgie/budgie-desktop/commit/e7f944312f96b64b11324eda8f5192a0fa607d71

**Comment by rilian-la-te** [comment]
Try latest master, please:)

**Comment by fossfreedom** [comment]
Hi,
  tried again.  Unfortunately no.

I ran GTK_DEBUG=interactive budgie-panel --replace &

I navigated down to the app menu - but I didnt see any evidence that either the budgie-menubar or -vala-panel-appmenu-budgie classes were actually added to any object

**Comment by fossfreedom** [comment]
ok - I've taken the try/catch block out and its failing on line 39 - it cannot load that resource file.  Just commented those bits that use the CSS provider and budgie-desktop is now styling correctly for the system theme.

**Comment by rilian-la-te** [comment]
What about builtin theme?

**Comment by fossfreedom** [comment]
builtin theme works ok  with the CSS provider bits  commented out.  

Possibly the resource is failing to load because I'm compiling like this?

``
cmake .. -DENABLE_XFCE=OFF -DENABLE_MATE=OFF -DENABLE_VALAPANEL=OFF -DENABLE_BUDGIE=ON -DENABLE_UNITY_GTK_MODULE=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib
```

**Comment by rilian-la-te** [comment]
Will look for it (wait a minute, I am updating a entire series of core vala-panel)

**Comment by fossfreedom** [comment]
ok - sorry - with a bit more obvious testing.  If you first start the panel (budgie-panel --replace &) the active window with the inbuilt theme is correctly themed.

As soon as you switch to another application, or the active window looses focus (e.g. opening Raven), the drop-down menus become transparent.  I guess here that the new application menuitems are no longer styled with "budgie-menubar"

**Comment by fossfreedom** [comment]
ok - thanks for the latest commit.  I've pulled this and recompiled.

![ubuntu xenial dev running - oracle vm virtualbox 1_017](https://cloud.githubusercontent.com/assets/996240/25772600/ff1f0654-3266-11e7-94c3-21f2fabb8735.jpg)

As you can see the bamfappmenu has lost its custom styling - just "menubar" is applied.

**Comment by rilian-la-te** [comment]
I will install budgie-desktop and test more in evening. I am in work now.

**Comment by fossfreedom** [comment]
yay! we have a winner with the latest commit!!

After making the following changes I have tested clicking between applications, clicking to an empty workspace and launching a new app, switching the inbuilt theme on and off.  All is correctly themed.

Well done! :)

```
//var provider = new Gtk.CssProvider();
        //File ruri = File.new_for_uri("resource://org/vala-panel/appmenu/appmenu.css");
        //try
        //{
            //provider.load_from_file(ruri);
            layout.get_child().notify.connect((pspec)=>{
                foreach(unowned Gtk.Widget ch in (layout.get_child() as Container).get_children())
                {
                    unowned Gtk.StyleContext context = ch.get_style_context();
                    //context.add_provider(provider,Gtk.STYLE_PROVIDER_PRIORITY_THEME);
                    context.add_class("budgie-menubar");
                    context.add_class("-vala-panel-appmenu-budgie");
                }
            });
            foreach(unowned Gtk.Widget ch in (layout.get_child() as Container).get_children())
            {
                unowned Gtk.StyleContext context = ch.get_style_context();
                //context.add_provider(provider,Gtk.STYLE_PROVIDER_PRIORITY_THEME);
                context.add_class("budgie-menubar");
                context.add_class("-vala-panel-appmenu-budgie");
            }
        //} catch (GLib.Error e) {}
```

**Comment by fossfreedom** [comment]
ah - I know what that error is - let me do some CSS changes....

**Comment by rilian-la-te** [comment]
Then make a PR, ok?

**Comment by fossfreedom** [comment]
Yes. Will do. Thnx

**Comment by rilian-la-te** [comment]
This is fixed, AFAIK.

**Comment by rilian-la-te** [comment]
@fossfreedom, what commit are fixing budgie issue?

**Comment by fossfreedom** [comment]
This PR - https://github.com/budgie-desktop/budgie-desktop/pull/910

**Comment by rilian-la-te** [comment]
Fixed upstream
