### ISSUE TITLE
build failure for budgie

### ISSUE THREAD

**Issue by SolarAquarion** [rilian-la-te/vala-panel-appmenu#70]
home/solaraquarion/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/lib/dbusmenu.c:808:15: note: ‘str’ was declared here
const char * str;
^~~
[ 39%] Building C object lib/CMakeFiles/appmenu-mate.dir/libappmenu.gresource.c.o
[ 40%] Linking C executable appmenu-mate
[ 44%] Built target appmenu-mate
[ 45%] Generating budgie-plugin-appmenu.c
/home/solaraquarion/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/lib/budgie-plugin-appmenu.vala:41.9-41.16: error: The name provider' does not exist in the context ofGlobalMenuApplet.new'
provider = new Gtk.CssProvider();
^^^^^^^^
/home/solaraquarion/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/lib/budgie-plugin-appmenu.vala:45.13-45.20: error: The name provider' does not exist in the context ofGlobalMenuApplet.new'
provider.load_from_file(ruri);
^^^^^^^^
/home/solaraquarion/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/lib/budgie-plugin-appmenu.vala:50.42-50.49: error: The name provider' does not exist in the context ofGlobalMenuApplet.new.lambda4'
context.add_provider(provider,Gtk.STYLE_PROVIDER_PRIORITY_FALLBACK);
^^^^^^^^
Compilation failed: 3 error(s), 0 warning(s)
make[2]: *** [lib/CMakeFiles/appmenu-budgie.dir/build.make:118: lib/appmenu-budgie_valac.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:534: lib/CMakeFiles/appmenu-budgie.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by rilian-la-te** [comment]
fixed
