### ISSUE TITLE
Unity-Gtk-Module: breaks caja

### ISSUE THREAD

**Issue by rilian-la-te** [rilian-la-te/vala-panel-appmenu#75]
Desktop icons lose transparency:(

**Comment by GrindamN** [comment]
I had similar issue happening. Basically, the icons would copy parts of background if you dragged them whether they were desktop icons or folder icons when you run file manager.

**Comment by flexiondotorg** [comment]
I've also seen this issue with Caja and Plank.

**Comment by rilian-la-te** [comment]
I think, [here](https://github.com/GNOME/gtk/commit/1d35f273d6ae7f145e7cf8102d423fd7451f57f5#diff-9f3aaddde6be3ef080e371d690b4243e) lies the bug.

**Comment by flexiondotorg** [comment]
This is also fixed in upstream `unity-gtk-module` too. Should land in the Ubuntu 17.10 archive in a few hours.

**Comment by rilian-la-te** [comment]
where? I does not see a fix in http://bazaar.launchpad.net/~indicator-applet-developers/unity-gtk-module/trunk.15.04/changes/

**Comment by rilian-la-te** [comment]
Upd: seen it in https://code.launchpad.net/~ubuntu-mate-dev/unity-gtk-module/lp1710999/+merge/329080.
But it is improper fix, you need also https://github.com/rilian-la-te/vala-panel-appmenu/commit/1f5ec2bbc90f5c2dc9ff7f95ca384f2aa19608eb,
because without is we will have big issues on MATE loading.

**Comment by flexiondotorg** [comment]
@rilian-la-te Can you explain what you mean by "we will have big issues on MATE loading" please? I can apply this change upstream but I need to know what I can test to ensure it works and doesn't cause any regression :-)

**Comment by rilian-la-te** [comment]
1. I want to be mentioned upstream.
2. About issues. For me, before commit when I start MATE (transparent panel), panel and Caja crashes every second, Just up and crash. And a hundred times repeat. (So, like a minute or two I spend watching on flashing panel and desktop icons).
And then I wrote this commit, which limits hack to DnD windows.

**Comment by flexiondotorg** [comment]
The complete fix is upstream and you are mentioned.

**Comment by rilian-la-te** [comment]
Thank you.
