### ISSUE TITLE
budgie desktop - entire desktop freezes when clicking the menu button after login

### ISSUE THREAD

**Issue by fossfreedom** [rilian-la-te/vala-panel-appmenu#76]
Ubuntu Budgie 17.04

With the global menu applet added to the panel - then reboot and login.

Click the budgie menu button - the whole desktop freezes

To recover - login - CTRL+ALT+T to open a terminal and run 

    budgie-panel --reset --replace &

This resets the panel removing the applet.

Threading issue maybe?  Does the applet create threads but maybe not release the thread?

**Comment by neowiz73** [comment]
i'm showing similar issues, i've noticed that the vala appmenu is trying to pull dbus information from the main application menu as well as any other applet that has a popup (ie. sound applet, user session applet).  this information is presented multiple times unless something is done to cause a break.  

the only method i've discovered so far requires more than one application to be open, then by alt+tab between these applications will cause the above issue to break and allow said menu to complete the opening process.

there may need to be an option for blacklisting certain processes like the budgie main menu and other applets.

**Comment by rilian-la-te** [comment]
Will look for it. You can blacklist it in appmenu-gtk-module. I will add a
hard blacklist next
