### ISSUE TITLE
Budgie Desktop- clicking menu button after adding the panel see repeating applets

### ISSUE THREAD

**Issue by fossfreedom** [rilian-la-te/vala-panel-appmenu#77]
![untitled](https://cloud.githubusercontent.com/assets/996240/25843645/e72fa644-349f-11e7-9fb7-7a354d1980da.png)

So following #76 I reset the panel

Then I opened raven and readded the global appmenu applet and moved it to the left hand side of the panel.

Then I clicked the menu button.  This repeats the applet across the panel before the whole desktop hard-freezes

**Comment by rilian-la-te** [comment]
I was seeing it. Will look for it.

**Comment by rilian-la-te** [comment]
Fixed in commit for non-Ubuntu.

For ubuntu - add budgie-panel to unity-gtk-module blacklist in GSettings.

**Comment by fossfreedom** [comment]
Hi @rilian-la-te 

![ubuntu budgie - new development running - oracle vm virtualbox_018](https://cloud.githubusercontent.com/assets/996240/25866260/bf38c4b0-34ed-11e7-9c07-87f9ee47fb11.jpg)

I compiled and installed the latest sources and updated the key shown in the picture - same issue occurred though.  Have I done something wrong with the key values?

**Comment by fossfreedom** [comment]
ah - wrong key! found it :)

**Comment by rilian-la-te** [comment]
So, it works?

**Comment by fossfreedom** [comment]
yes - thanks.  

Need somehow though to debian package this just for ubuntu.  I'll raise the issue - not really sure - maybe Martin will know since obviously Ubuntu MATE will need the same key being set.

I'll have a think as well.
