### ISSUE TITLE
Issues with qt applications

### ISSUE THREAD

**Issue by flamingrush2** [rilian-la-te/vala-panel-appmenu#78]
Global Appmenu doesn't work with qt applications(tested with VLC Media Player and OBS Studio). Using appmenu panel for xfce on Manjaro XFCE 17.0.1.

PS: I have followed the Readme. The appmenu works with most of the apps including chromium but not with qt apps. I've already install "appmenu-qt4" from AUR using yaourt.

Currently I am using compiz if that matters. However I tested with xfwm4 but the issue persists.

**Comment by rilian-la-te** [comment]
I will try it this evening.

**Comment by rilian-la-te** [comment]
It is qt4-only issue?

**Comment by flamingrush2** [comment]
Not sure. But I installed transmission-qt to check and it too didn't have the global menu.

**Comment by rilian-la-te** [comment]
Chromium, smplayer?

**Comment by flamingrush2** [comment]
Chromium has global app menu but sm player does not.

**Comment by rilian-la-te** [comment]
Check `UBUNTU_MENUPROXY` from terminal and try to running apps from terminal.

**Comment by flamingrush2** [comment]
Can you elaborate please what to do? I have followed the Readme and edited .profile and .bashrc as stated there.

**Comment by rilian-la-te** [comment]
Because it works for me, so, basic diagnostic.
1. Run one qt4 (vlc) and one qt5 (smplayer) application from terminal and post result screen and both logs here
2. Run ```env``` from terminal and post output here
3. Check any other registrar application (HUD) for running

**Comment by flamingrush2** [comment]
1. Screenshots of VLC and SMPlayer
![screenshot_2017-05-12_15-03-13](https://cloud.githubusercontent.com/assets/10271197/25992787/4d24c09c-3725-11e7-916b-db40c07c59b8.png)
![screenshot_2017-05-12_15-04-41](https://cloud.githubusercontent.com/assets/10271197/25992788/4d260358-3725-11e7-893f-e80069e22db5.png)



2. env output
`LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.pdf=00;32:*.ps=00;32:*.txt=00;32:*.patch=00;32:*.diff=00;32:*.log=00;32:*.tex=00;32:*.doc=00;32:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
LC_MEASUREMENT=en_IN
LC_PAPER=en_IN
LC_MONETARY=en_IN
XDG_MENU_PREFIX=xfce-
LANG=en_IN.utf8
YAOURT_COLORS=nb=1:pkg=1:ver=1;32:lver=1;45:installed=1;42:grp=1;34:od=1;41;5:votes=1;44:dsc=0:other=1;35
DISPLAY=:0.0
COLORTERM=truecolor
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
XDG_VTNR=7
GIO_LAUNCHED_DESKTOP_FILE_PID=2143
SSH_AUTH_SOCK=/tmp/ssh-sseCHhFO22J2/agent.641
GLADE_CATALOG_PATH=:
LC_NAME=en_IN
XDG_SESSION_ID=c2
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/amol
USER=amol
GLADE_MODULE_PATH=:
DESKTOP_SESSION=xfce
QT_QPA_PLATFORMTHEME=qt5ct
PWD=/home/amol
HOME=/home/amol
SSH_AGENT_PID=642
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/local/share:/usr/share
GSETTINGS_SCHEMA_DIR=/home/amol/data
XDG_SESSION_DESKTOP=xfce
LC_ADDRESS=en_IN
LC_NUMERIC=en_IN
GLADE_PIXMAP_PATH=:
GTK_MODULES=unity-gtk-module:canberra-gtk-module:unity-gtk-module:unity-gtk-module
MAIL=/var/spool/mail/amol
UBUNTU_MENUPROXY=1
TERM=xterm-256color
SHELL=/bin/bash
VTE_VERSION=4601
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_CURRENT_DESKTOP=XFCE
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/xfce4-terminal.desktop
XDG_SEAT=seat0
SHLVL=2
WINDOWID=73400323
LC_TELEPHONE=en_IN
GDMSESSION=xfce
LOGNAME=amol
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/home/amol/.Xauthority
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_CONFIG_DIRS=/etc/xdg
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
LC_IDENTIFICATION=en_IN
SESSION_MANAGER=local/workstation-MANJARO:@/tmp/.ICE-unix/634,unix/workstation-MANJARO:/tmp/.ICE-unix/634
LC_TIME=en_IN
_=/usr/bin/env`

3. I think none.

Have you tested on Manjaro/Arch? Few days back I had seen a comment in reddit post where the appmenu was also not working for him. He too was using Manjaro. But another person who was using Xubuntu, seems to be unaffected by the problem.

**Comment by rilian-la-te** [comment]
I am using Arch on all my computers, so, it is primary development platform.
Run ```env | grep UBUNTU_MENUPROXY```

**Comment by rilian-la-te** [comment]
And try to run it without qt5ct.
qt5ct can override default menu configuration.
(I do not use it, so, I do not know)

**Comment by flamingrush2** [comment]
env | grep UBUNTU_MENUPROXY:
`UBUNTU_MENUPROXY=1`

How do I run it without qt5ct? Tried uninstalling but it says it will break manjaro-xfce-settings.
`[ ~]$pactree -r qt5ct`
`qt5ct`
`└─manjaro-xfce-settings`

**Comment by rilian-la-te** [comment]
for example:
``` $ export QT_QPA_PLATFORMTHEME= 
     $ smplayer```

**Comment by flamingrush2** [comment]
I confirm it works now. But then the theme is gone now. To get the theme back I used:
`$ export QT_QPA_PLATFORMTHEME=gtk2`

But I'm pretty sure disabling qt5ct themes would surely break one app or the other. Thanks for your help. :)

PS: You may want to add it in your readme perhaps.

**Comment by flamingrush2** [comment]
But everytime I close the terminal, the theme resets back to qt5ct. Anyway to do the change permanently?

**Comment by rilian-la-te** [comment]
Please, create issue in qt5ct bugtracker. About permanent change - look to manjaro-xfce-settings and try to disable qt5ct, Or remove this package by pacman -Rsc.

**Comment by flamingrush2** [comment]
For permanent effect I added `export QT_QPA_PLATFORMTHEME=gtk2` to `~/.profile` and it seems to work fine now.

**Comment by rilian-la-te** [comment]
Issue in qt5ct [here](https://sourceforge.net/p/qt5ct/tickets/34/)

**Comment by rilian-la-te** [comment]
qt5ct creator asks for trying latest svn. Can you do it?
