### ISSUE TITLE
Not Working with LibreOffice 5.3

### ISSUE THREAD

**Issue by estelondono** [rilian-la-te/vala-panel-appmenu#79]
Hi there!
First, thank you so much for your app. I'm using Linux Lite (Ubuntu 16.04) but it's not working with LibreOffice 5.3 but with LibreOffice 5.2 was working normally.

**Comment by rilian-la-te** [comment]
Show me a screen. Did you install all required dependences like
unity-gtk-module?

**Comment by rilian-la-te** [comment]
And did you followed my Readme? 

For me, it works with 5.3 on Archlinux.

**Comment by estelondono** [comment]
![vala-libreoffice5-3](https://cloud.githubusercontent.com/assets/25468837/26019680/ec272c2c-373c-11e7-9ba4-bbd3543b22ec.png)
That's the screen I get when I run LibreOffice 5.3.
I installed it via ppa:webupd8team/mate and follow the instructions from [this web page from Web Upd8](http://www.webupd8.org/2017/02/alternative-global-menu-for-mate-and.html). Also follow the instructions in the README.md
I already had LibreOffice 5.2 that worked fine. I uninstalled and installed the 5.3 version. Then the Vala App Menu stop working.

**Comment by rilian-la-te** [comment]
![screenshot at 2017-05-13 09-58-06](https://cloud.githubusercontent.com/assets/1329638/26023382/e2c35b98-37c2-11e7-832c-aafac842fb36.png)

Works for me, libreoffice 5.3.2. Do you update MATE?
Another gtk2/gtk3 applications work?

**Comment by estelondono** [comment]
I'm using Xfce, not MATE. But all the others apps are working fine with it.

-------- Mensaje original --------
De: Konstantin <notifications@github.com> 
Fecha: 2017/05/13  01:59 AM  (GMT-05:00) 
A: rilian-la-te/vala-panel-appmenu <vala-panel-appmenu@noreply.github.com> 
CC: Esteban Londoño <estelondono@gmail.com>, Author <author@noreply.github.com> 
Asunto: Re: [rilian-la-te/vala-panel-appmenu] Nto Working with LibreOffice
  5.3 (#79) 

Works for me, libreoffice 5.3.2. Do you update MATE? Another gtk2/gtk3 applications work? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by rilian-la-te** [comment]
xprop for lowriter. I need to see it.

**Comment by rilian-la-te** [comment]
what libreoffice backend are you using?

**Comment by estelondono** [comment]
First, thank you for your help. Sorry the delay with my answers.

When I I type **xprop** and select LibreOffice 5.3 this is what the Terminal says (_I hope I'm doing it right_):

`_NET_WM_ICON_GEOMETRY(CARDINAL) = 4294957605, 4294957297, 60, 60
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 28, 3
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_STICK
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x3f185700
_NET_WM_DESKTOP(CARDINAL) = 1
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x3a00089
		bitmap id # of mask for icon: 0x3a0008a
		window id # of group leader: 0x3a00001
XdndAware(ATOM) = BITMAP
GDK_TIMESTAMP_PROP(GDK_TIMESTAMP_PROP) = 0x61
_NET_WM_ICON(CARDINAL) = 	Icon (32 x 32):
	                                
	                                
	    ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░    
	    ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒    
	    ▒▒            ▒▒▒     ▒▒    
	    ▒▒             ▒▒▒    ▒▒    
	    ▒▒              ▒▒▒   ▒▒    
	    ▒▒               ▒▒▒  ▒▒    
	    ▒▒                ▒▒▒ ▒▒    
	    ▒▒                 ▒▒▒▒▒    
	    ▒▒                  ▒▒▒▒    
	    ▒▒                   ▒▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒                    ▒▒    
	    ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒    
	    ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░    
	                                
	                                

	Icon (48 x 48):
	                                                
	                                                
	                                                
	                                                
	       ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒       
	      ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒      
	      ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒      
	      ▒▒▒                  ▒▒▒▒░       ▒▒▒      
	      ▒▒▒                   ▒▒▒▒░      ▒▒▒      
	      ▒▒▒                    ▒▒▒▒      ▒▒▒      
	      ▒▒▒                     ▒▒▒▒     ▒▒▒      
	      ▒▒▒                      ▒▒▒▒    ▒▒▒      
	      ▒▒▒                       ▒▒▒▒   ▒▒▒      
	      ▒▒▒                        ▒▒▒▒  ▒▒▒      
	      ▒▒▒                         ▒▒▒▒ ▒▒▒      
	      ▒▒▒                          ▒▒▒▒▒▒▒      
	      ▒▒▒                           ▒▒▒▒▒▒      
	      ▒▒▒                           ░▒▒▒▒▒      
	      ▒▒▒                            ░▒▒▒▒      
	      ▒▒▒                             ░▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒                              ▒▒▒      
	      ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒      
	      ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒      
	      ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░      
	                                                
	                                                
	                                                
	                                                

	Icon (128 x 128):
	                                                                                                                                
	                                                                                                                                
	                                                                                                                                
	                                                                                                                                
	                                                                                                                                
	                                                                                                                                
	                                                                                                                                
	                                                                                                                                
	                   ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░                       
	                  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                      
	                 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                     
	                ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░                    
	                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                ▒▒▒▒▒▒▒▒▒                   ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                 ▒▒▒▒▒▒▒▒▒                  ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                  ▒▒▒▒▒▒▒▒▒                 ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                   ▒▒▒▒▒▒▒▒▒                ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                    ▒▒▒▒▒▒▒▒▒               ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                     ▒▒▒▒▒▒▒▒▒              ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                      ▒▒▒▒▒▒▒▒▒             ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                       ▒▒▒▒▒▒▒▒▒            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                        ▒▒▒▒▒▒▒▒▒           ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                         ▒▒▒▒▒▒▒▒▒          ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                          ▒▒▒▒▒▒▒▒▒         ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                           ▒▒▒▒▒▒▒▒▒        ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                            ▒▒▒▒▒▒▒▒▒       ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                             ▒▒▒▒▒▒▒▒▒      ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                              ▒▒▒▒▒▒▒▒▒     ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                               ▒▒▒▒▒▒▒▒▒    ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                ▒▒▒▒▒▒▒▒▒   ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                 ▒▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                  ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                    ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                     ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                      ▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                       ▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                        ▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                         ▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                          ▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                           ▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒                                                                            ▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                    
	                ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░                    
	                 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                     
	                 ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░                     
	                   ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░                       
	                     ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░                         
	                                                                                                                                
	                                                                                                                                
	                                                                                                                                
	                                                                                                                                
	                                                                                                                                
	                                                                                                                                
	                                                                                                                                


_GTK_MENUBAR_OBJECT_PATH(UTF8_STRING) = "/com/canonical/unity/gtk/window/3"
_UNITY_OBJECT_PATH(UTF8_STRING) = "/com/canonical/unity/gtk/window/3"
_GTK_UNIQUE_BUS_NAME(UTF8_STRING) = ":1.120"
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 60817544
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x3a00087
WM_CLIENT_LEADER(WINDOW): window id # 0x3a00001
_NET_WM_PID(CARDINAL) = 7049
WM_LOCALE_NAME(STRING) = "es_VE.UTF-8"
WM_CLIENT_MACHINE(STRING) = "casa"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 218 by 598
		window gravity: Static
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "libreoffice", "libreoffice-startcenter"
WM_ICON_NAME(STRING) = "LibreOffice"
_NET_WM_ICON_NAME(UTF8_STRING) = "LibreOffice"
WM_NAME(STRING) = "LibreOffice"
_NET_WM_NAME(UTF8_STRING) = "LibreOffice"
`
About the "libreoffice backend": How can I see that?

Again, thank you so much for your help.

**Comment by rilian-la-te** [comment]
using apt-cache.
If `libreoffice-gtk2` is installed - gtk2 backend is used. If ends by gtk3 - gtk3 backend, kde - qt backend.

**Comment by estelondono** [comment]
Well, I run
`$ apt-cache pkgnames libreoffice5.3
libreoffice5.3-en-us
libreoffice5.3-base
libreoffice5.3-debian-menus
libreoffice5.3-writer
libreoffice5.3-ure
libreoffice5.3-impress
libreoffice5.3-calc
libreoffice5.3-dict-en
libreoffice5.3-dict-es
libreoffice5.3-dict-fr
libreoffice5.3-draw
libreoffice5.3-math
libreoffice5.3
`
I downloaded it from the web of LibreOffice directly. Unziping the tar.gz file and installed with
`dpkg -i *.deb`
 in the DEBS folder.

**Comment by rilian-la-te** [comment]
Why not using debian repository or ppa?

**Comment by rilian-la-te** [comment]
Why not using debian repository or ppa?

On May 15, 2017 7:52 PM, "Esteban Londoño" <notifications@github.com> wrote:

Well, I run
$ apt-cache pkgnames libreoffice5.3 libreoffice5.3-en-us
libreoffice5.3-base libreoffice5.3-debian-menus libreoffice5.3-writer
libreoffice5.3-ure libreoffice5.3-impress libreoffice5.3-calc
libreoffice5.3-dict-en libreoffice5.3-dict-es libreoffice5.3-dict-fr
libreoffice5.3-draw libreoffice5.3-math libreoffice5.3
I downloaded it from the web of LibreOffice directly. Unziping the tar.gz
file and installed with
dpkg -i *.deb
in the DEBS folder.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/rilian-la-te/vala-panel-appmenu/issues/79#issuecomment-301535013>,
or mute the thread

**Comment by rilian-la-te** [comment]
try libreoffice ppa, please ```sudo add-apt-repository ppa:libreoffice/ppa```

**Comment by estelondono** [comment]
Now it's working!

I add the repository from LibreOffice and updated the software. Now 
everything is working fine.
Thank you very much for your help!
