### ISSUE TITLE
appmenu crashes on current Archlinux

### ISSUE THREAD

**Issue by jcornuz** [rilian-la-te/vala-panel-appmenu#8]
Hello,

I don't know if you are targetting Ubuntu only, but with a current version of Archlinux (standard 3.16 GTK, not the 3.14 Ubuntu patched version) the appmenu is crashing the panel with:

** (vala-panel:25868): CRITICAL **: appmenu_inner_registrar_get_menu_for_window: assertion 'self != NULL' failed
Segmentation fault (core dumped)

the appmenu xfce panel also fails to start.

Again, I can understand why you wouldn't want to start support concurrent gtk version, so feel free to ignore this report. Vala-panel is a really promising project - thanks for your work on it.

Take care

**Comment by rilian-la-te** [comment]
What appmenu-related and vala-panel packages you have installed? do you
have KDE or another appmenu applet?

**Comment by rilian-la-te** [comment]
Added a workaround. Please update package from AUR and try:)

**Comment by rilian-la-te** [comment]
I close it as fixed now (workaround in https://github.com/rilian-la-te/vala-panel-appmenu/commit/46bf25098ee38b15816a3f44d05441071da15c16). There is any issues like this - reopen it.

**Comment by jcornuz** [comment]
Hello 

That was quick (to say the least).

I had topmenu (the plugin that comes from Mate and simply draws the menu away from its windows and into the panel) but I removed it now.

The appmenu loads and works for a bit. But as soon as I change window focus or load the preferences my terminal is floaded with:

(vala-panel:4073): GLib-GIO-CRITICAL **: g_dbus_connection_signal_subscribe: assertion 'sender == NULL || (g_dbus_is_name (sender) && (connection->flags & G_DBUS_CONNECTION_FLAGS_MESSAGE_BUS_CONNECTION))' failed

(vala-panel:4073): GLib-GIO-CRITICAL **: g_dbus_connection_call_sync_internal: assertion 'bus_name == NULL || g_dbus_is_name (bus_name)' failed

If I remove the appmenu plugin, everything goes back to normal. This is with 0.2.11.r0.g87ffee0-1 (vala-panel) and 0.2.6.1.r0.g3b16204-1 (appmenu).

I hope this helps?!??

Thank for YOUR help :)

**Comment by rilian-la-te** [comment]
I know about it, will fix tomorrow, or today. Now I am busy with vala-panel's systray.

**Comment by jcornuz** [comment]
OK, thanks :)

**Comment by rilian-la-te** [comment]
I think, console flood is fixed.
