### ISSUE TITLE
Appmenu doesn't auto start after login

### ISSUE THREAD

**Issue by flamingrush2** [rilian-la-te/vala-panel-appmenu#80]
If I explicitly logout and then login then the appmenu does not automatically autostart. However if I use the console command "kill -9 -1" and then relogin, the appmenu appears on the panel.

**Comment by rilian-la-te** [comment]
Add bamfdaemon to autostart.  Post result here.

**Comment by rilian-la-te** [comment]
For now I am closing this (because I think this is bamf issue). Feel free to reopen. I will be on plane this evening, sorry.

**Comment by flamingrush2** [comment]
If I terminate bamfdaemon before logging out and then in, everything works fine. So what exactly does bamfdaemon do? And can you share the steps to disable that if and only if it would not conflict with any other application upon disabling.

**Comment by rilian-la-te** [comment]
It should be enabled for Appmenu to work.
You need to start it before appmenu runs.

What it do - it is like libwnck, but by DBus.

**Comment by flamingrush2** [comment]
What I think happens is that after logout-login the bamfdaemon service does not start. Maybe that is causing the problem. Any solution for that?

**Comment by rilian-la-te** [comment]
Add it to autostart explicitly :-)

**Comment by flamingrush2** [comment]
I added /usr/lib/bamf/bamfdaemon to autostart and it is working fine now. Thanks!
