### ISSUE TITLE
Make application name bold

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#81]
Please make the application name in the global menu **bold**. This will make `vala-panel-appmenu` consistent with how TopMenu and the macOS menubar functions and it also makes it easy to identify which application has focus by glancing at the global menu.

**Comment by rilian-la-te** [comment]
I think, this should be a theme option (I does not like bold appname
myself) . If you agree, tomorrow I will try to add a class for bold appmenu
name.

**Comment by rilian-la-te** [comment]
I can use 2 ways to implement it:
1. As a class and reference theme file. 
2. As a GSetting (but I does not like it, because it introduces xfconf dependency in Xfce and deprecations in case of MATE).

**Comment by rilian-la-te** [comment]
But bold application name should be force no-default.

**Comment by flexiondotorg** [comment]
If you implement this using a style class then theme authors have to know that this is something their themes should support. If you were to make this a gsetting, the schema doesn't have to in MATE, it could be in a path specific to vala-panel-appmenu itself, such as `org.vala-panel-appmenu`.

For example, Brisk Menu keeps it configuration specific to itself, not with in the upstream MATE gschema.

**Comment by rilian-la-te** [comment]
No, if it will be GSetting, it will be in org.valapanel.appmenu.
And it will be hidden and non-default.

If it will be a style class, it also will be no-default, and I will explicitly ask theme authors to prv ide it as option only. 

What variant are you likes more?

**Comment by flexiondotorg** [comment]
I prefer a GSetting in `org.valapanel.appmenu` :-)

**Comment by MggMuggins** [comment]
A style class seems like it would be more flexible and less of a pain looking farther into the future.

**Comment by zezic** [comment]
@flexiondotorg 
```bash
shk@990FX:~$ cat .config/gtk-3.0/gtk.css
.-vala-panel-appmenu-private > * > GtkLabel,
.-vala-panel-appmenu-private > * > *  > GtkLabel {
  font-weight: normal;
}
.-vala-panel-appmenu-private:nth-child(1) > * > GtkLabel {
  font-weight: 900;
}
```

**Comment by rilian-la-te** [comment]
If it works, I will add it as non-default into package.

**Comment by zezic** [comment]
Yes, it works nice.

**Comment by rilian-la-te** [comment]
I will include it as build option then.

**Comment by imccausl** [comment]
I'm not sure what the explanation for this is, but I run Xubuntu and I had to change GtkLabel to label in order to get the styling to work.

**Comment by lufinkey** [comment]
is there a way to do this if it's installed from a package manager rather than built manually?

**Comment by zelgit** [comment]
Yeeeees! This works! Thanks so much! Btw, I also have Xubuntu but it still works with GtkLabel. I'm noob, but maybe it's because I installed Gt3 dev version?

**Comment by flexiondotorg** [comment]
@rilian-la-te I think this can be closed.

**Comment by rilian-la-te** [comment]
No, because we do not have proper solution for this, when this can be turned off. It is a bad feature anyway and should not be default

**Comment by hvdijk** [comment]
This doesn't work for me. Although the CSS file gets loaded and used, the menu item doesn't get bolded. Loading the exact same CSS from `.config/gtk-3.0/gtk.css` does work.

Styles applied directly to `.-vala-panel-appmenu-bold` work from within `appmenu.css`, but styles applied to children do not. I believe this is the caveat pointed out in [`gtk_style_context_add_provider`](https://developer.gnome.org/gtk3/stable/GtkStyleContext.html#gtk-style-context-add-provider):

> Note that a style provider added by this function only affects the style of the widget to which `context` belongs. If you want to affect the style of all widgets, use `gtk_style_context_add_provider_for_screen()`.

And indeed, when changing the code to `Gtk.StyleContext.add_provider_for_screen(ch.get_screen(),provider,Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION);` as a quick and dirty test, it does work. I don't think that's the proper fix though.

**Comment by rilian-la-te** [comment]
Build option work?

**Comment by rilian-la-te** [comment]
Provider for screen is bad option always, so, we need another fix.

**Comment by hvdijk** [comment]
What also works and is less of a hack is recursively visiting all children to end up calling `add_provider` for all descendants: https://github.com/hvdijk/vala-panel-appmenu/commit/d3f71fb6a98f7be77161a8a953f6f6ac54d382be But this still feels like it's more complicated than it needs to be.

**Comment by rilian-la-te** [comment]
Will look for it.

**Comment by rilian-la-te** [comment]
What version of GTK are you using?

**Comment by hvdijk** [comment]
Using GTK 3.22.24.

**Comment by nkkollaw** [comment]
Not working here.

I did build with the app name flag set to ON, but it still shows "normal".

**Comment by rilian-la-te** [comment]
@hvdijk  hack is working?

**Comment by hvdijk** [comment]
Yes, still working for me. GTK 3.22.26 now, MATE 1.19, vala-panel-appmenu 0.5.3 with d3f71fb6a98f7be77161a8a953f6f6ac54d382be applied. Screenshot: https://imgur.com/TdpL3KX

**Comment by rilian-la-te** [comment]
@hvdijk can you make a proper patch for this (when only menubar touched)? I will integrate it upstream:-)

**Comment by hvdijk** [comment]
The `MenuWidget` contains a `BamfAppmenu` and a `Gtk.MenuBar`. If I modify the code to only touch the `Gtk.MenuBar`, wouldn't then the `BamfAppmenu` become unstyled again, so not bold? I'm probably misunderstanding what you mean, can you explain in a bit more detail?

**Comment by rilian-la-te** [comment]
You need to modify exactly one element - appname. It can be in a BamfAppmenu or DesktopAppmenu or MenuWidgetMenumodel. You need to figure its element and make it .-vala-panel-appmenu-bold classed. Only it, not all menu.

**Comment by hvdijk** [comment]
Ah, okay, and modify the CSS to just `.-vala-panel-appmenu-bold { font-weight: 900; }`, I guess.

That wouldn't work either though, I believe. When you actually open the menu, the menu items in there are children of the main menu item, so they inherit the font weight, and every item inside the app menu would become bold. That's why the current CSS has the `.-vala-panel-appmenu-bold > * > *  > label { font-weight: normal; }` to revert it back to the default, isn't it? So it would still be necessary to have a loop in there somewhere to apply the CSS to the menu's children as well.

**Comment by rilian-la-te** [comment]
This is for apply a CSS to one specific element only, and you need to guess it. And rewrite a CSS.

**Comment by alekseyt** [comment]
I'm also affected by this bug on Void Linux and Xfce 4.12. I'm building with the following flags:
```
-DENABLE_APPMENU_GTK_MODULE=ON
-DENABLE_XFCE=ON
-DMAKE_BOLD_APPNAME=ON
-DCMAKE_INSTALL_PREFIX=/usr
-DCMAKE_INSTALL_LIBDIR=/usr/lib
```

Configure log:
```
-- The C compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for RPMTools... - rpmbuild NOT FOUND
-- Found Vala: /usr/bin/valac  
-- checking for a minimum Vala version of 0.24
--   found Vala, version 0.38.4
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'gtk+-3.0>=3.10'
--   Found gtk+-3.0, version 3.22.26
-- Checking for modules 'glib-2.0>=2.44;gio-2.0>=2.44;gio-unix-2.0>=2.44;gthread-2.0>=2.44;gmodule-2.0>=2.44'
--   Found glib-2.0, version 2.54.2
--   Found gio-2.0, version 2.54.2
--   Found gio-unix-2.0, version 2.54.2
--   Found gthread-2.0, version 2.54.2
--   Found gmodule-2.0, version 2.54.2
-- Checking for module 'libbamf3'
--   Found libbamf3, version 0.5.3
-- Checking for module 'libwnck-3.0>=3.4.0'
--   Found libwnck-3.0, version 3.24.1
Using libwnck, will be X-dependent
-- Checking for modules 'libxfce4panel-2.0;libxfconf-0'
--   Found libxfce4panel-2.0, version 4.12.1
--   Found libxfconf-0, version 4.12.1
-- Checking for module 'libmatepanelapplet-4.0'
--   No package 'libmatepanelapplet-4.0' found
-- Checking for module 'libpeas-1.0'
--   No package 'libpeas-1.0' found
-- Checking for module 'vala-panel'
--   No package 'vala-panel' found
-- Checking for modules 'budgie-1.0;libpeas-1.0'
--   No package 'budgie-1.0' found
--   No package 'libpeas-1.0' found
-- Checking for module 'gtk+-2.0>=2.24'
--   Found gtk+-2.0, version 2.24.31
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/libX11.so
-- GSettings schemas will be installed locally.
-- GSettings schemas will be compiled.
-- GSettings schemas will be installed into /usr/share/glib-2.0/schemas/
-- Checking for module 'systemd'
--   No package 'systemd' found
-- Could NOT find Java (missing: Java_JAVA_EXECUTABLE Java_JAR_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAVAH_EXECUTABLE Java_JAVADOC_EXECUTABLE) 
-- Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
-- Checking for module 'xkbcommon'
--   Found xkbcommon, version 0.7.2
-- Checking for module 'dbusmenu-glib-0.4'
--   Found dbusmenu-glib-0.4, version 16.04.0
-- checking for a minimum Vala version of 0.24
--   found Vala, version 0.38.4
-- Configuring done
-- Generating done
-- Build files have been written to: /builddir/vala-panel-appmenu-0.5.6/build
```

Source code used was from 0.5.6 release: https://github.com/rilian-la-te/vala-panel-appmenu/releases/tag/0.5.6 . It all installs and works, except application name is not bold. Gtk3 version is 3.22.26.

**Comment by nick87720z** [comment]
Just noticed this thread, seems to be not solved.
While working on menubar scroll feature, i parallely tried to solve this problem too.

I tried following experiment: completely commented style loading code and scrolling code, returning gui structure to original, with both appmenu and menubar added to GtkBox parent directly. Content from appmenu.css found its place in my ~/.config/gtk-3.0/gtk.css.

Result is ideal: only first menu (appmenu) is bolded, and only its name - submenu is not affected.
Menubars in other apps are not affected (tried with denemo, whose menu is not exported via dbus).

Now i tried to move styling code (from loading cssprovider to applying style classes)

**Comment by nick87720z** [comment]
@hvdijk Try to add content from internal appmenu.css directly to ~/.config/gtk-3.0/gtk.css .
This worked for me as clock)
(until it is done by code)

**Comment by nick87720z** [comment]
I found following issue with how gtk uses internal appmenu.css.
1. appmenu.css is applied even if it was not loaded by cssprovider and applied to style context.
2. There is no difference between -vala-panel-appmenu-private and -vala-panel-appmenu-bold because they are assigned to both menubars. Replacing private to bold and backward in both gtk.css and appmenu.css changes nothing.
3. In appmenu.css hierarchy selectors of any kind don't work. This is why first block in appmenu.css is used (otherwise menubars would be opaque flat), while second two blocks, pointing to labels inside menubars, don't. It is still possible to use :nth_child(n), so it is possible to make bold only first menuitem, but only together with its submenu. Thus, these constructions work:
```
menubar {...}
menubar:first_child {...}
* * {...}
/* This really seems to be equivalent to just */
* {...}
```
While these don't:
```
menubar * {...}
menubar > * > label {...}
menubar > menuitem > label {...}
```
(in gtk.css or from gtk inspector, all hierarchy selectors are working)

**Comment by junked** [comment]
Does any way to make all text bold, fix underline and alignment on picrelated (~95% all themes) ?
http://i.piccy.info/i9/bf74659d2b3167da0e805e70b2044b11/1514988948/4185/1209664/1.png

**Comment by nick87720z** [comment]
Hm, on your screenshot menubar has strange displacement towards bottom. I got same when tried fresh official elementary-os gtk3 theme. With adwaita-based (i have minwaita) it is ok.
And it seems, menubar is too thick for panel... you could increase panel thickness for immediate workaround. Probably, it needs as low as possible surrounding space.

**Comment by rilian-la-te** [comment]
Is line between menus from selection or from update?

**Comment by nick87720z** [comment]
I just got same bad vertical placement, trying panel height =22. Left menubar is not scrollable, so is forced to be narrower. But right part is, and scroller honors it, making ugly look.
For quick fix - try add this to ~/.config/gtk-3.0/gtk.css to make vertical placement ok:
```
.-vala-panel-appmenu-private > menuitem {
    margin: 0 0 0 0;
    padding-top: 0;
    padding-bottom: 0;
}
```

**Comment by rilian-la-te** [comment]
Will look for it.

**Comment by junked** [comment]
Oh, thank you, alignment works perfect with small panel size. And underline is gone. But can you tell me how I can change all text to bold ?

**Comment by rilian-la-te** [comment]
@junked what panel are you using?

**Comment by nick87720z** [comment]
@junked for only panel text change:
```
.-vala-panel-appmenu-bold > * > label {
  font-weight: bolder;
}

```
for all menus - begin with just `.-vala-panel-appmenu-bold {`

**Comment by rilian-la-te** [comment]
If @junked is using vala-panel, it should do it by config, not by CSS.

**Comment by nick87720z** [comment]
I did not know, it has settings)
In applets list its settings button is inactive. But i thought some related files in sources, so guessed it is in development.

**Comment by rilian-la-te** [comment]
No, it is vala-panel 's settings, not appmenu.

**Comment by nick87720z** [comment]
However, it changes font for all panel content, including submenus. While above css block does it only for menubar text.

**Comment by junked** [comment]
@rilian-la-te, xfce4-panel

**Comment by rilian-la-te** [comment]
@junked , use CSS then.

**Comment by rilian-la-te** [comment]
New approach arrives. Bold names does not working now, sorry.

**Comment by nick87720z** [comment]
It may be done for menu item as well.

**Comment by rilian-la-te** [comment]
But can it be done for first menu item without knowlege about it? Can you try to fix CSS with importer version?

**Comment by nick87720z** [comment]
This chunk makes it for my version of menu, where app menubar is included to scroller (.frame class).
However, it seems, that most left item is last-child, while first-child is at the end:
```
.frame .-vala-panel-appmenu-private > menuitem:last-child > label {
	font-weight: bold;
}
```
Btw, about scroller - if splitting of menu model between multiple menu shells is not possible, appart of complete removing of scroll feature it could just reset scroller position when menubar is exited.
Or may be even begin own menushell implementation, based on toolbar. to finally get overflow handling :).
Also, as variant... instead of both scroller or overflow container, menubar may be enclosed to container, which will do soft expand (like currently scroller does).

**Comment by rilian-la-te** [comment]
There is a hidden switch for compact mode now. Settings will be next.

**Comment by Gambulec** [comment]
My desktop menu looks like this
https://imgur.com/AUmuXpw
but the applications menu is good

**Comment by rilian-la-te** [comment]
Line is from what?

**Comment by Gambulec** [comment]
I do not know. In the version from two months ago it was not.

**Comment by rilian-la-te** [comment]
Will look for it.

**Comment by rilian-la-te** [comment]
Bold desktop are fixed. For separator - I should look for it to override a theme.
