### ISSUE TITLE
Some menus have too much padding

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#82]
I've noticed that some applications, for example Google Chrome, have lots of padding in the menus which makes them look out of place.

![menu-padding](https://cloud.githubusercontent.com/assets/304639/26027118/c7263814-37ff-11e7-8706-532844c4930c.png)

**Comment by rilian-la-te** [comment]
I know about it. I explicitly did this in vala-dbusmenu, because it should have an abilitiy show items with both icon and checkbox (and this padding are exactly for it). 
I think, tracking max padding by menu content is overkill (but I can try to implement it). 
But vala-dbusmenu should have an abilitiy to show both icon and checkbox (AFAIK, Virtualbox requires it)

**Comment by flexiondotorg** [comment]
How about simply dropping the padding from each menus that has no icons or checkboxes present? For example:

  * VLC has icons in most menus but the Subtitles menu has no icons at all.
  * Chome only has an icon in the People menu with no icons or checkboxes in any other menu.

Would it be possible to determine if individual menus have icons/checkboxes and change the padding on just those menus accordingly?

**Comment by rilian-la-te** [comment]
This need some complicated logic in menus itself. I will think about it.
And, please write requests about dbusmenu into vala-dbusmenu bugtracker.

**Comment by rilian-la-te** [comment]
And for examples, GtkMenuItem always reserving place for checkbox. I can
also reserve place for checkbox only, and this will consistent with Gtk.
And Ingore icons, if both present.

**Comment by rilian-la-te** [comment]
Workaround in [vala-dbusmenu/ad2d94bd9f37aa07292a0a0471b4ed3fecd52fcd](https://github.com/rilian-la-te/vala-dbusmenu/commit/ad2d94bd9f37aa07292a0a0471b4ed3fecd52fcd)
