### ISSUE TITLE
Can't rollover from the application menu and the menus.

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#83]
It is not possible to rollover from the menus to the application menu (the one with the application name).

For example, using Pluma in MATE if you click File in the Global Menu you can rollover to Edit and View etc, but you are not able to rollover to the application menu labelled Pluma. 

Again using Pluma, click the Pluma menu entry and you are not able to rollover to File, Edit, View, etc.

**Comment by rilian-la-te** [comment]
Yes, I know about it. It is because it is 2 menus actually, not one. I can look into GtkMenuShell documentation and source to determine abilitiy to merge 2 different menubars (model-based and custom). If it is possible, I will implement rollover.

**Comment by rilian-la-te** [comment]
I cannot find a way to merge menumodel and dbusmenu:-( But I can try to make 2 implementations of stub menu (mergeable).

**Comment by rilian-la-te** [comment]
try new release, please. If it works, close this.

**Comment by nick87720z** [comment]
In pull request #172 (waiting for approval). This change, however, doesn't handle mouse (yet).
It would be indeed better to merge two menu models (g_menu_append_section() is just fo this case), but even when done, scrolling, will can only affect entire menu - i.e., appmenu will be hidden.

However, one of xfce-devs told me about menubar overflow handling, which adds overflow submenu at the end, and i even noticed something related in docs, but now found it hard to find both in devhelp and internet :/ .

Btw, there is some strange thing appears in menu after it's filled by dbusmenu - using show_all() on it adds huge space between menubar items, as big as items theirself. Would much more convenient to work with it if it returns gmenumodel.

**Comment by rilian-la-te** [comment]
We cannot merge menumodels, because with Qt apps we do not have menubar menumodel.

**Comment by rilian-la-te** [comment]
About dbusmenu show_all - we have an icons here, icons can be huge, and then all menu items will ocuppy huge space each.

**Comment by nick87720z** [comment]
ok

**Comment by rilian-la-te** [comment]
About overflow handling - I need more information)

**Comment by nick87720z** [comment]
I'm in a maze with that. I found its mention, but it is about toolbar :S

**Comment by rilian-la-te** [comment]
Fixed, Now we can merge 2 models (I have importer)
