### ISSUE TITLE
vala-panel-appmenu plugin FTBFS

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#85]
I'm trying to build `vala-panel-appmenu` plugin against `vala-panel` 0.3.63 but it FTBS. As can be seen from the log snippet below it would seem that the name of the headers may have changed in newer versions of `vala-panel` that `vala-panel-appmenu` is try to reference?

```
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/lib/valapanel-plugin-appmenu.c:25:24: fatal error: vala-panel.h: No such file or directory
 #include <vala-panel.h>
```

The full log is here:

  * https://launchpadlibrarian.net/319708783/buildlog_ubuntu-artful-amd64.vala-panel-appmenu_0.4.4-2~artful1.0_BUILDING.txt.gz

**Comment by rilian-la-te** [comment]
try latest release, yes, it is. In 0.4 series I was changed plugin interface and configuration (from dir-based to file-based).

**Comment by rilian-la-te** [comment]
But it is vala-project-packages bug.

**Comment by flexiondotorg** [comment]
Try the latest release of what? `vala-panel-appmenu` 0.5.0?

**Comment by rilian-la-te** [comment]
yes.

**Comment by rilian-la-te** [comment]
so, this is fixed?

**Comment by flexiondotorg** [comment]
Yes, just about to submit a pull-request to vala-project-packages.
