### ISSUE TITLE
Since 0.5.0 MATE applet D-BUS service files don't reference their location

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-panel-appmenu#87]
Prior to `vala-panel-appmenu` 0.5.0 the MATE panel applets were installed in architecture specific directories, for example `/usr/lib/x86_64-linux-gnu/mate-panel/appmenu-mate` and the D-BUS service files correctly referenced those locations.

Since 0.5.0 MATE panel applets are now installed `/usr/lib/mate-panel` but the D-BUS service files still reference the architecture specific locations.

**Comment by flexiondotorg** [comment]
@rilian-la-te This issue is not fixed :-(

In 0.5.1 the issue is that  `usr/share/mate-panel/applets/org.vala-panel.appmenu.mate-panel-applet` has the following content, which is multi-arch. 

``` 
[Applet Factory]
Id=AppmenuAppletFactory
Location=/usr/lib/x86_64-linux-gnu/mate-panel/appmenu-mate
Name=Appmenu applet factory
InProcess=false
```

While `usr/share/dbus-1/services/org.mate.panel.applet.AppmenuAppletFactory.service` reflects the install location.

```
[D-BUS Service]
Name=org.mate.panel.applet.AppmenuAppletFactory
Exec=/usr/lib/mate-panel/appmenu-mate
```

**Comment by rilian-la-te** [comment]
Ok, changed. I am Arch user, so, does not see debian multilib, sorry.
