### ISSUE TITLE
Missing ARM version for Xubuntu

### ISSUE THREAD

**Issue by gameslayer** [rilian-la-te/vala-panel-appmenu#88]
Hey just wanted to ask if you could port to ARM for Xubuntu users

**Comment by rilian-la-te** [comment]
to [vala-project-packages](https://github.com/rilian-la-te/vala-project-packages)

**Comment by gameslayer** [comment]
So I just got to manually install the packages manually and it will work on ARM?

**Comment by rilian-la-te** [comment]
download sources and build deb packages for ARM. If I will be lucky, it will be inside Universe in 17.10.

**Comment by gameslayer** [comment]
Could you please explain how I build these sources for ARM?

**Comment by rilian-la-te** [comment]
If you need debs, go to PPA manual. If you need working appmenu, use README)))
