### ISSUE TITLE
Menu freezes with KDE registrar

### ISSUE THREAD

**Issue by snippins** [rilian-la-te/vala-panel-appmenu#89]
# Environment
OS: Neon, KDE 5.9.x 

When running xfce4-panel inside a KDE environment with vala-panel-appmenu. If I dont turn off KDE own implementation of "com.canonical.AppMenu.Registrar" ("com.canonical.AppMenu.Registrar"), some weird bugs appeared:
- Menu of apps that use DBusMenu (qt&gkt) got stuck, such as Firefox, Krusader, VLC, VSCode, etc.
- After a while the menu plugin will crashed (Xfce4=panel reports it have restarted more than 5 times/hour).

**Comment by snippins** [comment]
I have a minor mistake in the report:

Please read:
`"For gtk apps that use DBusMenu interface (com.canonical.AppMenu.Registrar)"`
as `
"For gtk apps that use DBusMenu interface (com.canonical.dbusmenu)"`

**Comment by rilian-la-te** [comment]
Firefox is not supported. 
Will test with chromium and VSCode. 
About KDE implementation. I will look into Registrar for better outer Registrar support.

**Comment by snippins** [comment]
Chromium is not gtk though, it used something called Aura. I just checked, its HUD works fine.

**Comment by rilian-la-te** [comment]
Atom, Sublime?

**Comment by snippins** [comment]
Sublime works fine but it use MenuModel.
Atom have the same problem as VScode and use DBusMenu.

**Comment by rilian-la-te** [comment]
Ghetto-Skype, other Electron Apps?

**Comment by snippins** [comment]
I dont see the menubar for Ghetto-Skype, just the Appmenu. Skype for linux Beta has the same problem as VScode and Atom.

**Comment by rilian-la-te** [comment]
Ok, please create issue about these in vala-dbusmenu bugtracker. This issue will be for outer (KDE) Registrar.

**Comment by 1931186** [comment]
I had the same [problem](https://github.com/electron/electron/issues/8297) (from where @snippins x-referenced to here) and it is not a registrar issue. While the registrar could expand the Layout when the application first registers itself, that would not make much sense because the menu is designed to change 'on-the-fly'. So the best fix for this is rewriting hud-menu.py

**Comment by snippins** [comment]
@1931186 Thanks for the help. I understand your idea. Would you mind to post your code? 

I just re-check the chromium case. They specifically exposed all the static menu entries, but the HUD also fail to capture the dynamic entries in "History".

**Comment by 1931186** [comment]
[Yeah, of course](https://gist.github.com/1931186/caa0ee955300bc2a40ef55d123b06212), but I doubt it will be of much help because, like I mentioned in the other thread, I rewrote it to export the menu of the active window to a json file and therefore it is completely restructured. I also use a mix of the deprecated [dbus-python binding](https://www.freedesktop.org/wiki/Software/DBusBindings/) and the 'lowlevel' gi.repository.Gio wrapper. Apart from that the [information I've already posted](https://github.com/electron/electron/issues/8297#issuecomment-303793574) is accurate for your case.

**Comment by snippins** [comment]
@rilian-la-te  The reason why KDE daemons **seems to work** is because they call AboutToShow() one time on all first level entry when the app open to fix something else on their side. They do not exposes all the menu entries as I thought. So I think this is actually not a bug, but I will leave it open in case new information come up.

@1931186 I will later discuss with you about your problem in the electron thread.

**Comment by snippins** [comment]
New findings: 

- Using the method suggest by @1931186 - recursively all AboutToShow() and GetLayOut() on the "com.canonical.dbusmenu" interface to expose all the menu work OK, but can not deal with dynamic entries like History & Book Marks (Chromium).
- The KDE fix mentioned above is for Firefox only to deal with some weird "Label Empty" childs prevent their built-in global plasmoid from opening the menu.

**Comment by rilian-la-te** [comment]
1. It is a bug in [vala-dbusmenu](https://github.com/rilian-la-te/vala-dbusmenu/), so, it will requires a rewriting:( vala-dbusmenu is Vala libdbusmenu replacement,
2. Firefox AboutToShow hack is very expensive (and may lead to freezes in another applications). So, I was decided to call AboutToShow when dbusmenu is actually wants showing (here)
```Vala
        private void on_select_cb()
        {
            if (this.submenu != null)
            {
                item.handle_event("opened",null,0);
                item.request_about_to_show();
            }
        }
```

AboutToShow is very expensive, because I reloads all menu after every update (I does not implemented partial reloading).

**Comment by 1931186** [comment]
@snippins Thats weird, chromiums history works for me. Are you sure you implemented it right? You are aware that the code needs to be run every time you start your hud  (or if your hud is persistent: every time theres a change in the menu layout; theres a signal for this on the bus)?

**Comment by snippins** [comment]
@1931186 Yes I do run the code everytime. Weird that atom and VSCode work though. I will check it again tomorrow.

**Comment by 1931186** [comment]
@snippins I just checked and the chromium history-feature does indeed work for me. It may be helpful to run the script I linked and check the output in /tmp/currentMenuLayout.json to see if this is a problem with your implementation or something else.

**Comment by snippins** [comment]
@1931186 Just tested and it also unable to get the Menus. This is how I reproduce it: 

- Open Chromium, open 3 random pages, then close it
- Open it again, run the script in background.
- Now check the history menu, it show a new submenu called "3 tabs". I did not click to it.
- Search in the json, cant find it.
- I run the script again, now it shows everything.

I think I know why though, because I only call AboutToShow() on Submenu that have no child.

**Comment by 1931186** [comment]
@snippins Ok I see where you're coming from now. You're completely right, and neither my script nor the script you linked in the other thread implement this. There is a [submenu property](https://github.com/electron/electron/blob/787bc8570382e98c4f204abff05b2af122e5a422/atom/browser/ui/views/global_menu_bar_x11.cc#L97) for com.canonical.dbusmenu and you [can call AboutToShow()](https://github.com/electron/electron/blob/787bc8570382e98c4f204abff05b2af122e5a422/atom/browser/ui/views/global_menu_bar_x11.cc#L241) on these. Thanks for pointing this out :)

**Comment by snippins** [comment]
@1931186 Last thing on my part is Firefox. I wonder why is the guy patched it for Ubuntu invent those weird "Label Empty" entries. Seriously WHY?

**Comment by 1931186** [comment]
@snippins Could you link the Ubuntu-patch for me? I never looked at it.

**Comment by snippins** [comment]
I am on KDE Neon, which is basically Ubuntu 16.04 so I just pull the source with apt :).

**Comment by 1931186** [comment]
Ah ok. I'm on arch but just found [this](https://aur.archlinux.org/packages/firefox-ubuntu/). I'll try to get it working, so lmk if you found anything new regarding this topic :)

**Comment by snippins** [comment]
Do you where to find the original specification for com.canonical.dbusmenu?

**Comment by 1931186** [comment]
The original probably floats around in some canonical docs but I think you can just use introspect on the dbus ([this one](https://github.com/gnustep/dbuskit/blob/master/Bundles/DBusMenu/com.canonical.dbusmenu.xml) should be accurate tho)

**Comment by snippins** [comment]
@1931186 Thanks figure the Firefox problem out. Updated the [HUD](https://gist.github.com/snippins/ee943f2b25db555ef12107f7cee20241). Not sure where to put the "decode("utf8")" for you though.

**Comment by 1931186** [comment]
@snippins Nice. Just putting `gtk_bus_name, gtk_menu_object_path, gtk_app_object_path = [i.decode("utf8") if isinstance(i, bytes) else i for i in [gtk_bus_name, gtk_menu_object_path, gtk_app_object_path]]` in line 341 should fix it.

Sorry for removing the link, I thought I had posted to the wrong thread...

**Comment by snippins** [comment]
@1931186 Thanks, updated it. Also I just fixed a bug where not sending "closed" events cause problems when interacting with Firefox using keyboard.

**Comment by rilian-la-te** [comment]
Now it is working?

**Comment by rilian-la-te** [comment]
With KDE Registrar?

**Comment by snippins** [comment]
I am on KDE Neon with GTK 3.18. So I could not build master. (>=3.20)

**Comment by rilian-la-te** [comment]
Change gtk requrement) if it builds, test it)

**Comment by snippins** [comment]
My version failed to build with

"gdbus-codegen: error: no such option: --output-directory"

**Comment by rilian-la-te** [comment]
Which version of glib do you have?

**Comment by snippins** [comment]
Wait a bit, I broke something, need to fix my packages. :(

**Comment by snippins** [comment]
I have version 2.50

**Comment by rilian-la-te** [comment]
Should work then. I will look for it)

**Comment by rilian-la-te** [comment]
Try latest build with gtk modification, please)))

**Comment by snippins** [comment]
It builds but crash with xfce4-panel 4.12. I will get a log for you later. Thanks

**Comment by rilian-la-te** [comment]
I need log and when it crashes, sorry. But it works for me.

**Comment by snippins** [comment]
It crashes right when trying to add the plugin to the panel:

This is the log where I add the plugin to the panel.

`(process:7998): xfce4-panel-wrapper-CRITICAL **: Wrapper appmenu-3: Failed to open plugin module "/usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libappmenu-xfce.so": /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libappmenu-xfce.so: undefined symbol: gtk_scrolled_window_set_propagate_natural_width.
xfce4-panel(external): appmenu-3: child exited with status 256
xfce4-panel-Message: Plugin appmenu-3 has been automatically restarted after crash.
xfce4-panel(external): appmenu-3: scheduled a respawn of the child
xfce4-panel(external): appmenu-3: child spawned; pid=7999, argc=8

(process:7999): GLib-WARNING **: (/build/glib2.0-2YWLGJ/glib2.0-2.50.0/./glib/gerror.c:405):g_error_new_valist: runtime check failed: (domain != 0)

(process:7999): xfce4-panel-wrapper-CRITICAL **: Wrapper appmenu-3: Failed to open plugin module "/usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libappmenu-xfce.so": /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libappmenu-xfce.so: undefined symbol: gtk_scrolled_window_set_propagate_natural_width.
xfce4-panel(external): appmenu-3: child exited with status 256`

This seems to be the problem: `undefined symbol: gtk_scrolled_window_set_propagate_natural_width`

**Comment by rilian-la-te** [comment]
This is gtk+3.20 symbol. You do not have it on 3.18.

**Comment by snippins** [comment]
I checked here and it say the symbol is introduced with gtk 3.22.
https://developer.gnome.org/gtk3/stable/api-index-3-22.html

**Comment by rilian-la-te** [comment]
I will rise version requirement then)

**Comment by snippins** [comment]
Things seem fine. I will give it another day and then close the bug :)

**Comment by snippins** [comment]
The plugin eventually crashed after a a long session. :(  Though honestly I am not sure how to reproduce or is it even because of KDE Registra. It happens on two machine with the same setup.  

This will take sometimes for me to test because of work. And since I planned to take time to set up vala-panel in my next free periods. I will only able to do some testing again in the 1 or 2 more weeks. :(

**Comment by rilian-la-te** [comment]
If it works, please, close this.
