### ISSUE TITLE
How to build this on Debian?

### ISSUE THREAD

**Issue by BrigDan** [rilian-la-te/vala-panel-appmenu#90]
Your readme doesn't really state how to build this, if you make it more intuitive it would be far better for myself and anyone else trying to install it. Thank you.

**Comment by tiledman** [comment]
I too am having this issue

**Comment by rilian-la-te** [comment]
You need a deb or just working appmenu?

If deb, ask @flexiondotorg . (and see vala-project-packages)

If build for work - ask me and provide info about your DE and panel.

**Comment by BrigDan** [comment]
I want to have the topmenu for xfce panel, I can't find how to build the program for Debian.

**Comment by BrigDan** [comment]
That was a big help, you should probably add this to your readme!

**Comment by rilian-la-te** [comment]
But I do not do anything yet))
