### ISSUE TITLE
Undo hiding xfce menubar

### ISSUE THREAD

**Issue by xoumi** [rilian-la-te/vala-panel-appmenu#92]
I've been having a fair bit of issue setting this up, problem's probably on my side so I'll look into it later some day. For now, I can't seem to revert the changes the XFCE commands did to hide the menubars.
I tried changing the two entries to false, that didn't help so I removed the entires, which didn't help either.
Thanks for the assistance

**Comment by rilian-la-te** [comment]
What OS are you using? What issues are you have?

**Comment by xoumi** [comment]
![2017-06-07-102826_1920x1080_scrot](https://user-images.githubusercontent.com/24864287/26863037-85feecec-4b6d-11e7-9f57-a2c7b2e717c0.png)

The screenshot answers everything I suppose. I also figured out how to get the menu back using `gtk-show-menubar` and `gtk-window-shows-menubar`

As you can see, I'm getting the "gimp" menu but none of the others (file, edit etc). If it did work correctly I should get the rest as well right ?

**Comment by rilian-la-te** [comment]
Do you installed and enabled appmenu-gtk-module? Configured it?

**Comment by xoumi** [comment]
If you're talking about this: https://aur.archlinux.org/packages/appmenu-gtk-module-git/
then yes, installed it.

As for configuring it, I'm using fish as my shell so the bash script doesn't work but 
echo $GTK_MODULES gives canberra-gtk-module:unity-gtk-module 
echo $UBUNTU_MENUPROXY gives 1

So I thought those were the correct values already. Should I change the GTK_MODULES variable ?

**Comment by rilian-la-te** [comment]
yes. this is appmenu-gtk-module, not unity-gtk-module

**Comment by xoumi** [comment]
Okay changing the GTK_MODULES var to appmenu-gtk-mdule worked for most applications.
Some still aren't working but I'll look into the other issues here.
Thanks regardless, working fine now.

**Comment by rilian-la-te** [comment]
what are not working?

Known:
1. Firefox
2. QtCreator 4.3 (they explicitly disabled it)

**Comment by xoumi** [comment]
Well to be exact, an application called Typora, which is what led me look into this global menu solution.
I don't even know if Typora is based on gtk or qt. It's not opensource either so I have no way of knowing.[https://typora.io/](url)
The menubar of this application is global in native unity but seems to still display inside window for me. Not a major issue though.
