### ISSUE TITLE
Disable Menus Under Window Titlebar Xfce

### ISSUE THREAD

**Issue by MggMuggins** [rilian-la-te/vala-panel-appmenu#94]
Alright, I'm running the Appmenu under Xfce4, and it works great! My only problem is that now I have two sets of menus. Here's a minimal screenshot:
![doublemenus](https://user-images.githubusercontent.com/16041213/26860053-72f1fce6-4b01-11e7-92de-f9388c38ec0c.png)
I'm sure this is a bad question, but I don't think it's a trivial solution. How do I remove the set of menus from the window and only use the ones appmenu provides?

**Comment by niyasc** [comment]
Are you using an Ubuntu based system? If so, Ubuntu includes some patches specific to unity and this causes application menu to stay there even when panel-menu is configured.

**Comment by rilian-la-te** [comment]
Did you see a hints?

**Comment by rilian-la-te** [comment]
Especially, this hint for XFCE users from README:
```xfconf-query -c xsettings -p /Gtk/ShellShowsMenubar -n -t bool -s true && xfconf-query -c xsettings -p /Gtk/ShellShowsAppmenu -n -t bool -s true```

**Comment by rilian-la-te** [comment]
Do you fix this issue?

**Comment by MggMuggins** [comment]
I'm running Manjaro.
The command you provided worked for PCManFM, LibreOffice, etc.

Gnome terminal and Opera are still not working, but it's progress. I have menus for Opera in Unity, so any way to move them in Xfce?

**Comment by rilian-la-te** [comment]
Gnome Terminal is not working outside Ubuntu, sorry.
About Opera - see Hints about chromium.

**Comment by MggMuggins** [comment]
I did read the Readme, but it did not adequately explain what the instructions were doing. Granted, I missed the chromium section, but the installation instructions have absolutely no information to indicate what following those instructions actually does.

**Comment by rilian-la-te** [comment]
Sorry. Can you offer improvements for README?

**Comment by MggMuggins** [comment]
I apologize, I got a little.. hurt, when I realized what I had done (not read things well, be a pain, etc.)...

Anyway, I would suggest some kind of disclaimer stating that issues such as this one will be closed, because they are answered on the README.
Also some of these instructions seem to be either distro or DE specific, so some  may not apply to all users. Some clarification could be helpful. 

You could include distro-specific instructions inside the installation instructions, that way both things above are addressed basically at once. If you make those steps seem imperative, less people will skip them.

Going top down on the instructions:
I'm not sure I understand the first instruction, because I found a file by the same name in ```~/.config```. This goes into the distro-specific thing. The user also doesn't edit it, so I'm not sure I understand why it is there.
For the files you have to create, make sure they aren't already there. This seems fairly obvious, but you will always have that one guy who asks...
Explain the gtkrc-2.0 and 3.0 edits. I can assume what these mean, but a little clarification would be nice.
The xfce command could use some clarification, because it is not clear why it has to be executed, or how it is different from the gtkrc edits.

Another thing that I noticed: For Arch (on Manjaro), the AUR unity-gtk-module-standalone-bzr is not required. I'm running fine without it (as far as I know...). Could you explain what that package does someplace?

I'd be willing to open a PR, but I can't do all the work. If you explain what everything does, then I'm willing to organize things.
