### ISSUE TITLE
Error vala-panel-git AUR - Manjaro 17.1

### ISSUE THREAD

**Issue by dprevidelli** [rilian-la-te/vala-panel-appmenu#95]
Yaourt -S vala-panel-git

==> Fazendo download do PKGBUILD de vala-panel-git do AUR...
x .SRCINFO
x PKGBUILD
x vala-panel.install
rilian commented on 2016-04-24 11:56			 
See #25 in Github, this is upstream issue.

masolit commented on 2016-07-08 15:24			 
== Starting prepare()...
== Starting pkgver()...
== Removing existing $pkgdir/ directory...
== Starting build()...
-- The C compiler identification is GNU 6.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for RPMTools... - rpmbuild NOT FOUND
-- Found Vala: /usr/bin/valac  
-- checking for a minimum Vala version of 0.24
--   found Vala, version 0.32.1
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'gtk+-3.0=3.12;glib-2.0=2.40;gio-2.0=2.40;gio-unix-2.0=2.40;gthread-2.0=2.40;libpeas-1.0=1.2;libpeas-gtk-1.0=1.2;gmodule-2.0=2.40'
--   
--   
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:363 (message):
A required package was not found
Call Stack (most recent call first):
/usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:528 (_pkg_check_modules_internal)
CMakeLists.txt:95 (pkg_check_modules)

-- Configuring incomplete, errors occurred!

masolit commented on 2016-07-08 15:34			 
add gobject-introspection to Dependencies

Brottweiler commented on 2016-08-07 11:55			 
Getting errors:

-- Checking for modules 'gtk+-3.0=3.16;glib-2.0=2.44;gio-2.0=2.44;gio-unix-2.0=2.44;gthread-2.0=2.44;libpeas-1.0=1.2;libpeas-gtk-1.0=1.2;gmodule-2.0=2.44;libuuid'
--   No package 'libuuid' found
CMake Error at /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:424 (message):
A required package was not found
Call Stack (most recent call first):
/usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_internal)
CMakeLists.txt:96 (pkg_check_modules)

qark commented on 2016-08-27 15:23			 
Scanning dependencies of target applet-api-new
[ 18%] Building C object lib/applets-new/CMakeFiles/applet-api-new.dir/applet-widget.c.o
/tmp/makepkg/vala-panel-git/src/vala-panel/lib/applets-new/applet-widget.c: In function 'vala_panel_applet_widget_class_init':
/tmp/makepkg/vala-panel-git/src/vala-panel/lib/applets-new/applet-widget.c:147:22: error: 'g_cclosure_user_marshal_VOID__ENUM_INT_INT' undeclared (first use in this function)
g_cclosure_user_marshal_VOID__ENUM_INT_INT,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/makepkg/vala-panel-git/src/vala-panel/lib/applets-new/applet-widget.c:147:22: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [lib/applets-new/CMakeFiles/applet-api-new.dir/build.make:82: lib/applets-new/CMakeFiles/applet-api-new.dir/applet-widget.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:332: lib/applets-new/CMakeFiles/applet-api-new.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
== ERROR: A failure occurred in build().
Aborting...
== ERROR: Makepkg was unable to build vala-panel-git.

vala-panel-git 0.3.8-1  (2017-05-08 13:08)
( Pacote sem suporte: Potencialmente perigoso ! )
==> Editar PKGBUILD ? [S/n] ("A" para abortar)
==> ------------------------------------------
==> n

==> DependÃªncias de vala-panel-git:
 - gtk3 (jÃ¡ instalado)
 - libwnck3 (jÃ¡ instalado)
 - libpeas (jÃ¡ instalado)
 - gobject-introspection (jÃ¡ instalado)
 - cmake (jÃ¡ instalado) [makedepend]
 - vala (jÃ¡ instalado) [makedepend]

==> Editar vala-panel.install ? [S/n] ("A" para abortar)
==> ----------------------------------------------------
==> n

==> Continuar a compilaÃ§Ã£o de vala-panel-git ? [S/n]
==> ------------------------------------------------
==> s

==> Compilando e instalando pacote
==> Criando o pacote: vala-panel-git 0.3.8-1 (qui jun  8 10:31:08 -03 2017)
==> Verificando as dependÃªncias de tempo de execuÃ§Ã£o...
==> Verificando as dependÃªncias de tempo de compilaÃ§Ã£o...
==> Obtendo fontes...
  -> Clonando repositÃ³rio vala-panel do tipo git...
Cloning into bare repository '/tmp/yaourt-tmp-danilo/aur-vala-panel-git/vala-panel'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Tempo esgotado para conexÃ£o
github.com[1: 192.30.253.112]: errno=Tempo esgotado para conexÃ£o

==> ERRO: Falha ao baixar o repositÃ³rio vala-panel do tipo git
    Abortando...
==> ERRO: Makepkg nÃ£o conseguiu compilar vala-panel-git.
==> Reiniciar a compilaÃ§Ã£o de vala-panel-git ? [s/N]
==> ------------------------------------------------
==>

**Comment by rilian-la-te** [comment]
english, please.

**Comment by rilian-la-te** [comment]
AFAIK i understand this language, you have broken Internet connection.

**Comment by rilian-la-te** [comment]
So,closing this.
