### ISSUE TITLE
"Desktop" menu items do nothing on Xubuntu 16.04

### ISSUE THREAD

**Issue by gcvl** [rilian-la-te/vala-panel-appmenu#96]
Hi,
I'm on latest master running Xubuntu 16.04 and I noticed that when focus is on desktop the "Desktop" menu items do nothing, while the "Files" items work and open listed files.

**Comment by rilian-la-te** [comment]
Do you have installed xfce4-settings-manager?

**Comment by gcvl** [comment]
Yes, it's preinstalled.

**Comment by rilian-la-te** [comment]
What console says?

**Comment by gcvl** [comment]
If you need some specific log tell me and I'll post it ;)

**Comment by rilian-la-te** [comment]
I need log from console vala-panel run with appmenu.

**Comment by gcvl** [comment]
This appears in /var/log/syslog after the applet crashed when I clicked on "Desktop" and "System Settings":


Jun 12 00:58:27 giannino-HP-EliteBook-8460p kernel: [  105.204351] panel-1-appmenu[4027]: segfault at 28 ip 00007f42fa351d0b sp 00007fff0b605c80 error 4 in libgio-2.0.so.0.4800.2[7f42fa2b4000+180000]

Jun 12 01:02:24 giannino-HP-EliteBook-8460p kernel: [  342.005798] panel-1-appmenu[4041]: segfault at 28 ip 00007f3708b54d0b sp 00007ffe4663a7b0 error 4 in libgio-2.0.so.0.4800.2[7f3708ab7000+180000]

This appears in /var/log/apport.log:

ERROR: apport (pid 4033) Mon Jun 12 00:58:28 2017: called for pid 4027, signal 11, core limit 0
ERROR: apport (pid 4033) Mon Jun 12 00:58:28 2017: executable: /usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-2.0 (command line "/usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-2.0 /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libappmenu-xfce.so 1 10486256 appmenu AppMenu\ Plugin Display\ AppMenu\ (Global\ Menu)")
ERROR: apport (pid 4033) Mon Jun 12 00:58:28 2017: gdbus call error: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

ERROR: apport (pid 4033) Mon Jun 12 00:58:28 2017: debug: session gdbus call: 
ERROR: apport (pid 4033) Mon Jun 12 00:58:30 2017: wrote report /var/crash/_usr_lib_x86_64-linux-gnu_xfce4_panel_wrapper-2.0.1000.crash
ERROR: apport (pid 4830) Mon Jun 12 01:02:24 2017: called for pid 4041, signal 11, core limit 0
ERROR: apport (pid 4830) Mon Jun 12 01:02:24 2017: executable: /usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-2.0 (command line "/usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-2.0 /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libappmenu-xfce.so 1 10486256 appmenu AppMenu\ Plugin Display\ AppMenu\ (Global\ Menu)")
ERROR: apport (pid 4830) Mon Jun 12 01:02:24 2017: gdbus call error: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

ERROR: apport (pid 4830) Mon Jun 12 01:02:24 2017: debug: session gdbus call: 
ERROR: apport (pid 4830) Mon Jun 12 01:02:24 2017: this executable already crashed 2 times, ignoring

If I click on "Desktop settings" nothing simply happens.
I'm not sure how to get console log but if you need just ask.

**Comment by rilian-la-te** [comment]
install vala-panel and appmenu for it.
And get log.

Or use PANEL_DEBUG=gdb and show me a log

**Comment by gcvl** [comment]
I don't have vala-panel in the archives and your master vala-panel requires GTK+3 >= 3.22 while I have 3.18.
I did:
PANEL_DEBUG=gdb
Enabled logging
xfce4-panel -q
xfce4-panel
Click on Desktop/System Settings -> Crash.
gdb.txt is empty but this appears in terminal:

(wrapper-1.0:28118): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GObject'

(wrapper-1.0:28118): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer

(wrapper-1.0:28118): GLib-GObject-CRITICAL **: g_signal_handler_is_connected: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(wrapper-2.0:28134): Gtk-CRITICAL **: gtk_label_set_text_with_mnemonic: assertion 'str != NULL' failed

(wrapper-1.0:28118): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GObject'

(wrapper-1.0:28118): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer

(wrapper-1.0:28118): GLib-GObject-CRITICAL **: g_signal_handler_is_connected: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(wrapper-2.0:28134): Gtk-CRITICAL **: gtk_label_set_text_with_mnemonic: assertion 'str != NULL' failed

** (wrapper-2.0:28134): WARNING **: appmenu-desktop.vala:189: Unknown desktop environment

xfce4-panel-Message: Plugin appmenu-2 has been automatically restarted after crash.

** (wrapper-2.0:28416): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-fx5qkHOj0Q: Connessione rifiutata

(wrapper-2.0:28416): Gtk-CRITICAL **: gtk_label_set_text_with_mnemonic: assertion 'str != NULL' failed

(wrapper-1.0:28118): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GObject'

(wrapper-1.0:28118): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer

(wrapper-1.0:28118): GLib-GObject-CRITICAL **: g_signal_handler_is_connected: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(wrapper-2.0:28416): Gtk-CRITICAL **: gtk_label_set_text_with_mnemonic: assertion 'str != NULL' failed

**Comment by gcvl** [comment]
When I click on "Desktop Settings":

** (wrapper-2.0:28416): WARNING **: appmenu-desktop.vala:163: Unknown desktop environment

Esecuzione del processo figlio "gnome-control-center" non riuscita (File o directory non esistente)
Translated : child process execution "gnome-control-center" failed (file or folder not existent)

**Comment by gcvl** [comment]
Now i did:

PANEL_DEBUG=1 xfce4-panel
Click on Desktop/System Settings
Got:

** (wrapper-2.0:398): WARNING **: appmenu-desktop.vala:189: Unknown desktop environment

xfce4-panel(external): appmenu-2: child exited with status 139
xfce4-panel-Message: Plugin appmenu-2 has been automatically restarted after crash.
xfce4-panel(external): appmenu-2: scheduled a respawn of the child
xfce4-panel(external): appmenu-2: child is unembedded
xfce4-panel(external): appmenu-2: child spawned; pid=640, argc=8

** (wrapper-2.0:640): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-fx5qkHOj0Q: Connessione rifiutata
xfce4-panel(external): appmenu-2: child is embedded; 6 properties in queue

**Comment by gcvl** [comment]
xxxyyyx_gdb_appmenu_log when clicking "System Settings":

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeba56700 (LWP 1681)]
[New Thread 0x7fffeb255700 (LWP 1682)]
[New Thread 0x7fffeaa54700 (LWP 1683)]
[New Thread 0x7fffea1f1700 (LWP 1684)]

Thread 1 "panel-2-appmenu" received signal SIGSEGV, Segmentation fault.
0x00007ffff39b6d0b in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#0  0x00007ffff39b6d0b in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#1  0x00007fffed67784c in appmenu_menu_widget_desktop_activate_control () from /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libappmenu-xfce.so
No symbol table info available.
#2  0x00007ffff6617fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#3  0x00007ffff6629fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#4  0x00007ffff6632d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#5  0x00007ffff663308f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#6  0x00007ffff39ced45 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#7  0x00007ffff7380c1e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#8  0x00007ffff7380c54 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#9  0x00007ffff74c5b56 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#10 0x00007ffff6617fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#11 0x00007ffff6629fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#12 0x00007ffff6632d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#13 0x00007ffff663308f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#14 0x00007ffff75e50de in gtk_widget_activate () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#15 0x00007ffff74c2746 in gtk_menu_shell_activate_item () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#16 0x00007ffff74c2a74 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#17 0x00007ffff74a509a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#18 0x00007ffff66181d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#19 0x00007ffff66324b8 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#20 0x00007ffff663308f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#21 0x00007ffff75e2c3c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#22 0x00007ffff74a23be in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#23 0x00007ffff74a41bc in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#24 0x00007ffff7011d92 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#25 0x00007ffff5f2e197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#26 0x00007ffff5f2e3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#27 0x00007ffff5f2e712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#28 0x00007ffff74a3395 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#29 0x0000555555557749 in main ()
No symbol table info available.
rax            0x5555557d1030	93824994840624
rbx            0x555555b75c70	93824998661232
rcx            0x4	4
rdx            0x0	0
rsi            0x1	1
rdi            0x5555557d1030	93824994840624
rbp            0x0	0x0
rsp            0x7fffffffcb00	0x7fffffffcb00
r8             0x7fffed676610	140737176364560
r9             0x555555b75c70	93824998661232
r10            0xaaaaaaaaaaaaaaab	-6148914691236517205
r11            0x5555557e9128	93824994939176
r12            0x0	0
r13            0x7fffed676750	140737176364880
r14            0x555555869270	93824995463792
r15            0x555555b09a50	93824998218320
rip            0x7ffff39b6d0b	0x7ffff39b6d0b
eflags         0x10206	[ PF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0

**Comment by rilian-la-te** [comment]
Ok, what is XDG_CURRENT_DESKTOP value?

**Comment by gcvl** [comment]
echo $XDG_CURRENT_DESKTOP gives XFCE.

**Comment by rilian-la-te** [comment]
Appmenu version?

**Comment by gcvl** [comment]
0.3.1 from Webupd8 ppa, couldn't find anywhere else.

**Comment by gcvl** [comment]
I installed vala-panel 0.3.5 and vala-panel-appmenu-common and xfce4-vala-appmenu from your PPA but Appmenu does not show up among panel applets and I can't add it on the panel.

**Comment by rilian-la-te** [comment]
Your version is too old. Ask @flexiondotorg, where to find latest version (he is a maintainer for deb-based)

**Comment by flexiondotorg** [comment]
PPA is here - https://launchpad.net/~ubuntu-mate-dev/+archive/ubuntu/global-menu

**Comment by gcvl** [comment]
Thank you, flexiondotorg!
I could install the latest releases and I can confirm this issue is gone!
Now it works exactly like it should.
