### ISSUE TITLE
cannot find unity-gtk-parser.h

### ISSUE THREAD

**Issue by haelmchen** [rilian-la-te/vala-panel-appmenu#97]
HI, I just set up a new system and tried to install your appmenu. I'm getting this error when installing it.

```
CMake Error at lib/cmake_install.cmake:100 (file):
  file INSTALL cannot find
  "/tmp/yaourt-tmp-mario/aur-vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/unity-gtk-module/lib/lib/unity-gtk-parser.h".
Call Stack (most recent call first):
  cmake_install.cmake:38 (include)


make: *** [Makefile:74: install] Fehler 1
make: Verzeichnis „/tmp/yaourt-tmp-mario/aur-vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/unity-gtk-module“ wird verlassen
==> FEHLER: Ein Fehler geschah in package_appmenu-gtk-module-git().
    Breche ab...

```

System:
OS: Antergos
Kernel: 4.11.3-1-ARCH
DE: Xfce

In the path there is double 'lib' and in my folders there is onyl one 'lib' folder. I guess something went wrong there.

**Comment by SolarAquarion** [comment]
ag "lib/lib/"       
unity-gtk-module/lib/cmake_install.cmake
101:    "/home/solaraquarion/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/unity-gtk-module/lib/lib/unity-gtk-parser.h"
102:    "/home/solaraquarion/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/unity-gtk-module/lib/lib/unity-gtk-menu-shell.h"
103:    "/home/solaraquarion/.cache/pacaur/vala-panel-appmenu-xfce-git/src/vala-panel-appmenu/unity-gtk-module/lib/lib/unity-gtk-action-group.h"
