### ISSUE TITLE
Failed to build in manjaro

### ISSUE THREAD

**Issue by geek21** [rilian-la-te/vala-panel-appmenu#99]
I can't build vala-panel-appmenu .. I get this error : 
`vala-dbusmenu.vapi:66.2-66.44: error: `DBusMenu' already contains a definition for `GtkItemIface'
	public interface GtkItemIface : GLib.Object {
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:150.2-150.44: note: previous definition of `GtkItemIface' was here
	public interface GtkItemIface : GLib.Object {
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-dbusmenu.vapi:72.2-72.40: error: `DBusMenu' already contains a definition for `Iface'
	public interface Iface : GLib.DBusProxy {
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:156.2-156.40: note: previous definition of `Iface' was here
	public interface Iface : GLib.DBusProxy {
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-dbusmenu.vapi:92.2-92.19: error: `DBusMenu' already contains a definition for `Status'
	public enum Status {
	^^^^^^^^^^^^^^^^^^
vala-panel.vapi:176.2-176.19: note: previous definition of `Status' was here
	public enum Status {
	^^^^^^^^^^^^^^^^^^
Compilation failed: 11 error(s), 0 warning(s)
make[2]: *** [lib/CMakeFiles/appmenu-valapanel.dir/build.make:71: lib/appmenu-valapanel_valac.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:792: lib/CMakeFiles/appmenu-valapanel.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

`
please help me to install it to get mate-hud and gobal menu to work

**Comment by rilian-la-te** [comment]
What vala - panel version are you have?

**Comment by geek21** [comment]
vala-panel-appmenu-valapanel-git  0.4.4-2
vala-panel-appmenu-mate-git  0.4.4-2

**Comment by rilian-la-te** [comment]
`vala-panel-git` -?

**Comment by geek21** [comment]
vala-panel-git  0.3.8 is installed I'm tiring to build vala-panel-appmenu-mate-git 0.4.4-2 from AUR

**Comment by rilian-la-te** [comment]
Vala-panel is too old. Update it or build vala-panel-appmenu without its support.

**Comment by rilian-la-te** [comment]
I will close it. If updating ```vala-panel-git``` does not help, I will reopen it.
